### ISSUE TITLE
Consult , How to iterate the. po file?

### ISSUE THREAD

**Issue by 625781186** [git-cola/git-cola#1019]
Please advise how to update the `.po` file every time the `git-cola. pot`  file content changes without overwriting the previous translation.

**Comment by 625781186** [comment]
May be use 'msgmerge' ?

**Comment by davvid** [comment]
My bad, I should probably be generating the `git-cola.pot` file more often.  I believe the workflow is that we are supposed to periodically run `make pot` to update the `git-cola.pot` file, commit the result, and then run `make po` to update the `.po` files with new/missing translations.

The `Makefile` defines the `make` targets/commands, and the files that implement the `build_mo` (`make mo`) and `build_pot` (`make pot`) commands via `setup.py` are provided by `extras/build_mo.py` and `extras/build_pot.py`.

Let me know if that makes sense.  We should document what `setup.py` is doing under the hood and document the high-level workflow before closing this issue.  We should close this issue with a commit that updates `README.md` with a `Translation` section that documents the workflow.  We'll also document the underlying `msgmerge` and `msgcat` commands that are used by the makefile targets so that someone could run the steps manually and see that it's just the standard `gettext` tools and workflows under the hood.

Thanks for the report.

**Comment by 625781186** [comment]
Thanks , 
I know how to do it.
But there are some mistakes : 
![image](https://user-images.githubusercontent.com/30521429/69935076-ce1db400-150e-11ea-8b1d-4876aeae6ea5.png)

https://github.com/git-cola/git-cola/blob/master/extras/build_pot.py
Line 121 may be need add `encoding="utf8"`

**Comment by davvid** [comment]
Maybe in the `open(src, 'rU')` line, try making it say `open(src, 'rb') so that it opens it in binary, and then change the read line to be `content = f.read().decode('utf-8')`.  Please let me know if that works and we'll get that patched ASAP.

**Comment by abid1998** [comment]
@davvid Is help required for this issue ? I am a new contributor i can help.

**Comment by davvid** [comment]
Thank you @abid1998 , yes help would be much appreciated. I just pushed in a commit that I believe may address the issue, but I don't have the same (windows `gbk`) locale environment available for testing, so I can't verify whether it helps or not.

Please let me know if 64e4aef0bb1abdc3fb55d70ce187611ba20e7d32 improves the situation.

**Comment by abid1998** [comment]
I am using Cola + Ubuntu won't be able to verify this.

**Comment by davvid** [comment]
Feel free to reopen if there are any issues.
