### ISSUE TITLE
git commit amend is very slow, but only for git-cola... why?

### ISSUE THREAD

**Issue by nevion** [git-cola/git-cola#1021]
OS Linux
git command line based amends and rebases are fast.

git cola seems to be doing something more.  Something that freezes the UI for ~1 minute before doing things like a popup dialog saying I've pushed the commit already, or something.

**Comment by davvid** [comment]
Curious, is it faster if you run `git gc --aggressive`?

**Comment by nevion** [comment]
@davvid I've tried it before, no it doesn't.
Can you point me at where I should look in the sources to see what "extra" work is going on besides the git commit --amend call?

**Comment by davvid** [comment]
https://git-cola.readthedocs.io/en/latest/git-cola.html#git-cola-trace

That'll point out the Git commands that cola is running.  It's the usual check the filesystem for files stuff, which can be slow in large repos.  There are settings to make cola skip untracked files that can be helpful if that's the slow part.

https://git-cola.readthedocs.io/en/latest/git-cola.html#gui-displayuntracked corresponds to the "Display Untracked Files" in the preferences.  That can speed things up when disabled.

I think there's also a `cola.turbo` mode, but it's probably not what you're running into.  https://git-cola.readthedocs.io/en/latest/git-cola.html#cola-turbo

Let me know if you're able to figure out what's going on when running in trace mode.

I'll leave this open so that we can get this information into the documentation so that next time we can just point someone to a faq.

**Comment by davvid** [comment]
I doubt the "check if the commit is pushed" part would take very long, as it's a purely local operation, but we'll see since the trace should help narrow that down.

A good entry points into seeing what's going on is the `cola/models/main.py` Model class has an `update_status()` method that reads a lot of Git details, and usually happens after committing, etc.

`cola/cmds.py` is where you'll find most of the actions (e.g. where we call `self.git.commit(...)` with `amend=True` which gets translated to `git commit --amend` in class Commit.

**Comment by nevion** [comment]
if you flush in your trace logging the command executed before it completes, it may be a little easier to see other problems but the problematic command looks to be this:
time  git -c diff.suppressBlankEmpty=false branch -r --contains=HEAD

real    0m19.971s
user    0m19.955s
sys     0m0.016s

Why do this and can it be skipped without breaking other functionalities?

**Comment by nevion** [comment]
poke @davvid 

I suspect I can probably get by with commenting out a line, I must admit I haven't pulled the sources yet for the purposes of auditting.  I'm guessing there is 1-2 lines though that if I comment out, I will have bypassed this in the near term while you ponder about the long term options (user opt-in/out option?).   Anyway it may save me some 20+ minutes if you could hint at where I would comment out such logic - line numbers in master / a link to the snippet in question.  I appreciate the direction so far.

**Comment by davvid** [comment]
That's super interesting.  What version of Git are you using?  I think I recall some discussion on the mailing list in the last year or so about `git tag --contains` and `git branch --contains` being slow, and that there are ways to speed it up in newer versions.

http://git.661346.n2.nabble.com/Why-is-quot-git-tag-contains-quot-so-slow-td5241514.html  (older)

http://git.661346.n2.nabble.com/git-branch-contains-is-slow-with-a-lot-of-branches-td7628097.html


We support multiple versions of Git so I think the right answer would be to make it possible to opt-out of the `git branch -r --contains HEAD` check.  This seems like it deserve its own checkbox in the settings as it can make a huge performance difference.

How many remote branches do you have?  `git branch -r | wc -l` can answer that question.

Don't run this blindly, but if you have a remote repo with lots of ephemeral remote branches then doing `git fetch --prune origin` (or any other remote name instead of "origin") will prune any remote branch names from your local cache that have been deleted remotely.  This can help performance of that command if you happen to have hundreds of ephemeral branches that should be cleaned up.

In any case, we'll leave this issue open so that we can add an option.

**Comment by davvid** [comment]
I'm writing the tooltip right now.  Does, "Check whether a commit has been published when amending" sound descriptive enough?

**Comment by nevion** [comment]
@davvid  - thousands of branches are tracked (not 10s of thousands, though).  It's not because old branches, though that was about 20% (thanks for that tip!).

I was using 2.7.4, and 2.23.0.  I just updated to git latest stable and confirmed it was still just as slow.

I updated to HEAD on git-cola, checked that new preference and it works instantly now.  Thanks!
