### ISSUE TITLE
Installation from source with pip fails with KeyError exception

### ISSUE THREAD

**Issue by allista** [git-cola/git-cola#1037]
ENV: Ubuntu 18.04, python 3.6
GitCola version: 3.6
With all previous versions this worked as expected.

```sudo -H pip3 install .
Processing /home/storage/Games/Downloads/git-cola-3.6
Building wheels for collected packages: git-cola
  Building wheel for git-cola (setup.py) ... done
  Created wheel for git-cola: filename=git_cola-3.6-cp36-none-any.whl size=474898 sha256=56e055b93bc050224fb477553702f615455435917817620fe97ffd360baa6d04
  Stored in directory: /root/.cache/pip/wheels/3c/2e/3e/345e3ddbe3133f38267eb759bac00f5080cd0c653e40b5a930
Successfully built git-cola
Installing collected packages: git-cola
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 455, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/__init__.py", line 62, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 861, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/req/req_install.py", line 495, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/wheel.py", line 492, in move_wheel_files
    dest = scheme[subdir]
KeyError: 'share'
```

**Comment by davvid** [comment]
What command are you using to get a working install?  Previously we've always supported `make install prefix=/path/to/the/install` which under the hood is doing `python setup.py install ...`.

This could be a recent bug in pip itself, especially if you've never seen it before.  Our setup.py did change in the last year to handle `#!` update in the helper share scripts, and perhaps that's tripping up pip because it doesn't know what to do when it sees the `share` directory.

If you're trying to install into a virutalenv then set your prefix to the virtualenv directory when installing and things should just work.

Here's an example that uses the system version of python to pickup PyQt5, and uses `vx` to manage the environment.  The source trees are available in `~/src` and a copy of vx is symlinked into `~/bin/vx` under the assumption that you have `$HOME` in your `$PATH`.

```sh
# these commands assume you're here, and already have the repo cloned in ~/src/git-cola
mkdir -p ~/src
cd ~/src
git clone git://github.com/git-cola/git-cola.git

# setup vx, clone the repo and symlink the script as ~/bin/vx
# I believe ubuntu's .bashrc/profile setup already has ~/bin in $PATH,
# but you may need to set that up yourself.
git clone git://github.com/davvid/vx.git
ln -s ../src/vx/vx ~/bin/vx
rehash || export PATH

# pyqt5 is provided by debian/ubuntu
sudo apt install python3-pyqt5

# create a virtualenv called "env36"
python3 -mvenv --system-site-packages env36

# install cola into that virtualenv
vx env36 make -C git-cola install prefix=$PWD/env36

# now you can run from that virtualenv
vx env36 git cola
```

Alternatively, maybe you want to use a virtualenv separately from ubuntu that uses pyqt provided by pip.

```
python3 -mvenv env36
# install PyQt5
vx env36 pip install PyQt5
# install cola
vx env36 make -C git-cola install prefix=$PWD/env36

# run
vx env36 git cola
```

As a test -- there's a section in setup.py where we assign to `build_helpers.helpers` from b130523eef3e075c3e7522d0b6cc0c2c463e569d.

Try commenting out those three lines in setup.py and if it works then there's something going on there.

Nonetheless, let me know what pip command you're using so I can try it locally.

**Comment by davvid** [comment]
This should be fixed in the latest versions. We use `options.data_files` in `setup.cfg` these days and no longer rely on distutils.
