### ISSUE TITLE
enable per worktree preferences

### ISSUE THREAD

**Issue by xieofxie** [git-cola/git-cola#1038]
Currently worktrees will share same config.

Related https://github.com/git-cola/git-cola/pull/1036

**Comment by davvid** [comment]
Hmm I think the core reason here has to do with git. I think git uses a a shared .git/config across all of the worktrees (if you look at the `.git` file used in git worktrees you'll see that they all point to a common .git storage area).

Unfortunately there's not much we can do about this currently since this is kind of how Git itself is currently designed, so our hands are tied a little.

I might be mistaken and maybe newer versions of git have a facility that allows for per-worktree `git config` values. If that comes online then we can certainly look into supporting it. Thanks for the heads-up.
