### ISSUE TITLE
Could not load the Qt platform plugin "windows" in "" even though it was found

### ISSUE THREAD

**Issue by kapitanluffy** [git-cola/git-cola#1042]
I can't seem to run git-cola (latest release). Below are the errors. I already set the `QT_QPA_PLATFORM_PLUGIN_PATH` environment variable but it did not work.

![image](https://user-images.githubusercontent.com/485799/73907374-08c21500-48e1-11ea-8f26-055a89319ad5.png)

![image](https://user-images.githubusercontent.com/485799/73907389-12e41380-48e1-11ea-9bfe-826d1011e609.png)

**Comment by davvid** [comment]
Hmm it's been a while since I've touched our `pynsist.cfg`.  I suspect that removing `bitness = 32` and updating pyqt to 5.13.1 and sip to 4.19.19 and that might do the trick.

I don't have any Windows machines available for testing this theory, though.  Could you perhaps try installing `pynsist` so that you can try building the installer with those tweaks?

The config file is pynsist.cfg.  and the script that typically gets run to generate an installer is `./contrib/win32/run-pynsist.sh`

Hopefully you'll be able to test it and confirm whether this fixes the issue.

**Comment by kapitanluffy** [comment]
I think I can't generate the installer since I am on windows but I won't mind testing it for you. Just send over the file.

**Comment by kapitanluffy** [comment]
I accidentally opened git-cola by reflex and worked. Weird. Gonna close this for now.
