### ISSUE TITLE
Running git-cola with Adwaita Dark Theme

### ISSUE THREAD

**Issue by Lonerider2010** [git-cola/git-cola#1043]
When running git-cola with adwaita dark theme, everything is shown as expected with two exceptions:
during publishing (push) the two dialogs for git authentication (username and password) are not shown in the dark theme. My environment: Raspbian Buster with XFCE, adwaita-qt and qt5ct installed.

**Comment by davvid** [comment]
Those dialogs can be replaced by installing an alternative askpass program.

Raspian.. hmm.  I'm guessing you're not on gnome, then, otherwise `ssh-askpass-gnome` can be installed and then you can get git to use it by setting `GIT_ASKPASS` to `/usr/bin/ssh-askpass-gnome` in your environment (or the other config methods documented below).

`apt-cache search askpass` on my debian/testing machine also finds `lxqt-openssh-askpass` which might be more appropriate on raspian.

Those dialogs are actually initiated by git internally.

https://git-scm.com/docs/gitcredentials#_requesting_credentials

Personally, I use ssh keys so I don't ever expect to get prompted by passwords.  If you're using https urls for pushing, you might be able to simplify things by using ssh urls with public key authentication instead.
