### ISSUE TITLE
[UI] More clearly separate the parts of the staging area

### ISSUE THREAD

**Issue by hoijui** [git-cola/git-cola#1057]
That's how it looks for me (Debian testing, XFCE):

![Screenshot](https://i.ibb.co/F5M36G0/git-cola-staging-area.png)

Apart form being italic, _Staged_, _Modified_ and _Untracked_ look exactly like a file.
It is hard to get a quick overview for me because of that.

Would it be possible to have them in separate windows (like in `git-gui`) or with some kind of separator line or space or so?

(related PR: https://github.com/git-cola/git-cola/pull/1030)

**Comment by hoijui** [comment]
related to https://github.com/git-cola/git-cola/pull/1030

**Comment by davvid** [comment]
Hello. In the Preferences/Settings there's a setting called "Indent Status paths" in the "Appearance" tab.

This will make it much easier to visually separate the items. There's also an option for "Bold on dark headers instead of italic" which makes the headers stand out even more by giving them a separate background color.

Please try out these settings and let me know if they improve the experience for you.

**Comment by hoijui** [comment]
ahh yes, the indenting is definitely doing it, thank you! :-)
I would strongly suggest to make this default on, but either way, I am good now, thanks!
