### ISSUE TITLE
Missing main menu in 3.6.1

### ISSUE THREAD

**Issue by cherio** [git-cola/git-cola#1058]
Just installed `git-cola` fresh on `Ubuntu 20.04` and the main menu bar is entirely missing.

When I run it from terminal it gives one WARNING and I am not sure if this is related to the missing menu.

`(python3:33604): dbind-WARNING **: 00:30:34.715: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.`

I managed the WARNING to go away by running `export NO_AT_BRIDGE=1` before launching `git-cola` but that didn't bring the menu back.

**Comment by cherio** [comment]
I managed to eliminate the warning by enabling/disabling the Accessibility. It looks like the warning is not related to the issue. The warning was being produced by many other applications that had main menu successfully rendered.

This happens in xubuntu 20.04 with git-cola installed from the official repository.

**Comment by tefletch** [comment]
I just started experiencing the "Missing Main Menu" issue as well.  I'm running Ubuntu 20.04 and Python 3.8.10.   The git-cola version is 3.6.

I've been using git-cola for years without issue and nothing has recently changed in my environment.  In fact, other users on the same workstation do not see the problem.  I assumed that a user-specific problem could be remedied by deleting ~/.config/git-cola/settings, but that did not fix the problem.

I imagine that somewhere along the line I clicked the wrong gui control since the menu disappearance was sudden.  Is there a more thorough reset that I can perform?

**Comment by davvid** [comment]
Kindly open an Ubuntu bug with these details ~ they'll firstly need to upgrade to the latest versions and then they can also provide some guidance around how Qt is being configured.

I suspect that the `QT_QPA_PLATFORMTHEME` environment variable might be related. Please see the notes here for more details:

https://git-cola.readthedocs.io/en/latest/git-cola.html#dark-mode-and-window-manager-themes


If that variable is related then `env -u QT_QPA_PLATFORMTHEME git cola` should give different results.
