### ISSUE TITLE
Does not support tilting window manager on Linux Mint Cinnamon

### ISSUE THREAD

**Issue by liquidscorpio** [git-cola/git-cola#1075]
Thanks for the excellent software!

Is it possible to get this to work with tiling window manager on a gnome derived DE like Cinnamon. Right now, I cannot get it to work with the default tiling manager shipped with Linux Mint Cinnamon.

**Version Info**:
Mint 19
Cinnamon 3.8.9
Git Cola version 3.0 
Python (/usr/bin/python3) 3.6.9 [GCC 8.4.0] 
Git 2.17.1 
Qt 5.9.5 
QtPy 1.3.1 
PyQt5 5.10.1

**Comment by davvid** [comment]
Ah, interesting.  The cola version listed is pretty old, but your platform should be totally supported.

I develop cola on debian myself.  If you're able to clone the repo, what happens when you run `./bin/git-cola` ?

Our integration with the window manager happens through Qt, so there may be some settings that could influence the behavior.

I believe I have `QT_QPA_PLATFORMTHEME=qt5ct` set in my environment, so that Qt uses the same theme as the window manager.  You could also test:

```
env QT_QPA_PLATFORMTHEME=qt5ct ./bin/git-cola
```

..to see if it affects anything.  In the past I had to use `Gtk2` as the value, but that was a long time ago ;-)

Let me know what you're seeing.  If there's something custom that we need for cinnamon then reporting this to the debian/mint packagers might allow them to set something up system-wide to handle it.  It's likely not just cola -- all PyQt5 apps are likely affected.  We're a good test case, though.

Thanks for the heads-up.  Let me know what we can do to help dig into this.  Linux Mint support is a top priority.

**Comment by liquidscorpio** [comment]
Thanks for the quick response @davvid! 

I will try this over the weekend and follow-up here.

**Comment by liquidscorpio** [comment]
Clone from the latest master is working with the tiling window manager. :tada: 

Thanks for the help, really appreciated! Closing the ticket.
