### ISSUE TITLE
Help: How to alias 'git gui' to 'git cola' ?

### ISSUE THREAD

**Issue by Gruntfuggly** [git-cola/git-cola#1083]
Can anybody tell me how to create an alias so that when I enter 'git gui' in the terminal, it runs git cola instead? I've tried using
```
git config --global alias.gui cola
```

But it still runs the tcl/tk git-gui.

**Comment by davvid** [comment]
Git does not usually allow overriding built-in commands with aliases (for example `git log`) cannot be overridden with an alias.

But, we can accomplish this for `git-gui` specifically if we arrange to have a script or symlink to `git-cola` named `git-gui` found by `git` by placing it in its path.

Note: this only works because `git-gui` itself is an external command.

One way to do this is create a `bin` directory in your home directory for keeping scripts, and then create a `git-gui` shell script in there that launches `git-cola`.  The following commands will do just that:

```
mkdir -p ~/bin
cat <<"EOF" >~/bin/git-gui
#!/bin/sh
git-cola "$@"
EOF
chmod +x ~/bin/git-gui
```

In order to make this work we have to modify Git's `$PATH` by setting a value in the environment.  From https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables

> GIT_EXEC_PATH determines where Git looks for its sub-programs (like git-commit, git-diff, and others). You can check the current setting by running git --exec-path.


This means we can override where Git looks for external commands by setting this variable.  It supports a colon-separated list of paths.  A typical place to set this up is in your `~/.bash_profile` by adding a snippet that looks like this:

```
if test -z "$GIT_EXEC_PATH"
then
    GIT_EXEC_PATH="$HOME/bin:$(git --exec-path)"
    export GIT_EXEC_PATH
fi
```

Then, open a new shell and try running `git gui` -- this should now launch cola instead.  This variable is effectively telling git to look in your `~/bin` directory first before running external commands.  We retain Git's original location in there as well, so this is safe.

When git sets up its `$PATH` [here](https://github.com/git/git/blob/v2.24.3/exec-cmd.c#L304) it copies the value from `GIT_EXEC_PATH` verbatim to the front of the `$PATH` environment variable, so it's safe to specify multiple paths separated by colons.

**Comment by davvid** [comment]
If you're on debian then another approach (that wouldn't require modifying `GIT_EXEC_PATH`) might be to uninstall `git-gui` using something like `sudo apt remove git-gui`

In that approach you would need to add `$HOME/bin` to your `$PATH`.  Git will then launch your `~/bin/git-gui` script because it won't find the real `git-gui` in its `git --exec-path` after we uninstall it.

**Comment by Gruntfuggly** [comment]
The script solution sounds perfect - thank you!

**Comment by Gruntfuggly** [comment]
For anybody else finding this, it worked great for me on Linux, but refused to work on my mac.
On my mac I ended up uninstalling git-gui (which I'd previously installed via homebrew) and then created a symlink in the bin directory to the git-cola exe, called git-cola, i.e.
`ln -s /usr/local/bin/git-cola git-gui`
This works because git also looks in your bin for commands starting with `git-`.
