### ISSUE TITLE
The diff issues with v2 vs v3 git-cola in Ubuntu20.04

### ISSUE THREAD

**Issue by RaghavendhraK** [git-cola/git-cola#1085]
![V3](https://user-images.githubusercontent.com/2741110/92695048-85c8d780-f365-11ea-83cf-876f9b05c9e3.png)
![V2](https://user-images.githubusercontent.com/2741110/92695041-83ff1400-f365-11ea-8365-18549e89d42a.png)

Hi,
We can see the diff tool is showing the entire file with highlights in new git-cola version whereas the older one is showing only the lines where the change has happened. Not sure, whether this change is due to python versions. But this issue is happening. I am finding difficulty in looking for the changes while committing the changes.

New Git Versions
Git Cola version 3.7 
Linux-5.4.0-47-generic-x86_64-with-glibc2.29 
Python (/usr/bin/python3) 3.8.2 (default, Jul 16 2020, 14:00:26) [GCC 9.3.0] 
Git 2.25.1 
Qt 5.15.0 
QtPy 1.9.0 
PyQt5 5.15.0 

Older Git version
Git Cola version 3.2 (v3.2) 
Linux-5.4.0-47-generic-x86_64-with-Ubuntu-20.04-focal 
Python (/snap/git-cola/136/usr/bin/python) 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609] 
Git 2.7.4 
Qt 5.5.1 
QtPy 1.4.2 
PyQt5 5.5.1 

Could you please help me with this.
Thanks,
Raghu

**Comment by davvid** [comment]
In the preferences there's a setting for "Number of Diff Context Lines" that could be related.

Otherwise, check the sprocket menu in the diff tool and see if it has "Show whole surrounding functions of changes" enabled.

That code hasn't really changed in a while.  We basically look at the output of `git diff`.


You can debug it and try following along on the command-line by running `env GIT_COLA_TRACE=1 git cola` and it will print out all of the git commands that it's running.

One possibility is actually the Git version difference as well.  Let me know what you find.

**Comment by RaghavendhraK** [comment]
Hi,

I checked with the trace env and the command to git diff has these much options, which shows all the file content
`git -c diff.suppressBlankEmpty=false diff -M --patience --submodule --no-color --no-ext-diff --unified=9992 -- src/app/common/header/header.component.ts`
 
But when I removed the `unified=9992`, it shows the correct way.
Now, the question is how to remove this option unified=9992 from git-cola preference.

Thanks,
Raghu
