### ISSUE TITLE
Unable to open Spyder on Ubuntu

### ISSUE THREAD

**Issue by w142236** [git-cola/git-cola#1092]
I know this issue is old, but I tried opening Spyder using Ubuntu after installing pyqt5, and I'm still getting the exact same error. 

I activated my virtualenv and then ran:

`pip3 install spyder`

Then,
 `pip3 install pyqt5`

and finally: `spyder3` and I get the following:

  File "/usr/bin/spyder3", line 11, in <module>
    load_entry_point('spyder==3.3.6', 'gui_scripts', 'spyder3')()
  File "/usr/lib/python3/dist-packages/spyder/app/start.py", line 178, in main
    from spyder.app import mainwindow
  File "/usr/lib/python3/dist-packages/spyder/app/mainwindow.py", line 48, in <module>
    requirements.check_qt()
  File "/usr/lib/python3/dist-packages/spyder/requirements.py", line 41, in check_qt
    import qtpy
  File "/usr/lib/python3/dist-packages/qtpy/__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

**Comment by davvid** [comment]
Hello, please report this at https://github.com/spyder-ide/qtpy

Quick tip -- I don't think you're using the "spyder3" from your virtualenv.  Check the virtualenv's `bin/` directory -- does it have a script called `spyder3`?

What is the name of your virtualenv directory?  `env38`?  If so, it would be at `./env38/bin/spyder3`

Your error message basically suggests that it is not running the script from the virtualenv but rather from `/usr/bin/spyder3`, which is outside your virtualenv.


Since you mentioned virtualenvs, I'll now plug `vx` because it's how I use virtualenvs so that I don't have to pollute my shell environment with the `activate / ... / deactivate` shenanigans.

https://github.com/spyder-ide/qtpy


The workflow using `vx` would be (assuming python3.8, but you can name it whatever you want):

```
python3.8 -m venv env38
vx env38 pip install spyder
vx env38 spyder3
```

You don't need to install PyQt5 separately -- installing spyder handles it.  I just tested this and it Works for Me (TM) ;-) but hopefully it works for you too.

**Comment by davvid** [comment]
Last tip -- if you want your global `/usr/bin/spyder3` install to work then the path of least resistance is to use your package manager to install PyQt5, eg.

```
sudo apt install python3-pyqt5 python3-pyqt5.qtmultimedia
```

**Comment by w142236** [comment]
> 
> 
> Hello, please report this at https://github.com/spyder-ide/qtpy
> 
> Quick tip -- I don't think you're using the "spyder3" from your virtualenv. Check the virtualenv's `bin/` directory -- does it have a script called `spyder3`?
> 
> What is the name of your virtualenv directory? `env38`? If so, it would be at `./env38/bin/spyder3`
> 
> Your error message basically suggests that it is not running the script from the virtualenv but rather from `/usr/bin/spyder3`, which is outside your virtualenv.
> 
> Since you mentioned virtualenvs, I'll now plug `vx` because it's how I use virtualenvs so that I don't have to pollute my shell environment with the `activate / ... / deactivate` shenanigans.
> 
> https://github.com/davvid/vx
> 
> The workflow using `vx` would be (assuming python3.8, but you can name it whatever you want):
> 
> ```
> python3.8 -m venv env38
> vx env38 pip install spyder
> vx env38 spyder3
> ```
> 
> You don't need to install PyQt5 separately -- installing spyder handles it. I just tested this and it Works for Me (TM) ;-) but hopefully it works for you too.

I went ahead and uninstalled Spyder and reinstalled it with the virtualenv activated:

`source venv/bin/activate`
`sudo pip3 install -U spyder`
`spyder3`
Then I got an error about it not being able to find the display, so I ran:
`export DISPLAY=localhost:0.0 `
`spyder3`
The spyder logo appears so that issue seems to be fixed. 

But, it then crashes before the GUI can even open with the errors:

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-quit'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
shared memfd open() failed: Function not implemented
Trace/breakpoint trap (core dumped)

No clue what the issue is. [Apparently this is an issue with nvidia graphics cards, but I don't seem to have the exact same problematic "mesa" library.](https://askubuntu.com/questions/834254/steam-libgl-error-no-matching-fbconfigs-or-visuals-found-libgl-error-failed-t) 
I ran the following to check
` sudo ldconfig -p | grep -i gl.so`

and got the following:

        libwayland-egl.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libwayland-egl.so.1
        libcogl.so.20 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcogl.so.20
        libQt5OpenGL.so.5 (libc6,x86-64) => /lib/x86_64-linux-gnu/libQt5OpenGL.so.5
        libGL.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libGL.so.1
        libEGL.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libEGL.so.1

I don't know if anyone of these libraries are the problem or perhaps I'm missing the library that it wants? Any ideas or do you think I should try opening up a new issue?

-Thank you for getting back to me!

**Comment by w142236** [comment]
> 
> 
> Last tip -- if you want your global `/usr/bin/spyder3` install to work then the path of least resistance is to use your package manager to install PyQt5, eg.
> 
> ```
> sudo apt install python3-pyqt5 python3-pyqt5.qtmultimedia
> ```

Oh! And I made sure to install those as well as you suggested. Still getting the same issue.

**Comment by davvid** [comment]
There is a very unfortunate step there -- the `sudo pip3 install ...` step should *never* be run.

Don't ever run `pip` under `sudo` -- it basically just overwrote your system files in `/usr` and did who-knows-what to the system's python installation.

The way virtualenv works is it sets environment variables and in your active shell environment.  When you `sudo`, it's very common for `sudo` to clear environment variables so that it runs in a secure context, and that behavior can and will effectively "escape" the virtualenv.

For example:

https://unix.stackexchange.com/questions/91541/why-is-path-reset-in-a-sudo-command

`$PATH` is indeed something sourcing the virtualenv activate script manages.  Like I said, this is total shenanigans and is why I use `vx`, and never ever use `sudo pip3` or let python's package management tools nearby anything with elevated system permissions.

Regarding the OpenGL stuff, yes, please open an issue with the spyder team since they'll know what to do about it.  It does seem like your opengl setup might be in an unexpected state.  Does `glxgears` work?  If not, then it could be related to nvidia drivers or something along those lines.
