### ISSUE TITLE
Windows installer contains unused DLLs taking up space

### ISSUE THREAD

**Issue by nyanpasu64** [git-cola/git-cola#1094]
I just installed Git Cola 3.7 64-bit on Windows 10. The folder in Program Files is 176.2 MB, which is very large, and many of the files are unnecessary.

- `C:\Program Files\git-cola\pkgs\PyQt5\Qt\bin\opengl32sw.dll` is 20 megabytes, and the app runs fine with OpenGL software rasterization removed. Same with `d3dcompiler_47.dll` and `libGLESv2.dll`.
- `Qt5Quick.dll` and `Qt5Qml.dll` are fairly small, but probably unnecessary considering you don't use QML. I ended up removing a pile of dlls, both Qt5[Foo].dll and a few others.
- `pkgs\PyQt5\Qt\plugins` can be cleaned up. `sceneparsers` is bloated and unused, all DLLs in `platforms` can be removed except `qwindows.dll` (IDK what qminimal.dll is used for), and else except `imageformats`, `styles`, and `iconengines`.
- `pkgs\PyQt5\Qt\qml` is small in size, but has 1033 files, and extracting them one by one slows down installation on NTFS.
- Don't know if `pkgs\PyQt5\Qt\translations` is in use.
- Why are there both `pkgs\PyQt5\Qt\bin\libcrypto-1_1-x64.dll` and `Python\libcrypto-1_1.dll`?

I managed to cut my folder size to just under 100 MB without removing any files in use.

I'm not sure how you're packaging Qt. You use a makefile, qtpy (which I haven't touched), and don't use windeployqt (which I've seen used for C++ Qt programs).

**Comment by davvid** [comment]
Thanks for the tips on how to improve the Windows packages.

We use pynsist[1]  for packaging.  See `contrib/win32/run-pynsist.sh` and the `pynsist.cfg` file to build an installer from scratch.

pynsist is used because it allows building Windows installers from Linux.  Luckily it seems to support excluding files[2] -- see the "exclude" option.  That option sounds like it should make it possible to trim things down using the recommendations you list above.

The libcrypto bits should probably be left alone, though.  That's just python and Qt each having their own copies.  Can you help us get the `pynsist.cfg` in order?  It looks like we're already excluding the bluetooth libraries, so expanding that out like you've outlined is a great idea.

My trial Windows VM expired again so I won't be able to test any changes to the installer in the near future.  I'll easily procrastinate dealing with Windows in a VM until the end of year, so hopefully someone can beat me to it.

I do need to get the VM working so that I can run hakchi 🎮 again, tho, so it'll happen eventually, but probably not too soon.

[1] https://github.com/takluyver/pynsist
[2] https://pynsist.readthedocs.io/en/latest/cfgfile.html#include-section

**Comment by Mithil467** [comment]
I see a few more files have been added to the exclude section.
But a lot of the files mentioned above are yet to be included.
I am interested to know how to identify what DLLs are safe to be excluded.

I ran git-cola and had a look at the DLLs listed by [process-explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer)

![image](https://user-images.githubusercontent.com/41439841/128819278-5ae2ce74-bbb8-42bf-a47f-98c931e5a602.png)

Are these the only ones being used? Does it mean it is safe to exclude the rest?

**Comment by davvid** [comment]
Use the Help->Keyboard Shortcuts feature and the DAG feature as well. Those will bring in the QtWebEngine and QGrapicsScene stuff which may account for a few more libraries.

If there are any other `Qt*` DLLs that aren't listed then we can consider pruning them. I'm not sure how much space we can save at this point, though. If it's a big enough of a difference I'd be happy to review a PR that trims down. I wouldn't really recommend pruning the Python bits tho.

Thanks for taking a look -- I don't use Windows so I very much appreciate help from Windows users.

**Comment by Mithil467** [comment]
Here's a list of DLLs that I found loaded after using the 2 features you mentioned.

```
pkgs\PyQt5\Qt\bin\libcrypto-1_1-x64.dll
pkgs\PyQt5\Qt\bin\libssl-1_1-x64.dll
pkgs\PyQt5\Qt\bin\Qt5Core.dll
pkgs\PyQt5\Qt\bin\Qt5Gui.dll
pkgs\PyQt5\Qt\bin\Qt5Network.dll
pkgs\PyQt5\Qt\bin\Qt5Svg.dll
pkgs\PyQt5\Qt\bin\Qt5Widgets.dll
pkgs\PyQt5\Qt\plugins\bearer\qgenericbearer.dll
pkgs\PyQt5\Qt\plugins\iconengines\qsvgicon.dll
pkgs\PyQt5\Qt\plugins\imageformats\qgif.dll
pkgs\PyQt5\Qt\plugins\imageformats\qicns.dll
pkgs\PyQt5\Qt\plugins\imageformats\qico.dll
pkgs\PyQt5\Qt\plugins\imageformats\qjpeg.dll
pkgs\PyQt5\Qt\plugins\imageformats\qsvg.dll
pkgs\PyQt5\Qt\plugins\imageformats\qtga.dll
pkgs\PyQt5\Qt\plugins\imageformats\qtiff.dll
pkgs\PyQt5\Qt\plugins\imageformats\qwbmp.dll
pkgs\PyQt5\Qt\plugins\imageformats\qwebp.dll
pkgs\PyQt5\Qt\plugins\platforms\qwindows.dll
pkgs\PyQt5\Qt\plugins\styles\qwindowsvistastyle.dll
pkgs\PyQt5\QtCore.pyd
pkgs\PyQt5\QtGui.pyd
pkgs\PyQt5\QtNetwork.pyd
pkgs\PyQt5\QtWidgets.pyd
pkgs\PyQt5\sip.cp37-win_amd64.pyd
```
I deleted all the DLL files from `pkgs\PyQt5\Qt\` except these and everything seems to work fine.
The pkgs folder size went from 141MB to 89.5MB and the installer size went from 51.8MB to 33.4MB.
