### ISSUE TITLE
black background on the 3.0 app

### ISSUE THREAD

**Issue by jorgekoronis** [git-cola/git-cola#1095]
Hello

For some strange reason I recently started getting the following look and feel of the application git-cola, version 3.0. It displays a black background as you can see on the attached pictures. 

![git-cola screenshot1](https://user-images.githubusercontent.com/71354661/96362728-a38d1780-112f-11eb-998f-95b2949436eb.jpg)
![git-cola screenshot2](https://user-images.githubusercontent.com/71354661/96362729-a425ae00-112f-11eb-9ec1-b34901ecf5b5.png)

I also attach a third screenshot that displays the correct look and feel of the application before this happened.
![git-cola screenshotCorrectBackground](https://user-images.githubusercontent.com/71354661/96362819-52315800-1130-11eb-9c55-6ad6da8e3908.png)

I would appreciate if anyone could tell me what I might have done wrong to get the black background displayed on the first two screenshots and how I can fix it.

Cheers!

**Comment by davvid** [comment]
Ubuntu?  Do you have `qt5ct` installed?  There's a note in the docs about Qt and how it integrates with the window manager's theming.

https://git-cola.readthedocs.io/en/latest/git-cola.html#dark-mode-and-window-manager-themes

Long story short, check the value of `QT_QPA_PLATFORMTHEME` in your environment since it may or may not be related.

Usually on Linux there's a way to get it to follow your window manager theme using Qt.

If you'd like to diverge from that, there's way to do so using both Qt, or you can configure cola's preferences and select one of the light themes that ship with cola.

The "default" theme is the one that follows Qt's defaults, and thus can be made to integrate with the window manager's theming.

**Comment by kurtmckee** [comment]
@davvid I recommend closing this issue. Additional information is needed, and the ticket has not been updated in 2.5 years.
