### ISSUE TITLE
Fedora33 ModuleNotFoundError: No module named 'PySide

### ISSUE THREAD

**Issue by lighta** [git-cola/git-cola#1108]
Hi, I'm having an issue with the git-cola launch.
```
[lighta@localhost ~]$ git-cola --prompt
Traceback (most recent call last):
  File "/usr/share/git-cola/lib/qtpy/__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
  File "/usr/lib64/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/git-cola", line 40, in <module>
    from cola.main import main
  File "/usr/share/git-cola/lib/cola/main.py", line 6, in <module>
    from . import app
  File "/usr/share/git-cola/lib/cola/app.py", line 16, in <module>
    from qtpy import QtCore
  File "/usr/share/git-cola/lib/qtpy/__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
```

Seem kinda the same issue as here :
#979
#787

I did try to install pyside as mentionned in those ticket, but the system persist.
```
[lighta@localhost ~]$ sudo dnf install PyQt5 python3-pyside2
Last metadata expiration check: 1:12:02 ago on Thu 07 Jan 2021 11:19:23 AM CET.
Package python3-qt5-5.15.0-4.fc33.x86_64 is already installed.
Package python3-pyside2-1:5.15.2-1.fc33.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

Also when trying with pip, the package can't be installed
```
Defaulting to user installation because normal site-packages is not writeable
Collecting pyside
  Downloading PySide-1.2.4.tar.gz (9.3 MB)
     |████████████████████████████████| 9.3 MB 1.7 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-j9vm1m7r/pyside/setup.py'"'"'; __file__='"'"'/tmp/pip-install-j9vm1m7r/pyside/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-6_8m38b6
         cwd: /tmp/pip-install-j9vm1m7r/pyside/
    Complete output (1 lines):
    only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[lighta@localhost ~]$ python --version
Python 3.9.1
```
Due to pyside not supporting python3.9.

Since, this error occur quite frequently can't you just ship pyside with the package ? and or remove that dependancies completly ?

**Comment by nateridderman** [comment]
Just did a `brew upgrade` and ran into this on my Mac (Big Sur)

**Comment by nateridderman** [comment]
Not sure what caused my breakage, or if it's related to the Fedora issue. I fixed it by installing pip3, then installing PyQt5 via pip3. It was already installed via brew, but Git Cola couldn't find that. On a personal note, as a OSS user who is not experienced with python dep mgmt, it all feels like a hot mess.

**Comment by davvid** [comment]
Oi, it's true that we do receive a bit of reports from fedora and macos users that have run into issues when python gets upgraded.

The common thing between Linux and macOS is that the first line in the script with `#!` defines which python will run.  Check the output of `which git-cola` and verify that the script it reports points to the right python.

The fedora thing is certainly a packaging issue, though the fedora package looks normal:
https://src.fedoraproject.org/rpms/git-cola/blob/f33/f/git-cola.spec

If there are modules installed elsewhere, then maybe you somehow ended up with multiple pythons and tweaking the script to point at the right python will get things working?


If you'd like a workaround, I think the common advice these days would be to use a virtualenv.  eg. throw https://github.com/davvid/vx in your $PATH and you can do this:

```
# setup virtualenv and install dependencies
python3 -m venv env3
vx env3 pip install -r requirements/requirements-dev.txt
vx env3 pip install PyQt5

# OR you can use pyside2.  Only do this if PyQt5 is not available for some reason.
# You only need PyQt5 or PySide2, not both.  We prefer PyQt5.
# vx env3 pip install PySide2

# Install cola into the virtualenv
vx env3 make install prefix=$PWD/env3

# Now you can run cola from inside the virtualenv
vx env3 git-cola
```

The only time you have to recreate the virtualenv is when python gets upgraded, which should correspond to upgrading macOS or fedora.

We try to rely on the package maintainers who already provide PyQt5 for their users so that we don't have to make users have multiple copies of Qt (since it's not exactly tiny), but sometimes using a virtualenv might be better if you'd like to try the latest versions or for those occasions when there are packaging issues on macos or fedora.

I'll leave this open so we can document what to do to run cola in a virtualenv.

Would you mind filing an issue with the rpms/git-cola fedora package so that the fedora maintainers can see this?

https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&classification=Fedora&component=git-cola&product=Fedora&product=Fedora%20EPEL

Ditto for homebrew.

Over the years I've seen these kinda issues from macOS users, where macOS gets upgraded and their existing homebrew installation ends up in a jacked-up state.

One solution I've seen that works in the past on macOS is doing a full `brew upgrade --verbose` and then uninstall and reinstall qt5 and git-cola.  That's sometimes enough for it to tickle things back into a working state.


For fedora, if you've used pip3 to install stuff then there's either your system install just got stomped over by pip (if you ran it as root, which is always a bad idea) or it left behind a bunch of crud in your `~/.local/lib/python*` directories.  Cleaning that stuff up and using a virtualenv will be easier to manage.

Bummer that fedora is running into these issues.  Homebrew has always been hacky, but fedora is something I would expect to have this sorted out.  Is the fedora machine in need of a `sudo dnf upgrade --refresh` or something along those lines?

**Comment by bhavanki** [comment]
For Homebrew, this got things working for me after the Big Sur upgrade.

```
brew reinstall pyqt@5
```

The latest pyqt from Homebrew is version 6, maybe that has something to do with it.
