### ISSUE TITLE
Can't write a commit summary starting with '#'

### ISSUE THREAD

**Issue by JonathanOldenburg** [git-cola/git-cola#1109]
The commit summary input doesn't let me use '#' as the first character.
![Peek 27-01-2021 21-02](https://user-images.githubusercontent.com/11889654/106073574-191e6180-60e9-11eb-86e6-4e7313a591a5.gif)

Commiting from command line with '#' at the start of summary works well
![git-commit](https://user-images.githubusercontent.com/11889654/106073763-6ef30980-60e9-11eb-9fe1-3571448aff4f.png)

I need this because we use "#<issue_id>" on the commit message to attach issues to the commits in the company where I work.

**Comment by JonathanOldenburg** [comment]
I took a look into the code, and see that there is a validation for that field that prevents from starting with the comment char:
`    def validate(self, string, idx):
        """Scrub whitespace and validate the commit message"""
        string = string.lstrip()
        if string.startswith(self._comment_char):
            state = self.Invalid
        else:
            state = self.Acceptable
        return (state, string, idx)`

This piece of code was taken from commitmsg.py

But it doesnt seem to make sense to me, because comments are not supported on summary and may start with '#'

**Comment by davvid** [comment]
cola passes a file to `git commit` to create commits, similar to what happens when you run `git commit` interactively and it throws you into an editor.

Git itself strips lines that start with `#`.  You can change that, though, by configuring `core.commentChar` to something else.  For example:

    git config --global core.commentChar '%'

If you run that then cola will treat `%` as the comment character, and you can have summaries that start with `#`.

**Comment by davvid** [comment]
We don't pass the commit message directly via `git commit -m '<msg>'` because we allow `# comments` in the commit message.  For example, if you are in the middle of a merge, cola will read the `.git/COMMIT_MSG` file that Git generates, and that file has comments in it.

We follow the standard git conventions where `git commit` throws you into an editor and if you enter a summary that starts with `#` then git will ignore that line.  We prevent that state by preventing that input on the summary line, as it would no longer be valid when read from a file by git.

So this is basically the intended behavior, and also why we implemented support for `core.commentChar`.  Hope that helps.

https://git-scm.com/docs/git-config#Documentation/git-config.txt-corecommentChar

**Comment by JonathanOldenburg** [comment]
I've changed the core.commentChar property and it works well now. Thanks!
