### ISSUE TITLE
Feature suggestion: find inside files

### ISSUE THREAD

**Issue by GiovanniSM20** [git-cola/git-cola#1116]
I just got to know the program and found it very interesting mainly to centralize the information and do some things that I didn't even know were possible with git. I would like to make a suggestion of a feature which is "find inside files" (preferably modified ones) - currently it has "find files" - I for example like to make modifications but sometimes I want to commit only one line but with the amount of files very hard to find. I could add it but I would like to know if it is in the interest of the maintainers / contributors / users.

**Comment by davvid** [comment]
Are you looking for the `grep` tool?  Hit ctrl-g to bring up the `grep` tool (same as `git cola grep`) and then start typing some text. It'll find that text inside all files.

**Comment by GiovanniSM20** [comment]
Good tool but I still can't see, for example, what I had before for example and what I have now. Supposing that for example I have a variable with a value and I deleted it but I don't remember what file I did it in, it would be nice to see the file I edited for example and which line I removed and added so I could commit this line. Only searching for this value/variable.

**Comment by Tyler799** [comment]
I second this - though I'm not sure in the same way. I would really love to be able to search through my staged and un-staged edits for a file. 

It would be great for catching errors like "Did I remember to stage all places where I changed a name from X to Y?". If I can quickly search through the un-staged changes in a file for a word, I can easily detect these before they become a problem.

**Comment by davvid** [comment]
I think there's a pretty sweet feature we can come up with to handle this. These are really great ideas.

I'm imagining a small "Find" bar similar to what you get when you Ctrl-f in firefox. It would let you search across all the uncommitted changes and support Next/Previous for navigating the diffs.

When it finds a match it would select that file in the status tree and focus the line that matched. Performance pitfall: in order to implement this across all files it requires running `git diff`, so it is O(N) over the size of the changes and can be slow, so one option might be to limit the search to only the currently selected file so that it's fast by default.

I'm a little bummed I already used ctrl-f for the Fetch dialog. Maybe I can swap that for Ctrl-F (capital-F) or alt-f so that this "Find" feature can take over ctrl-f as it's more of an interactive operation and I do like having hotkeys that are familiar (hence ctrl-l, which we borrowed from firefox).

The Find bar would have checkboxes for limiting the search to the Staged, Unmerged, and Modified lists. We'd have them all enabled by default, but we'll also enable "Search in current file only" by default as well, so those checkboxes will only matter when the "current file" option is disabled.

"Match Case" will be disabled by default to allow case-insensitive searching, but the fallback will be "smartcase" searching similar to vim, where we do case-sensitive searching when we notice that they're using an upper-case character anywhere in the search string. "Match Case" is useful for when your search string is lowercase and you only want to find lowercase entries (because lowercase doesn't trigger the Smartcase heuristic).

**Comment by dorian-marchal** [comment]
What about showing a search bar on <kbd>Ctrl+F</kbd> to search in the \*current\* diff, only?
This is what I would expect when hitting <kbd>Ctrl+F</kbd> (the same way browsers allow me to search the current tab on <kbd>Ctrl+F</kbd>, not all tabs).

**Comment by 0xGreen** [comment]
Just start using the tool and absolutely loving it!! Thank you!

I have a question regarding grep. The grep is only greping from files and not from commits history.
For example in grep window:
1. Type "password" and it will list results with password in all files
2. Enable "Shell arguments" type "password -- css" and it list all matches in css folder

But i was wondering if it possible to grep like this:
```bash
git grep password $(git rev-list --all)
# cli command greping password from all files/commit history
```

Thanks!!

**Comment by davvid** [comment]
Thanks for the sugs. Please test the latest from git -- there's now a Ctrl-F search feature in the diff editor that searches the current file, just like a web browser.

I didn't implement the ability to find across all (modified / staged) files, but that can basically be done by selecting the `Modified` or `Staged` header items and searching the diffs within them using Ctrl-F, so it didn't really seem complicating things.

**Comment by davvid** [comment]
Heads-up @0xGreen the Grep tool only looks at the current commit.

You can use the DAG tool to search for commits that contain the text "password" by typing `-Spassword` into the DAG input field. That corresponds to `git log -Spassword`, which tells git to find all commits whose diffs contain the text "password".

This is not quite as convenient as `git grep $(git rev-list --all) 'text'`, but it'll at least filter down to just the commits that introduce or remove that text (rather than every single commit after which the text was added), which is arguably a better birds-eye view.
