### ISSUE TITLE
Feature Request: drop down listing branchs in DAG view

### ISSUE THREAD

**Issue by boxerab** [git-cola/git-cola#1127]
currently I have to remember the branch I want to view or go run `git branch` from command line.
It would be convenient to put this in a drop down where the current text box is. Also, have an option
to list remote branches as well.

**Comment by davvid** [comment]
We actually mostly support this already. There's autocomplete in there for paths, branches and arbitrary refs already. If you start typing they show up.

I think a good enhancement would be to make it so that when you hit the Down arrow it lists all the possible completion values. Right now the Down arrow makes it lose focus and switch to the commit list widget. If it initiated completions then the drop-down would appear.

**Comment by boxerab** [comment]
Thanks, I just check the latest version, and the autocomplete is good enough for me. Going to close this.
