### ISSUE TITLE
git-cola, will it support OAuth

### ISSUE THREAD

**Issue by makitso** [git-cola/git-cola#1132]
Beginning August 13, 2021, github will no longer accept account passwords when authenticating Git operations on GitHub.com.
Will git cola be updated to support OAuth?

**Comment by davvid** [comment]
As long as `git push` supports it, we'll support it. We execute `git` internally and cola will reuse any configuration you've already put in place for authenticating.

That said, I will strongly suggest that you use ssh urls and key-based authentication when interacting with github.

Instead of https://github.com/user/repo.git as your `git config remote.origin.url` remote url (see `.git/config` in your repos), use `git@github.com:user/repo.git` as the URL.

But, I think these are orthogonal ~ I'm talking about the push/pull workflow, and it looks like Github's change is primarily about their REST API usage. The push/pull operations do overlap, though.

From reading https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ (is this the change you're referencing?) we are not affected.

Cola does not use your github authentication tokens or use any github APIs so we generally won't be affected by this change. If you are using https:// urls then switching to ssh will get things happy.

https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh

**Comment by makitso** [comment]
Thanks Davvid, switched to ssh :-)
