### ISSUE TITLE
Unable to clone repository using git cola

### ISSUE THREAD

**Issue by SMatani** [git-cola/git-cola#1147]
![image](https://user-images.githubusercontent.com/47073413/125046083-4e2cd800-e0bb-11eb-913e-a1e0746b059b.png)
Hi,

I am trying to clone repository using git cola. But getting the error as shown in the attached png.

Thanks,
Sonam

**Comment by dschwoerer** [comment]
Does that repository exist?

It is not listed at:
https://github.com/SMatani?tab=repositories

**Comment by davvid** [comment]
True that. In case this is a private repository, first try cloning from the command-line:
```
git clone git@github.com:SMatani/Microservices.git
```

If that works then it'll work in cola too. I'd suggest using the above SSH URL rather than the `https://` URLs for cloning repos that you intend to push into.

I will note that the error messages says "unable to execute git".
* If you're on a Debian or Ubuntu system you can `sudo apt install git` to make Git available.
* If you're on Windows you'll have to download "Git for Windows" and install it.
* If you're on macOS you may need to install Xcode (or the xcode command-line tools). IIRC you can `xcode-select --install` on macOS to install the Xcode Command Line Tools.

Based on the screenshot I believe you're on WIndows. Please let us know if installing [GIt for Windows](https://gitforwindows.org/) fixes this for you.

**Comment by davvid** [comment]
Please also see the [Windows Notes](https://git-cola.readthedocs.io/en/latest/git-cola.html#windows-notes) in the documentation in case you have GIt installed in a non-standard location.

**Comment by SMatani** [comment]
> Does that repository exist?
> 
> It is not listed at:
> https://github.com/SMatani?tab=repositories

It is a private repository.

**Comment by SMatani** [comment]
> True that. In case this is a private repository, first try cloning from the command-line:
> 
> ```
> git clone git@github.com:SMatani/Microservices.git
> ```
> 
> If that works then it'll work in cola too. I'd suggest using the above SSH URL rather than the `https://` URLs for cloning repos that you intend to push into.
> 
> I will note that the error messages says "unable to execute git".
> 
> * If you're on a Debian or Ubuntu system you can `sudo apt install git` to make Git available.
> * If you're on Windows you'll have to download "Git for Windows" and install it.
> * If you're on macOS you may need to install Xcode (or the xcode command-line tools). IIRC you can `xcode-select --install` on macOS to install the Xcode Command Line Tools.
> 
> Based on the screenshot I believe you're on WIndows. Please let us know if installing [GIt for Windows](https://gitforwindows.org/) fixes this for you.

Installing git fixed the issue . Thanks.
