### ISSUE TITLE
Diff not showing in dag. Scenario problem.

### ISSUE THREAD

**Issue by NielBuys** [git-cola/git-cola#1154]
When opening multiple diff tool files the diff in dag stop showing.

To reproduce do the following steps.
1. Open git-dag
2. Right click on a file and press on Launch diff tool.
3. Right click on another file and press on Launch diff tool.
4. While both diff tool windows are open the diff block in git-dag just shows loading. (See screenshot)
5. On closing one of the diff tool windows the diff block on git dag starts to work again.

Git-cola version 3.10.1 - Normal windows install version
Windows 10

NOTE: can't reproduce problem on my linux environment.
![loading bug on windows dag](https://user-images.githubusercontent.com/8427483/130589580-429cab1e-be3e-4287-afe0-ce14ec052753.png)

**Comment by davvid** [comment]
3e51b23d028082923bc989aac5264aa674698cb5 and a8ebb29cdca926fb92cec08246a8b1027440e201 should have eliminated any chance that it's something in the code itself that is causing this behavior.

Windows has all kinds of warts and strange behaviors, like the limitation that the same file cannot be opened by multiple processes. Windows' syscalls block when that happens. The symptoms you describe sound like it's another fallout from the way the Windows OS works.

Since this is a Windows-only issue then the simple explanation is that this is basically a Windows bug. There's nothing cola can do it about it. Even worse, if you were to report this issue to Microsoft they'll just tell you that they won't ever change the behavior because backwards-compatibility is their main selling point.

Sorry about that, but it's not really cola's fault. Thanks for the heads-up.
