### ISSUE TITLE
Icons missing on Kubuntu 21.04, git-cola version 3.9

### ISSUE THREAD

**Issue by prof7bit** [git-cola/git-cola#1159]
There is a 7 year old bug that was closed. This problem now exists on the latest version of Kubuntu. Please provide guidance how to debug this or what information I should provide.

**Comment by davvid** [comment]
@lah7 recently revamped the toolbar icons to better integrate with KDE desktops and others. Are you still seeing this issue in the latest git version? We try to use the theme/desktop-provided icons in more situations now.

And just to verify -- you have `libqt5svg5` installed? I want to believe you do, because otherwise python3-pyqt5.qtsvg shouldn't be able to be installed, but just checking in case.

**Comment by davvid** [comment]
I believe this is the root cause: https://bugs.kde.org/show_bug.cgi?id=434451

This is according to: https://aur.archlinux.org/packages/git-cola/ (see the discussion thread)

I believe this can be closed now. Please let me know if you're seeing otherwise.
