### ISSUE TITLE
External editor doesn't open

### ISSUE THREAD

**Issue by Elijahh177** [git-cola/git-cola#1175]
When trying to launch the default git editor (VS Code in this case) through git-cola, the following error message appears:

```
Cannot exec "code --wait": please configure your editor
Traceback (most recent call last):

  File "C:\Program Files\git-cola\pkgs\cola\cmds.py", line 1418, in do
    core.fork(utils.shell_split(editor) + opts)

  File "C:\Program Files\git-cola\pkgs\cola\core.py", line 305, in _fork_win32
    argv, cwd=cwd, creationflags=DETACHED_PROCESS, shell=shell

  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 800, in __init__

  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\subprocess.py", line 1207, in _execute_child

OSError: [WinError 193] %1 ist keine zulässige Win32-Anwendung
```
The same error appears with Notepad++.

In contrast, the editor launches correctly when using the git CLI.

Is this a bug or am I doing something wrong?

**Comment by davvid** [comment]
Hmm.. I wonder if it'll work better if you configure it to have an absolute path to the "code" command?

That's surprising that it launches correctly via Git's CLI. For reference, the output of:

    git config gui.editor

That reports `code --wait`, correct? Or do you have it configured through the `$EDITOR` environment variable?

    git config core.editor
    echo $EDITOR
    echo $VISUAL

Those are all the possible places we look.

Is it possible that your shell environment has `$PATH` configured to include `code`, but the environment that cola runs in does not? If that's the case then using an absolute path should fix it.

You may need to use a quoted value, eg.

    "C:/Program Files/VSCode/code.exe" --wait

when entering the value through the cola preferences.


I don't have a Windows environment for testing so apologies in advance since I'm half guessing at possible causes.

Once we figure it out this issue won't get closed until we add a Windows blurb to [the documentation](https://git-cola.readthedocs.io/en/latest/git-cola.html#configure-your-editor) that better explains how to set things up for a common Windows VSCode setup.

Thanks for the heads-up. Let's see what we can do to make this better for new users.

**Comment by Elijahh177** [comment]
Hey davvid,

thanks for your detailed answer. I appreciate your effort!

With your help I was able to figure out the issue. I set the editor in the "Preferences" page of git-cola, which in turn calls `git config gui.editor`.
I checked the path variable for VSCode. The following path was created automatically from installing VSCode:
`C:\Program Files\Microsoft VS Code\bin`
This seems to be the right path for linux operating systems.

In turn, the actual "code.exe" for windows is located in:
`C:\Program Files\Microsoft VS Code`
Adding this to the path and setting `git config gui.editor` to "code.exe --wait" fixes the problem.
