### ISSUE TITLE
Ubuntu python Qt import fail

### ISSUE THREAD

**Issue by arnstein99** [git-cola/git-cola#1180]
I am not able to launch git-cola on Ubuntu 20.04. That program complains about an undefined symbol. The problem comes from this line of code in git-cola:
`    from PyQt5.QtWidgets import *`

I isolated that problem as follows, for simplicity:
```
$ python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.QtWidgets import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib/python3/dist-packages/PyQt5/QtWidgets.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZTI13QOpenGLWidget, version Qt_5
```

What should I do to resolve the undefined symbol? I installed git-cola from Ubuntu repo:
`$sudo apt-get install git-cola`

**Comment by davvid** [comment]
Hello, is this still an issue? I think ubuntu should have fixed their PyQt installation by now.

If you're still having issues running the ubuntu-provided version then I would recommend following the instructions in the README for running from a virtualenv.

If you can't import PyQt5 then that's not really a cola problem. We're just the canary in the coal mine. Sorry 'bout that.

If you have any news since then it might help other users out in the future in case this was a transient problem. Thanks!
