### ISSUE TITLE
French translation trouble

### ISSUE THREAD

**Issue by Hierosme** [git-cola/git-cola#1181]
The tools git-cola have been translate on the worng way.

I'm French, i use Git everyday for more of 10 years now. And when i have try git-cola it was a surprise.

The translation make the tools totaly unusable, that a literal translation and not follow Git flow.
It have no option to force the tools to back in english, then the tools is simply not usable.
I have to export LANG=en before start the tool.

It look like the translation have been done by someone who don't really know what is Git and unfortunally it have a huge impact for French pepoles.

By exemple:
**CheckOut** is translate "Capturé" it mean "Grab", unfortunally all the software have been translate like that.

For my point Git command haven't to be translate at all

**Comment by davvid** [comment]
Thanks for the report. In this case, removing the translation might be the right thing to do.

Do you think that's the best option?

**Comment by Hierosme** [comment]
i don't know if that the best option to remove the entire translation.
Actually my workarround is to export LANG=en.

At first i have think about for the language from the GUI, but it have no option about language, then i have repport for the trouble.

I can take a look, if need, where is the translation files ?


Regards

**Comment by davvid** [comment]
Yes, unfortunately implementation details make it so that the language is baked in very early during app startup and it's not something that we expect to override/change so we don't have any config settings for it.

We do document how to change the language in a persistent way that doesn't involve exporting the environment variable. The environment setting is less desirable in general since it affects other programs besides cola.

https://git-cola.readthedocs.io/en/latest/git-cola.html#language-settings

I'd very much appreciate help with the translations. To test them, run `make i18n` and `python3 ./bin/git-cola` to test out the changes.

The source files are in the `po/` directory.

**Comment by davvid** [comment]
Heads-up: the process to update the translations has changed. The translations are in the `cola/i18n/fr.po` flie and they can be edited in-place without having to run any build steps.

**Comment by hierosme-nova** [comment]
Haaa good News

**Comment by davvid** [comment]
The translations you mentioned were improved, as well as some around stashing. Please submit a pull request or share more examples of translations you think we should improve.
