### ISSUE TITLE
Crash opening a project stored on a WSL2 filesystem (Windows 11)

### ISSUE THREAD

**Issue by lah7** [git-cola/git-cola#1194]
For work, I'm using Git-Cola 3.12.0 on Windows 11 to access Git repositories stored on a WSL2 file system (the latest version at time of writing: `wsl --update`). Upon opening the repository, a white, blank `pythonw` window appears before crashing:

```
Traceback (most recent call last):
  File "C:\Users\Luke\AppData\Local\Programs\git-cola\pkgs\cola\fsmonitor.py", line 447, in run
    self._worktree_watch = _Win32Watch(self._worktree, self._FLAGS)
  File "C:\Users\Luke\AppData\Local\Programs\git-cola\pkgs\cola\fsmonitor.py", line 377, in __init__
    None,
pywintypes.error: (3, 'CreateFileW', 'The system cannot find the path specified.')
```

The repositories are being accessed via this path: `//wsl.localhost/Ubuntu/home/user/Repos/test`. It also crashes when mapped as a network drive. However, local paths (`C:\...`) and a normal SMB network drive works fine.

I did notice that the file list didn't refresh automatically while browsing the WSL file system in Windows Explorer, so it's possible the protocol doesn't support file system watchers.

The workaround is to turn off inotify in `.gitconfig`:
```
[cola]
    inotify = false
```

**Comment by davvid** [comment]
This seems to be a limitation of Window's filesystem watcher APIs and/or WSL. Kindly report this issue to the WSL team so that they can improve interactions between WSL and the core Win32 APIs.

Newer versions of Git Cola won't be helpful to them since we're now working around/catching the errors and avoiding them. This should make it so that you can keep the `cola.inotify` setting enabled without running into this issue. Please test the current version from git if you can to verify the fix.

For reference, 49c13295d320d630ad349b56fa2166cc6cbc6e1e is the last commit where this issue between Windows and WSL2 filesystems can be reproduced.

Thanks for the heads-up.
