### ISSUE TITLE
MAC m1 Fail copy to Applications

### ISSUE THREAD

**Issue by shay-te** [git-cola/git-cola#1197]
Hi all. 
on a fresh Mac following this (instruction)[https://github.com/git-cola/git-cola#mac-os-x]
the `cp -r git-cola.app /Applications` command fails with the following error 

```shell 
cp: git-cola.app/Contents/Resources/share/icons/hicolor/scalable/apps/git-cola.svg: No such file or directory
```

Thank you

**Comment by davvid** [comment]
Thanks for the heads-up. The instructions have been updated and hopefully the installation procedure is simpler now.

**Comment by davvid** [comment]
We no longer specify how to copy stuff over into `/Applications` but I figured I should share that here in case you're curious. I suspect the old steps possibly created a stale symlink that was making `cp` upset. We no longer do that so it shouldn't be an issue anymore.

That said, I would recommend using `rsync` over `cp` in general since it'll handle symlinks and all that jazz.

```
rsync -avrP ./git-cola.app/ /Applications/git-cola.app/
```

You'll want to pull down the latest, clear out the old one and rebuild:

```
rm -rf git-cola.app
make git-cola.app
```
