### ISSUE TITLE
Cannot remove old folders from git-cola main window

### ISSUE THREAD

**Issue by zauberparacelsus** [git-cola/git-cola#1199]
When opening git-cola, you are presented with a selection of folders you have previously opened in git-cola.  There does not appear to be a way to remove these from within the GUI.

**Comment by davvid** [comment]
In the main UI in the `View` menu there are `Favorites` and `Recent` repository widgets. You can remove entries using those widgets (right-click context menu). There's even an action that will prune missing entries.

I think it would be a good sug to make this feature available as a right-click context menu in the initial folder selection window as well so that it's easier to discover.

**Comment by turingnixstyx** [comment]
Hi @davvid I am a new programmer, but I believe I can take this up

**Comment by davvid** [comment]
Thanks @turingnixstyx  -- this functionality does exist from the main UI, but there is currently no way to remove items from the initial `git cola --prompt` dialog.

Adding a context menu action to that dialog which allows us to prune and remove entries from the list directly would be really nice enhancement, thanks for reaching out. Let me know if you have any questions about how things work.

I'd suggest `cola/widgets/bookmarks.py` as a good place to start reading. That's the "Favorites" and "Recent" widgets and it contains code that removes entries from the bookmarks (aka "favorites") and recent repos lists. See `def delete_bookmarks(self)` for the code that removes stuff from these lists.

The initial dialog's list of repos comes from these sources -- the bookmarks (favorites) and recent repos. Running the `cmds.RemoveBookmark` or `cmds.RemoveRecent` command objects is what handles removing items from these sources.

**Comment by kevin-pease** [comment]
Hi, I was wondering if someone's still looking into this issue, as I'm looking for a beginner friendly way to dive into a nice open source project! :)

**Comment by kenrap** [comment]
I'm working on this issue and I got a question:

Regarding the bookmark widgets in the "Folder" tab from the `StartupDialog` window when using `--prompt`, they don't seem to be using the `BookmarksWidget` class from `cola/widgets/bookmarks.py`. When opening from a selected index, those bookmarks are of type `PyQt5.QtCore.QModelIndex`.

Knowing this, I'm not sure if the startup dialog indexes need to be replaced with `BookmarksWidget` instances? Since I'm new to using PyQt5 (and Qt5 in general), I don't know how to connect `QModelIndex` instances with mouse click events.

So I would appreciate any guidance here.

(In addition, since I like to refactor, I'm noticing places that could be simplified as I'm navigating around the codebase. At least to help me find bugs more efficiently.)

**Comment by JitongZ** [comment]
Hi, @davvid Seems like there aren't any updates for a long time. Can I work on this issue?

**Comment by davvid** [comment]
Yes, please. I'd be more than happy to help you out if you have any questions.

**Comment by amanakhtar78** [comment]
Hay there, I am new to open source, can you please mentor me and assign me some new basic issue which I can solve and give back to this open source community.

**Comment by nakanoi** [comment]
Hi, Happy new year!
I add context menu in dialog in PR #1280. If you don't mind, I would be very happy if you check it out!
