### ISSUE TITLE
[bug]squash do not work properly.

### ISSUE THREAD

**Issue by xiaoyifang** [git-cola/git-cola#1217]
If I have multi commits ,such as 
```
000004   commit D
000003   commit C
000002   commit B
000001   commit A
000000   base

```
`
git cola rebase 000000
`
and squash all the other commits into commit A

in the commit dialog ,only leave commitA message ,and delete all the other message.

after squash ,the result commit A 's message will become 

```
commit A

commit A
commit B
commit C
commit D
```

what's expected result is 

```
commit A 
```
only.

**Comment by davvid** [comment]
Thanks for the report. We already support this feature 👍 

In the rebase dialog use `j` to navigate down to commit `B`.

 instead of hitting `s` for `squash`, hit `f` for `fixup` on commits B, C and D.

`f` selects the `fixup` action.

The keyboard actions to accomplish what you described above would be `jfjfjf` and then `ctrl-enter` to save and run.

That'll do exactly what you're requesting. These are referred to as `fixup` commits, because we do not care about their commit messages.

If you choose `squash` then the commit messages are included so that you can *squash* them together.
