### ISSUE TITLE
Message box is invisible

### ISSUE THREAD

**Issue by hydrargyrum** [git-cola/git-cola#1228]
- **What I'm doing:** I'm trying to stage unmerged files
- **What I had:** I used to have a confirmation dialog querying me if I really wanted to stage conflict markers.
- **What I have now:** there's no dialog, the main git-cola window loses focus and no keys except enter/escape work. When I press them, the main window gains focus back and I can interact with it, but nothing was staged and I did not have the confirmation dialog

After some investigation, I found out my config file `~/.config/git-cola/settings` contained that:

```json
        "messagebox": {
            "geometry": "AdnQywADAAAAAAAAAAAAHwAAgAQAAAEvAAAAAwAAADgAAIABAAABLAAAAAAAAAAAB4AAAAADAAAAOAAAgAEAAAEs",
            "width": 32767,
            "height": 245,
            "x": 0,
            "y": 31
        },
```

I don't know what generated that impossible width and corrupted the config, but this bug hit me on 2 different machines (which don't share config files), so I would tend to think git-cola itself generated that values.

It seems the consequence of the bug is that the confirmation dialog is not shown at all though it takes the focus. At least a check could clamp impossible window geometry to the desktop size so the dialog is shown.

**Comment by davvid** [comment]
Thanks for the heads-up. We query Qt for these sizes so I wonder if there's a bug in QMessageBox (that code has been stable for a long time).

Good idea to clamp things, though. I'll keep this open so we can do that. We should also add in some defensive checks when querying for the values so that we don't ever record something like 32767 (interestingly that's 32768-1).

**Comment by hydrargyrum** [comment]
Cool thanks!
