### ISSUE TITLE
Git-cola causing high power usage in WSL+Ubuntu 20

### ISSUE THREAD

**Issue by Tyler799** [git-cola/git-cola#1229]
I've recently been trying to use git-cola under WSL running Ubuntu 20.04.

On launch it appears fine, but after doing some simple operations (looking at file diffs, for example), Windows reports its power usage as "VERY HIGH" and my fans begin to spin up and will run at full blast until I close it. (Windows labels it as "Python 3.8") 

On my modern 6C/12T machine, it was using around 12% of the CPU just on git-cola. Nothing else I'm running even comes close.

**Comment by davvid** [comment]
How does the power usage compare to these two options?

* Native Linux
* The Native Windows Python installer

We use subprocess since we do things the unix way to keep things isolated and simple. The WSL layer might be going through a lot of layers that makes things not great for that use case.

I'm about to release a new version and that'll include a fixed WIndows installer which you can use directly instead of going through the abstration layers. I hope that helps.

**Comment by Tyler799** [comment]
I cannot test a native linux install, nor anything in a traditional virtual machine. I only have access to it via either MSYS2, WSL, or natively under Windows.

I swapped from the Windows install because it was quite slow, and I assumed that issue was windows-specific.

Might have been worth keeping the issue open until that new version is actually out and tested. In any case, I look forward to testing it when it does release.
