### ISSUE TITLE
App version broken in macOS Monterrey

### ISSUE THREAD

**Issue by darksylinc** [git-cola/git-cola#1239]
# What works

1. `./git-cola.app/Contents/MacOS/git-cola` from Terminal (Terminal has `Full Disk Access`)
2. git-cola (from Terminal, installed by brew, Terminal has `Full Disk Access`)

# What doesn't work

1. `open git-cola.app`
2. Double clicking `git-cola.app` from within Finder or Launchpad

# What happens

The GUI to select which repository opens fine. But after trying to open a repository, the app will just close with no feedback (likely a crash)

# Diagnostic

It appears to be a permission problem:

![A](https://user-images.githubusercontent.com/3395130/174401650-99c5d9a9-cbe9-4275-8f70-1d4669ecbf5f.png)

All those `System Policy: ... deny ... file-read-data` appear right after I double click the repository to open in git-cola and crashes `/Users/matias/Documents/git-cola` is the repository I'm trying to open.

Adding `git-cola.app` and `/usr/bin/git` to `Full Disk Access` doesn't fix it:

![Untitled](https://user-images.githubusercontent.com/3395130/174401757-86d6e784-d63d-4fa5-aa74-d7974084ca0e.jpg)

**Comment by davvid** [comment]
Did you build it using `make git-cola.app`?

I pushed in a couple of commits that may or may not help. The `Makefile` was updated so that `git-cola.app` is made to be fully insulated within the app bundle. Previously, it relied on symlinks to the python installation.

Furthermore, I updated the `Info.plist` file to request permissions.

The downside is that I'm unable to reproduce these errors even though I'm also on Monterrey, so I have no idea if these changes make any difference.

There's a bunch of app notarization stuff in newer versions of macOS that make some of this stuff more challenging. Hopefully we can still keep the app bundle as an option for some users, but I'll need some help figuring out what's going on.

**Comment by dxkrs** [comment]
I install the git-cola step by step on my macos 12.6
```
cd ~
brew update
brew install git-cola
```
then I run 
```
make git-cola.app
```
it show the error :
```
make: *** No rule to make target `git-cola'.  Stop.
```
`Application` fold haven't the app, enter the command `git-cola` can open the git-cola gui which only have a "Python" on the top left menu.

What wrong?

**Comment by davvid** [comment]
You have to be inside a clone of the git-cola repository when running `make git-cola.app`.

**Comment by davvid** [comment]
For reference, this step moved you back to your $HOME directory:

```
cd ~
```

If you cloned cola to a directory called `git-cola` in your current directory then you would need to use `cd git-cola` after cloning it to enter that directory.
