### ISSUE TITLE
.config/git-cola/language setting no longer working

### ISSUE THREAD

**Issue by nieroster** [git-cola/git-cola#1246]
In previous versions we could set the language of git-cola to be different from the operating system language using the language file in .config/git-cola 
For some reason this is ignored in the current version 4.0.1. The last version it was working with is 3.12.

OS: Win10
OS Language: German
desired git-cola language: English
.config/git-cola/language  content: en_US.UTF-8

How can I start git-cola in English again?

**Comment by nieroster** [comment]
For now I've renamed git-cola\pkgs\cola\i18n\de.po to get it working again

But it would be nice to get this fixed, or updating the doc it the mechanism has changed due to the new build system.

**Comment by davvid** [comment]
Thanks for the report.

Can you run in a command shell and check what it resolves to in your environment?

```
"C:\Program Files\git-cola\Python\python.exe" -c "import os; print(os.path.expanduser('~'))"
```

That'll print out the home directory where it expects to find the `.config` directory.

The main thing that's changed in this area lately is that we've changed python versions, so maybe Python is resolving `~` to a different value these days?

In the past I have observed the need to have the file in a `_config/git-cola/` directory (note the leading `_` underscore) instead of `.config`, but that would be something in the Python/Windows layer that's outside of our control.

In the code we are constructing a path to `~/.config/git-cola` and looking for the `lang` file in there.

For reference, [here is where we calculate the .config/git-cola directory](https://github.com/git-cola/git-cola/blob/main/cola/resources.py#L131).

[Here is where create the path](https://github.com/git-cola/git-cola/blob/main/cola/i18n.py#L119) to the `language` file.

I hope that helps. We also support the `$XDG_CONFIG_HOME` environment variable to configure the location of the `.config` top-level directory.

Let me know what you find. Maybe there's an environment variable we should be consulting on Windows?
