### ISSUE TITLE
opening issue (Kali 2022.2 the latest  )

### ISSUE THREAD

**Issue by c4ir0** [git-cola/git-cola#1248]
**command to install** --> ` sudo apt install git-cola`
 and it should be installed but .....
![Capture](https://user-images.githubusercontent.com/108268587/180773273-304719a9-43d9-40d0-b7c5-b7c29fd84ad1.PNG)

I have already read some issues reported but nothing led to solution, I hope u can help

**Comment by davvid** [comment]
Kindly file a bug with the kali folks, this seems to be a mismatch between pyqt5 and sip. That's a build error and you shouldn't ever see that under normal circumstances.

Cola is just the canary here -- all pyqt5 apps are affected by that issue.

You don't have a different sip module in `~/.local/lib/python3*/site-packages`, right?

My sug would be to try upgrading your `python3-sip` and all of the `python3-pyqt5*` packages.

Installing cola into a virtualenv is also an option if the distro-provided packages aren't working out for you. But, whatever you do, please don't ever run `pip install` outside of a virtualenv or as root as it can do bad things to your pristine apt-managed system. Even running it as your user will install into your $HOME directory by default (typically under `~/.local/lib/python3*/site-packages`) and modules installed there could later conflict with the distro-provided ones.

So usually I try to avoid installing anything user-wide and keep things insulated inside virtualenvs. And since you're on an apt-based system, the distro packages for python-pyqt5 and python3-sip should be preferred.

This page lists the kali pyqt5 packages in the "Binaries" list:

https://pkg.kali.org/pkg/pyqt5

It might be that a new build was recently uploaded so upgrading now might get you better results. You don't need to change cola versions -- these errors are from the pyqt5 part of the stack.

I'm going to close this issue because there's not much we can do about it, but please share details (or links to a kali bug for this issue) if you report an issue or find a solution since it might be able to help someone else down the line. Thanks for the heads-up.
