### ISSUE TITLE
Problems with git-cola 4.0.3

### ISSUE THREAD

**Issue by NielBuys** [git-cola/git-cola#1264]
I am running git-cola from source on Ubuntu 20.04. I did a git pull for the newest version of git-cola.

I had the following problems stopping me to use git-cola.
1. I couldn't git fetch or pull I press on the fetch or pull button and on the screen opening I press the fetch or pull button then nothing happens.
2. History browser did not open it keeps telling me gitk is not installed. I always used git-dag for my history browser. If I open my .gitconfig in my home directory it says git-dag is my history browser.
3. If I go to the preferences screen to change gitk to git-dag. The change is not saved. If I close the preferences window and open it again then it says gitk again. And history browser is still not working.

In the git-cola folder I reset my local git-cola branch to v4.0.2 then everything started to work.

**Comment by davvid** [comment]
Thanks for the heads-up. The latest in git (unreleased) has a rewrite of the config reader. I'm going to assume this is related to those changes.

Can you please share the output from these commands when run inside the repo in question?

```
git version
git config --show-origin --show-scope --includes --list
```

A few possibilities -- does your git support the `--show-origin` and `--show-scope` options? Apologies if this is the root cause since it means that we're now depending on a newer git.

If Ubuntu 20.04 does not support those options then I may consider having a fallback implementation that uses the older (original) approach when it detects an older git version.

**Comment by davvid** [comment]
2c77ba5f647dce1752cb5c6c65c8cd797b6cf86b is the commit that changed the config reader.

**Comment by davvid** [comment]
In case it helps, it looks like there's a PPA for Ubuntu 20 that gets you a newer git version. That might be preferable if `git` is the root cause.

https://www.linuxcapable.com/how-to-install-and-update-latest-git-on-ubuntu-20-04/#Install_Custom_PPA_GIT-COREPPA

**Comment by davvid** [comment]
https://launchpad.net/~git-core/+archive/ubuntu/ppa is the PPA.

Please let me know if this resolves the issue for you and if so I'll add a note to the documentation about it. If the issue persists after upgrading git then I'll consider the back-compat approach.

**Comment by davvid** [comment]
`git config --show-origin` was introduced in git 2.8.0 (2016) so I'm pretty sure you have that version already.

`git config --show-scope` was introduced in 2.26.0 (2020) so that option is probably the one that's unavailable.

I'm leaning towards adding support for git versions that do not support `git config --show-scope` since that'll also enable a few other distros that do not yet have 2.26.0 available.

**Comment by NielBuys** [comment]
Ok I have run the above commands looks like I don't have the "show-scope" function. Let me know if you plan to change git-cola with support for versions that do not support show-scope. Then I will wait for that to test if it works. If not then I will see to it to load newest Git on my system.
![image](https://user-images.githubusercontent.com/8427483/195783050-7b4d8a80-8292-4c52-800c-50c35d4aecf6.png)
![image](https://user-images.githubusercontent.com/8427483/195783160-4d58c42f-b864-4008-ab75-28330a591d86.png)

Thanks for your reply

**Comment by davvid** [comment]
Thanks again for the heads-up, Niel. I just added a Git v2.8.0-compatible implementation. Please test it out and let me know if it's working for you too.

**Comment by NielBuys** [comment]
Thanks for the fix and a great product. Git Cola works now with the newest pull.
