### ISSUE TITLE
[Bug] Deleted remote branch still listed

### ISSUE THREAD

**Issue by FlachyJoe** [git-cola/git-cola#1266]
Hi,

0. Using Git-cola 4.0.2
1. Create a local branch
2. Push it to a new remote one
3. Delete the remote by CLI or web interface
4. Git-col still show the remote branch and I can't find how to remove it from the tree

**Comment by davvid** [comment]
The reason we display the remote-tracking branch is because the local pointer still exists.

Git is a pack rat and it tries very hard to make sure that you don't lose any data.

If you want the stale tracking branches to be removed then you can do these steps:

* Open the "Fetch" dialog (Actions -> Fetch)
* Click on the "Prune" checkbox
* Click on "Fetch" to fetch refs from the selected remote (typically "origin").

The "Prune" checkbox will make cola use the `--prune` option when running `git fetch`. This causes the stale branches from "origin" to be removed.
