### ISSUE TITLE
make install prefix forces a new local folder

### ISSUE THREAD

**Issue by brccabral** [git-cola/git-cola#1272]
Hi,
Running `make prefix=~/myfolder install` creates a new folder `~/myfolder/local`.
The same if using DESTDIR `make DESTDIR=~/myfolder prefix= install`.
Is it possible to not create the new `local` folder?

**Comment by davvid** [comment]
For python it's very strongly recommend to always work in the context of a virtualenv. It's usually not a good idea in general to do `sudo make prefix=/usr install`, or `sudo xxx ...`.

The README.md has this note:

> **IMPORTANT**: never run `pip install` as root or outside of a Python virtualenv!

I should mention `make install` in there too.

There's an old unix mantra ~ "don't do stuff as root" ~ but that behavior difference when run under sudo is an interesting observation. FWIW, our requirements are minimal so things are probably fine.

Python does have some sharp corners. I just want to echo the caution that pip displays:

> WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv


I have a hunch that what's happening in that first `make prefix=$HOME/.local install` is that `pip` is perhaps trying to uninstall / remove an existing `git-cola` installation in `/usr/local`.

Can you confirm whether or not that was the state of  your machine before running the final install -- did you have a copy in /usr/local/bin/git-cola that pip would have detected?

That error message is basically pip thinking it needs to write into /usr/local.

So when you run `make prefix=$HOME/.local install` as a regular user, pip tries to "helpfully" delete some other cola installation that it's detecting? That's unfortunate. pip is wild.. I'm going to have another look to see if there's perhaps a way to get pip to not try to uninstall pre-existing installs.

That said.. I don't have my hopes up. That might just be how pip works, unfortunately, but it would be a bummer since in this scenario we're clearly not installing into the same location.

If my hunch is correct then I suspect that removing the copy from `/usr/local` completely, including all of the cola/ python modules and git_cola-*.dist-info/ directories under /usr/local/lib/python3.*/site-packages, will fix being able to `make prefix=$HOME/.local`.

For reference, here's my workflow if I want to run on a machine that doesn't have pyqt pre-installed.

```
python3 -m venv env3
vx env3 make requirements requirements-optional
vx env3 bin/git-cola
```

This installs the dev requirements and runs the test suite

```
vx env3 make requirements-dev
vx env3 make test
```

[1] https://github.com/davvid/vx

Since you want to install into ~/.local, the simplest option might be to symlink the `bin/git-cola` script into that location. The repo is totally designed to be run in-place.

```
mkdir -p ~/.local/bin
ln -s $PWD/bin/git-cola ~/.local/bin/git-cola
```

The nice thing about that setup is that you can `git pull` to get the latest version and you don't have to reinstall anything.

I also suspect that the virtualenv should work since python and pip will then be dealing with the virtualenv instead of going out into /usr/local to do stuff. So in theory this should work without having to run under sudo as well.

In that case, this is how you can install with the sandboxed pip:

```
vx env3 make install prefix=$HOME/.local
```

Let me know if either of these approaches work out, and whether there's a pre-existing install somewhere under /usr that pip was finding.
