### ISSUE TITLE
SSH keys password requested even when SSH agent running/working

### ISSUE THREAD

**Issue by nekromoff** [git-cola/git-cola#1275]
Cola 3.12.0 always requests known SSH key password, while SSH user agent running in the background
Linux / Ubuntu

**Comment by davvid** [comment]
What happens when you `git push` or `git pull` from the command-line? Does it prompt for a password as well?

Cola runs the git command-line tool on your behalf so it should always be possible to reproduce these issues using plain `git push`.

If you're launching Cola from a desktop launcher then one explanation might be that the desktop environment doesn't have the ssh agent environment variables that you might have defined in your shell.

How are you launching it? Does it behave better if you launch cola from a shell where `git push` is known to work without prompting?

**Comment by nekromoff** [comment]
You can close this, it's not happening anymore. It must have been some glitch.
