### ISSUE TITLE
qt5ct theme

### ISSUE THREAD

**Issue by brccabral** [git-cola/git-cola#1283]
Hi,
It is not git-cola's fault, but I just noticed that if we install PyQt5 in a venv it is missing qt5ct libraries and a custom theme is not loaded.
After I copied the libraries from my system (Ubuntu) into the venv the custom theme loads.

from /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqt5ct.so to $HOME/venv/lib/python3.10/site-packages/PyQt5/Qt5/plugins/platformthemes/libqt5ct.so
from /usr/lib/x86_64-linux-gnu/qt5/plugins/styles/libqt5ct-style.so to $HOME/venv/lib/python3.10/site-packages/PyQt5/Qt5/plugins/styles/libqt5ct-style.so

**Comment by davvid** [comment]
Yeah, that's more or less how to deal with it.

eg. https://stackoverflow.com/questions/58675935/having-issues-getting-pyqt5-venv-qt5ct-to-play-nicely reached the same basic conclusion.

Users on Linux are usually better off using the system's PyQt5 package. The simplest way to do that is to rebuild the venv using `python3 -m venv --system-site-packages venv` so that the distro-provded PyQt5 packages are available inside of the virtualenv.

Another experiment you can try instead of `--system-site-packages` is to use the `QT_PLUGIN_PATH` environment variable to get the venv's PyQt5 to load system-provided plugins. I'll explain how to do that, but heads-up that it's kinda dodgy. It's slightly dodgier than copying libs into the venv in the long term, but basically equivalent to that approach in the moment.

It's only "slightly dodgier" because a system upgrade can theoretically break it at any time, whereas copying the libs into the venv like you've done will be slightly more resilient.

To try that, `export QT_PLUGIN_PATH=${HOME}/venv/lib/python3.10/site-packages/PyQt5/Qt5/plugins/:/usr/lib/x86_64-linux-gnu/qt5/plugins` in your environment. That should allow the venv-provided PyQt5 to load the system-provided plugins from /usr/lib without having to copy stuff into it.

This is kinda risky, though. A caveat with mixing a venv-provided PyQt5 with a distro-provided Qt5 is that the venv-provided PyQt5 must be binary-compatible with the system-provided Qt5 version. This usually means pinning the venv's PyQt5 version to match the system version.

All that considered, I think `--system-site-packages` is probably the right way to go here. Thanks for the heads-up. I've updated the readme to mention `--system-site-packages` for now.
