### ISSUE TITLE
ssh-askpass shebang line hard-codes location of tclsh

### ISSUE THREAD

**Issue by tbpassin** [git-cola/git-cola#1285]
The shebang line assumes a location for tclsh:

`#!/usr/bin/env tclsh`

However, not all Linux distros put it there.  If it is not there, a commit cannot be pushed to the remote.  For example, on my Debian Buster virtual machine, it is at `/usr/bin/tclsh` and the `/usr/bin/env` does not even exist.

The user could create the directory and put a symbolic link there, but it seems unreasonable to expect that.

**Comment by davvid** [comment]
I'm on debian and `/usr/bin/env` is provided by `coreutils`. Do you not have coreutils installed? Where is `env` on your system?

I'm kinda  confused because `#!/usr/bin/env tclsh` is the typical way to write a script that'll pickup whatever `tclsh` is in your $PATH.

If, for example. we had `#!/usr/bin/tclsh` hard-coded then this issue seems like it would be a little more relevant, but we don't. We use that `env` technique specifically for the purpose of allowing the path to be dynamic.

I'll close this issue for now, but please let me know if I'm misunderstanding something, or kindly open a PR.

**Comment by tbpassin** [comment]
Now I see my mistake.  I assumed that /usr/bin/env was a directory (which I don't have), but now I see it's an executable file and it's present.  I apologize for confusing people!
