### ISSUE TITLE
(Feature request): Toggleable +/- in diff?

### ISSUE THREAD

**Issue by birgersp** [git-cola/git-cola#1288]
Hello,

I often find myself copying some snippets of code from the diff view.

E.g. I needed some parts of a deleted (but not yet staged) file to put in a different file. When I highlight the text in the diff view and copy it, I also get the leading +/- symbols for each line (naturally).

E.g. imagine I select these two lines:

![image](https://user-images.githubusercontent.com/5260237/217829575-0cf01aec-301c-462c-8079-11e0b792df04.png)

What I get into my clipboard is literally:

```
-	const parser =
+	const parser =
```

What I actually want is
```
	const parser =
	const parser =
```

In some diff views the +/- symbols are actually not selectable (render on the side?). For instance, the diff view in DevOps:

![image](https://user-images.githubusercontent.com/5260237/217829885-30e180df-b221-4d0e-a383-28dd719e7940.png)

As demonstrated, I can select the text from the diff and all I get is the changed lines (without the leading +/- symbols).

I think it would be really great if I could select-and-copy text as easy in Git Cola, as I can in DevOps.

So what I am proposing is that the leading +/- is not selectable.

**Comment by davvid** [comment]
This would be super useful! I find myself wanting to do the same thing from the diff view.

I'm going to look into adding a "Copy Diff" action that implements a custom copy behavior. It'll basically copy the text while stripping off the leading `+/-/<space>` characters.

Part of me wants to hijack the core "Copy" action and make it handle this automatically, but then we'd also need a separate "Copy Raw" action for cases where we do want to copy directly from it. That's why I'm thinking that having a dedicated "Copy Diff" action is probably the way to go.

I'll try to assign a hotkey (ctrl-shift-c) to it too so that it's easy and convenient to use.

We already have a lot of new features in the upcoming v4.2.0 release but this one seems worth adding as part of the upcoming release.

**Comment by birgersp** [comment]
> This would be super useful! I find myself wanting to do the same thing from the diff view.
> 
> I'm going to look into adding a "Copy Diff" action that implements a custom copy behavior. It'll basically copy the text while stripping off the leading `+/-/<space>` characters.

That sounds like a great solution! Someone might want to copy the diff **with** the +/- included and the default copy behaviour should probably remain.

**Comment by davvid** [comment]
We already have `Ctrl + Shift + C` for cherry-pick so this was added with an `Alt  + Shift + C` hotkey instead.

Thanks for the sug!
