### ISSUE TITLE
Clipboard is cleared when creating a new branch

### ISSUE THREAD

**Issue by jakubklos77** [git-cola/git-cola#1295]
In the latest "main" branch there is an odd behavior:

- Copy some string to the clipboard (outside of git-cola)
- Branch / Create...
- Try to paste the string from clipboard, nothing happens, the clipboard is cleared

Testing on Ubuntu 22.04

**Comment by davvid** [comment]
We don't have any clipboard interaction in that dialog so this is super surprising. 

Have you tested the latest from git? There's a key difference in the unreleased version that might help.

I was not able to reproduce this issue on my desktop running debian/testing.

I was not able to reproduce this issue on macos either.

I was not able to reproduce this in an ubuntu20 VM either.

I only tested the latest version in git.

In the latest version from git we're internally setting `QT_QPA_PLATFORM=wayland` when we detect that you're on wayland, which I believe is the case for ubuntu20.

If you're only seeing this problem in the latest version (and not in a tagged version) then I'd be curious to know whether you see it when launching as:

    env QT_QPA_PLATFORM=qcb ./bin/git-cola

The above advice is only applicable to the latest (soon to be tagged) version.

On the other hand, If you're only seeing this with the latest version in git then try testing with the command above since it can change things related to copy/paste integration.

The reason why we're setting `QT_QPA_PLATFORM=wayland` internally in the latest (unreleased) version is that it fixes drag+drop behavior on modern linux desktop environments. We only set this when we detect that we're running under wayland. This change could impact copy/paste as well, but I only observed it when testing drag+drop.

Here is the code where we manage this variable:

https://github.com/davvid/git-cola/blob/3763f2ac8acd4d5934c75d5478ed700db2514d61/cola/app.py#L147

If you haven't tried the latest version then there's a high probability that we fixed it recently when we started setting QT_QPA_PLATFORM in the code linked above.

Let me know if any of that helps.

**Comment by jakubklos77** [comment]
Hi David,
thank you for your response.

Yes, I use the latest git master branch on Wayland.

qcb does not work for me, says:
qt.qpa.plugin: Could not find the Qt platform plugin "qcb" in ""

tried: xcb instead and that works properly.
The clipboard is maintained the whole time after git-cola is run.

Good for me, I can make the required change but how shall we resolve this when the version is released officially?

Thank you again

**Comment by davvid** [comment]
Thanks for the feedback. That's really helpful. Here's my explanation for what's up.

Since you defined that variable it then prevents cola from setting `QT_QPA_PLATFORM=wayland`.

It then looks like you don't have the qt5 qcb plugin installed so then Qt will fallback to its default platform plugin after printing that warning message about xcb.

Despite the warning messages, things work when you do that so I think what cola should do is not try to manage this variable at all.

I'm going to push a commit that removes our internal handling for QT_QPA_PLATFORM. I believe that should resolve this issue in your environment.

We can then add a note to the documentation suggesting use of QT_QPA_PLATFROM=wayland on some platforms (or I can figure out a better heuristic).

That way it should be better behaved and you shouldn't need to do anything.

Please the latest version in git and let me know if it worked. I just pushed in a tweak that should help.

Please re-open this issue if it's still not working. I marked the commit with `Closes: #1295` since I believe it should have fixed it, but please let me know if you observe things otherwise.

Thanks for catching this before v4.2.0 was tagged!

**Comment by jakubklos77** [comment]
Works great for me. Thank you!
