### ISSUE TITLE
Feature Request: dual parent and submodule view

### ISSUE THREAD

**Issue by boxerab** [git-cola/git-cola#1300]
I often make changes to both a submodule and its parent - currently I need two instances of git-cola open to manage both projects. Is there a way of seeing commits for both parent and submodule from single instance ?

**Comment by davvid** [comment]
Sorry, this isn't well support by the Git model so it's not something that we're planning on supporting in cola.

The recommended workflow is to use the submodules widgets to open submodules, or to bookmark both the parent and child repos so that you can quickly jump between them using the Favorites widget. There's also the `Alt-p` hotkey that can be used for quickly jumping between Recently Opened and bookmarked repositories.

One reason why this is necessary because commits are two-phase -- you have to commit in the child repository before you can commit the new submodule commit ID into the parent repository.
