### ISSUE TITLE
Extremely slow operations

### ISSUE THREAD

**Issue by installgentoo** [git-cola/git-cola#1305]
So, seemingly starting with 4.1.0, git-cola sometimes starts freezing. On everything. Opening a repo takes a few minutes, closing preferences or reverting a commit - the same. Displays no errors in terminal.

Even more odd is that not only it finishes the operation properly, it also takes 0 cpu time while frozen. I have never seen this behaviour, it's as if it hit a race, but then something un-races it on a timeout. And sometimes it just starts and works normally.

This is on python 3.11

**Comment by installgentoo** [comment]
Same on 4.0.4. Perhaps this is caused by git? I'm using 2.40.0

**Comment by installgentoo** [comment]
Does git-cola perform sync operations somehow? I've stopped copy on an external hdd, sync'd and it's working at normal speed for now. Very peculiar

**Comment by davvid** [comment]
Once thing to look out for is whether you've run `git gc` recently. That can have a large impact on performance.

The latest version in git (v4.2.0 and newer) has performance improvements that could help as well. I'm curious to know what caused the difference. Thanks for the heads-up.

**Comment by installgentoo** [comment]
@davvid 

No matter whether i run git gc or not, this happens.

It happens specifically with slow external storage attached and actively copying a lot of files, as if git-cola calls bash command "sync" on its every operation. Even just opening an empty repo lags exactly as much as a sync operation takes. i'm on 2.42 and 4.3.1 right now. By "lags" i'm talking minutes, as syncing a large buffer to hdd would take.

This is 100% git-cola, using git in console doesn't lag at all.

You are probably, somehow, calling sync through python code.

Just faced this issue again, as i happen to be doing backups.

**Comment by davvid** [comment]
Very interesting! It's possible that some of the `git` operations we rely on use `fsync` under the hood.

Luckily `git` has configuration that allows you to control this behavior: https://git-scm.com/docs/git-config#Documentation/git-config.txt-corefsync

Can you please help us narrow down on exactly which operations are slowest?

Run `GIT_COLA_TRACE=1 ./bin/git-cola` or `GIT_COLA_TRACE=1 git cola` instead of how you normally launch `git cola` and that'll make it print a trace to stdout of the `git` commands as it runs them alongside timing information for how long the operation took.

If you can share the output then that can help us determine exactly which operation is triggering the slowness.

**Comment by installgentoo** [comment]
@davvid 

It's not the git commands, it's cola. I can run git commands just fine.

```
/ $  GIT_COLA_TRACE=1 git cola
# 0.004s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false version
# 0.004s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false config --show-origin --show-scope --list --includes
# 0.005s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false config --show-origin --show-scope --list --includes
# 0.010s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false ls-files -z --
# 0.008s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false update-index --refresh
# 0.007s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-index --cached -z HEAD --
# 0.008s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-files -z --
# 0.009s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false ls-files -z --others --exclude-standard --
# 0.009s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false rev-parse --symbolic-full-name HEAD
# 0.008s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false merge-base HEAD origin/master
# 0.008s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false diff-tree --name-only --no-commit-id -r -z 6c5427c2a8173e2e8bbbc78bed6c204fddf28ba3 origin/master
# 0.006s: git -c diff.suppressBlankEmpty=false -c log.showSignature=false for-each-ref --format=%(refname) --sort=version:refname
^[[A^[[B^[[D^[[C
```

Here, with rsync in background, opening a repo(by clicking on a repo icon in git-cola startup interface) on unrelated ssd hangs for 5 seconds. As you can see, these seconds aren't actually logged anywhere. Right now, after exiting, i have python3.11 /usr/bin/git-cola hanged, sitting at 0% cpu time. Even after stopping rsync and disconnecting the hdd i had to kill it with ctrl+c to actually finally return to terminal.

**Comment by sthalik** [comment]
Try running `strace(1)` or `truss(1)` on that Python instance. There's some operation (can even be `stat(2)` or `open(2)`) being done on the main thread that's slow on your machine when it's contended.

As a workaround you can use a different IO scheduler or `ionice(1)` the busy tasks.

**Comment by installgentoo** [comment]
in cola/core.py:484 cola defines sync(), which does literally sync, and that sync() somehow is used in almost everything cola does. i just had this issue again. removing that naturally fixes the issue.

i don't think it's up to cola to concern itself with syncing the filesystem.

**Comment by davvid** [comment]
Actually, the `core.fsync()` function is only used in a single place, which is when cola is shutting down and needs to ensure that its settings get written. That function is not used at all when cola is doing normal things.

I'll test things out a bit to make sure that's the case in reality, but at least that's how it's supposed to be working.

I believe core `git` may have some tuning knobs for syncing.

`git help config` on my system (git v2.43.0) has this section:

```
       core.fsync
           A comma-separated list of components of the repository that should be hardened via the
           core.fsyncMethod when created or modified. You can disable hardening of any component by prefixing it
           with a -. Items that are not hardened may be lost in the event of an unclean system shutdown. Unless
           you have special requirements, it is recommended that you leave this option empty or pick one of
           committed, added, or all.

           When this configuration is encountered, the set of components starts with the platform default value,
           disabled components are removed, and additional components are added.  none resets the state so that
           the platform default is ignored.

           The empty string resets the fsync configuration to the platform default. The default on most platforms
           is equivalent to core.fsync=committed,-loose-object, which has good performance, but risks losing
           recent work in the event of an unclean system shutdown.

           •   none clears the set of fsynced components.

[a bunch more trimmed for brevity]
```

Does it help at all if you run this:
```bash
git config --global core.fsync none
```
?


The `git update-index --refresh` call is pretty expensive, as are the diff-related ones, but that's the only way we can gather the status information that the UI relies on. If we don't call those them the UI will sometimes report that something is modified (when it's really not).

**Comment by installgentoo** [comment]
I believe your sync is literally invoking the OS sync. Re-read the lines.

Because i commented that sync out in python, and lags disappeared. It's not the global git config, as my git was never lagging. Something must be messed up on the cola side, it it was a git issue, someone else would've reported it for git itself.

**Comment by davvid** [comment]
@installgentoo thanks for explaining that you're seeing this behavior when closing windows / dialogs.

That's one of the only places we call sync -- when dialogs and windows are closed in order to persist settings.

The reason it's there is to avoid data loss in some scenarios (reported in #1241), which is a pretty common scenario, so I'm not sure if I should rip it this out completely. Heads-up @darksylinc

What I can do is add a config knob that you can try out @installgentoo:

```bash
git config --global cola.sync false
```

That'll prevent cola from using `os.sync()`. Unfortunately `os.sync()` is the only hammer we have. We don't have any other granularity available from python, but if you're aware of one please let me know.

I guess I could do something gnarly like grab a pointer to libc's `fsync` by using `libc = ctypes.CDLL('libc.so.6')` to load libc at runtime and then call `libc.fsync(fd)` but maybe that's going a little too far... or maybe not?

That would possibly let us eliminate this config variable. I'll take a stab at that before tagging the next release since I think that might be a better solution for linux users.

Is  hard-coding `libc.so.6` a bad idea? I guess it doesn't hurt for folks that have it, and I can fallback to calling `os.sync()` when ctypes fails. I'll give that a try in the next couple of days.

**Comment by davvid** [comment]
Also test w/out configuring anything. We're now using `fdatasync()` when it's available, so this should be better behaved by default on systems with a libc.so.6 that provides it.

**Comment by darksylinc** [comment]
Yeah.

fdatasync is a much better approach.

However it is a bit of a red flag that opening a repo can take **minutes**.

Perhaps config saving is being done excessively? Ideally file settings should only be saved if they changed, or just a few times per session (i.e. only once at shutdown + after user closes the config dialog).

Since `os.sync()` is global, it would make sense to take minutes (without being git-cola's fault) if the user performed an unrelated IO write operation that takes a long time to flush:

- Wrote a big file to an USB thumb drive (i.e. writing a 2GB file to a 5 MB/s thumb drive takes almost 7 minutes)
- Wrote a big file to a mounted shared network folder (SAMBA, NFS, SFTP)
- User is running on a Macbook M1 (M1's SSD has a known issue where HW flushing brings the NVMe down to a crawl, just 46 IOPS or so). I don't know if the problem got fixed for M2 and later models

**Comment by darksylinc** [comment]
An alternate solution would be to spawn a worker thread, and send all the data to save to that worker thread.

The worker thread consumes the data from the queue, saves to disk and flushes. If the queue has multiple entries pending when it wakes up (i.e. save_config was called multiple times in a row), then worker should skip the older entries and save the latest one.

**Comment by davvid** [comment]
Add some print() calls to `core.sync()` and you should see that we don't really call it very often -- only when dialogs are closed. It doesn't get called during the startup path.

Another thing that might be going on is running into inotify notifications when things write stuff into the repo directory. You can test that with: `git config --global cola.inotify false`

That'll avoid running commands in response to filesystem events, which can cause lots of IO. The only difference is that you'll have to periodically run `Ctrl + r` to trigger a UI refresh when files are edited w/out cola knowing about it.

The latest cola in git is using fdatasync on just the file that was written so the overhead should be much lower now. I'm curious to know whether that's made a noticeable difference in your workloads.

**Comment by installgentoo** [comment]
Why do you even sync filesystem? I have never head of an application doing that. Git itself doesn't do that.
On the line i removed it from, it's supposedly used after git-cola config is saved. Just save to a file and swap like normal people.

**Comment by darksylinc** [comment]
> Why do you even sync filesystem? I have never head of an application doing that.

That is quite normal for keeping data stored safely. Many apps resort to using sqlite for storing settings safely, which does that under the hood. `NSUserDefaults` for example does that under the hood too.

Having that I said, I was gonna suggest the same thing: The original problem was that git-cola was overriding the file in-place; which caused data loss with enough frequency that I had to report it, which stemmed from _normal_ usage (ordering the OS to shutdown, and the OS kills git-cola halfway saving data).

The solution included the following:

1. Write the file to a tmp file.
2. Perform a flush to ensure the tmp file data is actually saved.
3. Delete the current config file, rename the tmp to the final config file name.
4. On load, the app must check if the config is there. If it's missing, it should check the backup.

This theoretically covers 99.99% of cases for data loss, including power failure and OS bugs. It does not cover HW failure (e.g. corruption when writing data) since there is no CRC calculated or other integrity verification.

The reason for this flush is that most filesystems drivers don't always guarantee the rename happens after all the data has been written. But this detail is only relevant on power failure, kernel panics / BSODs and similar. It should not be relevant if the OS kills git-cola halfway while saving data.

If we remove the flush on step 2, git-cola should still cover 90% _or more_ of cases (and very likely the cases which were troubling me). It would not cover certain poorly-timed cases of power failure. But they should be so rare as to not be something git-cola should worry about (specially if users complain the flush is causing visible performance degradation).

**Comment by installgentoo** [comment]
I have literally never encountered any other application that would lag because it calls sync.
Who even came up with this flush idea? You people are aware that file systems use journaling nowadays, right? Write tmp and swap it with settings. Moving(via rename) a file is atomic.


I will tell this as anecdote about python devs swapping the bloody fs to preserve the settings going forth.

**Comment by darksylinc** [comment]
>  You people are aware that file systems use journaling nowadays, right? Write tmp and swap it with settings. Moving(via rename) a file is atomic.

Journaling guarantees the metadata is consistent, but it says nothing about the actual data. Without journaling at all you can end up with a filesystem that has corrupted entries or can't even be mounted anymore.

With Journaling we get the guarantee the file is either there or not. But what's inside is anyone's guess (unless the filesystem is ext4 and was mounted with data=journal which is very slow, and is not the default).

Whether the atomic rename happened _before or after_ the data was done writing to disk depends on various settings and conditions (eg. for ext4 it is writeback vs ordered).

Anyway, git-cola's settings may not need this level of integrity since they can be regenerated (even if annoying) by the user.
