### ISSUE TITLE
git-cola 4.2.0 no longer shows initial autocomplete for Checkout / Delete branch dialog

### ISSUE THREAD

**Issue by lah7** [git-cola/git-cola#1308]
When the "Checkout..." or "Delete..." options are chosen in 4.1.0, initial autocomplete suggestions would appear (like the names of branches & tags), with the ability for the user to type and filter it down. In 4.2.0, this is blank until the user starts typing a couple of characters.

I didn't see this change mentioned in the changelog, so I think it might be a bug.

| 4.1.0 | 4.2.0 |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/13032135/227796837-045ac717-e51c-4b20-8b07-d6af0197f67e.png) | ![image](https://user-images.githubusercontent.com/13032135/227796835-85f54ed6-752e-4974-9af1-6caa4e0473c1.png)

## Environment

git-cola 4.2.0 (from AUR + when ran from repository folder)
Arch Linux
KDE Plasma 5.27.3
Qt 5.15.8
Python 3.10.10

**Comment by davvid** [comment]
There were a number of optimizations recently that deferred loading some of this data, which has a measurable effect on huge repositories.

I think we can specialize the behavior for the branches completer since it's not used during startup. I was specifically optimizing the startup speed of `git-dag` and that one uses a different completer.

Thanks for the heads-up.

**Comment by davvid** [comment]
This should be better than the original version from before.

The first commit restored the original behavior. That behavior had an edge case where nothing would get displayed once the field was edited and cleared.

The new version now displays all of the candidates anytime the field is cleared, so the behavior should be consistent and predictable.
