### ISSUE TITLE
git-cola 4.2.1: Interactive rebase failing to start on Ubuntu 22.04

### ISSUE THREAD

**Issue by makcblmru** [git-cola/git-cola#1317]
Interactive rebase fails to start after entering target branch with the following error message:
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
Cannot mix incompatible Qt library (5.15.3) with this library (5.15.2)
error: git-cola/bin/git-cola-sequence-editor died of signal 6
error: There was a problem with the editor 'git-cola/bin/git-cola-sequence-editor'.

QT_QPA_PLATFORM=wayland is already set in my environment. Looks like PyQt5 installs Qt  5.15.2 although I have installed Qt 5.15.3

**Comment by davvid** [comment]
>  Cannot mix incompatible Qt library (5.15.3) with this library (5.15.2)

That usually means that your distro-provided Qt packages were upgraded separately from the PyQt packages in your environment.

Getting your PyQt installation fixed will resolve the issue.

On (Debian) Linux I usually stick to using the distro-provided python and PyQt packages. If I use a virtualenv for cola I don't install PyQt into the virtualenv but rather rely on `python3 -m venv --system-site-packages env3` to allow access to the distro-provided PyQt from inside the `env3` virtualenv.

If you find a resolution please share so that google can find the answer next time.

Here's a list of Python mistakes that can lead to this situation. If you ever did any of these steps then that might explain the problem you're seeing.

* Using `pip install` to install stuff.
  - `pip` will install stuff in your $HOME by default, which can conflict with distro-provided packages. You should never run `pip install` to install things packages that can be acquired from your distro. Likewise, you should avoid `pip install` in general because it writes to your global $HOME area.
  - Check `~/.local/lib/python*/site-packages` for `pip install` remnants. It'll install stuff there. If you see a PyQt installation there then delete it.
  - Never run pip outside of a virtualenv. It's *only* okay to run pip from inside a virtualenv.
  - I use [vx](https://gitlab.com/davvid/vx) because I never want to remember whether or not I did the "activate" / "deactivate" virtualenv dance -- I just vx all the time which means I never run "pip" on its own, which helps erase it from my muscle memory.
* Running `pip install` using sudo or as root
  - Installing stuff as root using pip can and will break your distro-provided python installation and related packages. Fixing this usually means using apt to reinstall the distro-provided python packages, but sometimes pip really breaks stuff.
  - This is such a common problem that pip eventually made this tougher to do by making this behavior opt-in behind a `--break-system-packages` flag ~ https://github.com/pypa/pip/pull/11780. Older pip versions will "break system packages" by default.


Please read the README.md and if there's anything unique about your situation please share so that we can update the instructions.

Since you're on ubuntu then my best advice is to cleanup/delete any stray PyQt installations you have and rely solely on distro-provided PyQt packages.
