### ISSUE TITLE
Missing git-cola etc to launch it once pip installed or installed from source

### ISSUE THREAD

**Issue by AddictArts** [git-cola/git-cola#1326]
I followed the README and after a pip install there is nothing to launch it. Missing from the command line is git-cola and not `git cola.

Tried pip install git-cola.

Built the source and make install.

Ubuntu 22.04

Thanks for the help

**Comment by davvid** [comment]
Did you run `make install` without any arguments, or did you run it while specifying the `make install prefix=....` with a installation prefix?

If you ran `make install` without any arguments then it will have installed the launcher script at `$HOME/bin/git-cola`.

Try running `~/bin/git-cola`. If that works then you can make `git cola` work as well by adding `$HOME/bin` to your $PATH.

Are you on Linux? macOS?

Some Linux distributions ship with a default shell environment profile that includes `$HOME/.local/bin` in `$PATH` by default. Check your `$PATH` (`echo $PATH`) to see.

If `echo $PATH` contains that location then instead of changing your shell settings you can `make install prefix=$HOME/.local` and it'll install into the `~/.local/bin` directory.

Also, does launch fine if you run `./bin/git-cola` directly from the source tree?

**Comment by kurtmckee** [comment]
@davvid The wheel that was uploaded to PyPI was built incorrectly. It's missing a top-level `entry_points.txt` file. I'm seeing similar failures when I install git-cola using pipx:

```
$ pipx install git-cola
Note: Dependent package 'qtpy' contains 1 apps
  - qtpy
Note: Dependent package 'pyqt5' contains 3 apps
  - pylupdate5
  - pyrcc5
  - pyuic5

No apps associated with package git-cola.
Try again with '--include-deps' to include apps of dependent packages, which are listed above.
If you are attempting to install a library, pipx should not be used.
Consider using pip or a similar tool instead.
```

This problem appears to be restricted to the 4.3.0 wheel that's uploaded to PyPI, however. It's possible to force pip to download and install the `.tar.gz` file instead with this command, which allows git-cola to install correctly:

```
$ pipx install git-cola --pip-args "--no-binary git-cola"
```

Please yank the 4.3.0 release from PyPI, which is currently not usable by default. I recommend releasing a new version, perhaps 4.3.0.post0 or 4.3.1, after identifying and testing the root cause for the packaging failure.

**Comment by davvid** [comment]
Python packaging is a bit of a mess to be honest.

Our `pyproject.toml` contains this section, which is supposedly how we're supposed to convey this stuff:
```
[project.scripts]
cola = "cola.main:main"
git-cola = "cola.main:main"
git-dag = "cola.dag:main"
git-cola-sequence-editor = "cola.sequenceeditor:main"
```

Do you know what we're supposed to be doing? Maybe it's pipx that is broken? Any tips?

**Comment by davvid** [comment]
Maybe the issue is that cola isn't wheel-safe? Maybe we need to look into not generating wheels, possibly?

**Comment by kurtmckee** [comment]
Cola has previously been wheel-safe (4.2.1 has a wheel with an `entry_points.txt` file in the archive's `*.dist_info/` directory, for example).

Something about how the 4.3.0 wheel was generated appears to have changed since 4.2.1 was released. That could indicate a bug in the packaging software, or a change in the build process.

I naively tried running the following command in the current `main` branch:

```
python setup.py bdist_wheel
```

That command wasn't able to find the version, so `0.0.0` was used as the version. However, that command built a wheel in the `dist/` directory with an `entry_points.txt` file.

I then tried running:

```
pip install .
```

This generated and cached a wheel with the version `4.3.1.dev22+g605cc003`. I checked the cached wheel and it contained an `entry_points.txt` file.

What tool or command do you use to generate the packages for upload to PyPI? Has that process changed recently?

**Comment by kurtmckee** [comment]
(I'm asking because if the issue can be recreated it may point to bug in the tool that affects others. However, solving this for git-cola is a priority for me personally -- I use both Linux and Windows, and as a winget user, I'm very excited about the 4.3.0 release!)

**Comment by davvid** [comment]
Thanks. I think maybe I need to change from using `python -m build -n .` for building wheels to using `pip wheel .` instead.

After a quick test, it looks like the wheels generated using `pip wheel .` contains entry_points.txt while the ones built by the python `build` tool do not.

Thank for pointing this out! I'll try and get that patched up soon.

**Comment by kurtmckee** [comment]
Thanks @davvid! And thanks for your work on git-cola! It's fantastic, and I use it every day. :1st_place_medal: :crown: :+1:

**Comment by davvid** [comment]
Thanks! I think this is resolved now: https://pypi.org/project/git-cola/4.3.1/

I used `pipx install git-cola` and I got the entry point scripts this time. Much appreciated!

**Comment by kurtmckee** [comment]
Nice! Thanks @davvid!

**Comment by AddictArts** [comment]
> Thanks! I think this is resolved now: https://pypi.org/project/git-cola/4.3.1/
> 
> I used `pipx install git-cola` and I got the entry point scripts this time. Much appreciated!

Ditto, thanks
