### ISSUE TITLE
Support file renames in DAG

### ISSUE THREAD

**Issue by BaumiCoder** [git-cola/git-cola#1327]
## Needs and benefits
Some times files get renamed or moved. I like to see the commits to a file in the history completely. This also includes the commits before renames. I would like to see such a full history with dag, so that I don't have to use the shell and tip something like `git log --follow history.txt`.

### With "Log Options" in DAG
I try  `git dag --follow history.txt`, but it shows the same like `git dag history.txt`. I though that should change something, because of the section [log Options at the documentation](https://git-cola.readthedocs.io/en/latest/git-dag.html#log-options).

I made a little test repository. You can find it [here](https://github.com/BaumiCoder/renameAndHistory).

## Feature Description
I would like to see the commits to a file before the file was renamed or moved. In Addition it would be nice to have extra markers, which show the renames at commits, for example "rename: renamed.txt --> history.txt". That would help me to keep track of the name of the file, I am looking at.

**Comment by BaumiCoder** [comment]
I updated to the latest version recently  (4.8.2 from AUR), but there `git dag --follow history.txt` still shows the same behavior as `git dag history.txt`.

**Comment by davvid** [comment]
Thanks for the heads-up. I just realized that the bug is arguably partially in core `git` itself.

Compare:

```
git log --follow cola/__init__.py
git log --reverse --follow cola/__init__.py
```

Surprisingly, `git` returns a truncated set of commits when `--reverse` is there, likely due to implementation details.

We use `--reverse` internally in `git dag` for the purposes of the graph ordering.

This gets further exacerbated when adding the `-<number>` option (which we also do) to limit the number of commits returned.

```
git log -2 --reverse --follow cola/__init__.py
```

Now it returns an empty set. Not exactly what we'd expect. Using `-2` without reverse correctly prints 2 commits.

In any case, I swapped things around so that we do the reversing part after reading from git's output, and we no longer pass `--reverse` to git. `git dag --follow <filename>` should be better behaved now.

I'll plan to tag v4.9.0 in about a week or so.

This issue was originally closed during an issue spring cleaning but now it's actually closed as completed. Thanks for the report.
