### ISSUE TITLE
Code comments stripped from commit message (text after `#` hashtag)

### ISSUE THREAD

**Issue by mara004** [git-cola/git-cola#1330]
It is common to include a code snippet in the commit description, like this

````md
commit text

```python
# code snippet with comments
if ... in ...:
    pass
```
````

However, when actually committing it with git-cola, the code comments are silently stripped, which is very unexpected (information loss).

in | out
--|--
![image](https://github.com/git-cola/git-cola/assets/65915611/1aff4c08-3e9f-4913-ab5d-1bd1ee66c2b4) | ![image](https://github.com/git-cola/git-cola/assets/65915611/e29e45e5-c31a-43cc-b407-3bcc4e8acf96)

---------

`About` -> `Version`
```
Git Cola version 4.2.1 
Linux-6.4.9-100.fc37.x86_64-x86_64-with-glibc2.36 
Python (/usr/bin/python3) 3.11.4 (main, Jun 7 2023, 00:00:00) [GCC 12.3.1 20230508 (Red Hat 12.3.1-1)] 
Git 2.41.0 
Qt 5.15.9 
QtPy 2.1.0 
PyQt5 5.15.9 
```

**Comment by davvid** [comment]
This is actually by design. We have a feature that lets you choose a different comment char if you prefer.

https://git-scm.com/docs/git-config#Documentation/git-config.txt-corecommentChar

It's a core git feature. `#` is the default comment char.

**Comment by davvid** [comment]
By "core git feature" what I mean is that we don't really have control over that behavior -- we let `git commit` handle the details. The upside is that we align with core git, so the behavior is the same when you `git commit` and it throws you into an editor.

**Comment by mara004** [comment]
Hmm, yes, it is logical to have a comment char when committing or rebasing in a text editor using plain git, with the commented-out preamble, which includes a nice message like `Lines starting with '#' will be ignored`.

However, it doesn't feel natural in a git GUI at all; there is no warning about this "feature" (nor a way to configure it in the git-cola GUI), and I see no sensible reason why you would want temporary comments in a GUI commit message. So this is still an unexpected loss of information, and of relatively high relevance for people who don't usually use command-line git.

I understand git-cola just forwards the commit message to git, but is there maybe a way to (automatically) escape the comment character, similar to shell or regex escaping? This would be the ideal solution IMO. Defining a different char is just a workaround that can lead to similar unexpected situations.

**Comment by mara004** [comment]
I did a search over the git docs. It turns out `git commit` actually provides a `--cleanup=<mode>` option that can be used to configure this behavior. I'd suggest to use `--cleanup=whitespace`, which strips whitespace but does not remove commentary.

This can be configured via `git config [--global] commit.cleanup whitespace`, but I think a GUI should pass the option with the commit command since commentary stripping is not desired in GUI mode but may be in CLI mode.

@davvid Please consider re-opening the issue. Thanks!

Extract from git help:
```
--cleanup=<mode>
   This option determines how the supplied commit message should be cleaned up before committing. The <mode> can be strip, whitespace, verbatim, scissors or default.
   strip
       Strip leading and trailing empty lines, trailing whitespace, commentary and collapse consecutive empty lines.
   whitespace
       Same as strip except #commentary is not removed.
   verbatim
       Do not change the message at all.
   scissors
       Same as whitespace except that everything from (and including) the line found below is truncated, if the message is to be edited. "#" can be customized with core.commentChar.
           # ------------------------ >8 ------------------------
   default
       Same as strip if the message is to be edited. Otherwise whitespace.
   The default can be changed by the commit.cleanup configuration variable (see git-config(1)).
```

**Comment by davvid** [comment]
There are cases where the comments are helpful. For example, cola detects the presence of `.git/MERGE_MSG` (and `.git/SQUASH_MSG`) and automatically loads them into the editor, comments and all. I suspect we won't need to change that behavior, though -- it looks like we have a simple solution.

In light of `commit.cleanup` we should add a configuration combobox that lets the user pick the behavior they'd like to have.

Thanks for pointing out `commit.cleanup`. I think that implies that you can run:

```
git config --global commit.cleanup whitespace
```
and cola will preserve #-lines the commit messages. Please try this out and let me know if it's not behaving as expected.

I've re-opened this issue since it seems like we have two things to improve. We should add a section to our documentation pointing to `core.commentchar`, `commit.cleanup`. We should also update preferences/settings dialog to expose both `core.commentchar` and `commit.cleanup`. The `commit.cleanup` UI widget should be a combobox with the available choices: default, verbatim, strip, whitespace and scissors.

**Comment by davvid** [comment]
Until this is implemented, while this isn't a great workaround, a simple thing to do that side-steps this behavior is to indent your python code with four spaces, eg.

```
commit text. example code:

    for x in y:
        print(x * y)
```

It looks like the behavior of `-F` did not previously apply stripping of comments (which is why we were doing it ourselves, apparently). I'll have to dig up the git version where `commit.cleanup` was introduced so that we only do the stripping on our end when using older versions of git. That should be a way of doing it that gets us the better behavior by default (`whitespace` is the default when not using an editor, per the docs for `default`).

**Comment by davvid** [comment]
The mantra of, "follow the git defaults" actually ended up working out well for this issue.

Git's default for `commit.cleanup` is a string value of `default`.

When the `default` mode is used Git will only cleanup whitespace when committing through `git commit -F <filename>`, (which is what Git Cola uses). It will not cleanup comments.

When committing using `git commit` on the command-line then Git will cleanup both comments and whitespace.

This seems like a pretty sensible behavior so that's what we've got now. In other words, Git Cola now retains `#` comments by default since that's what Git's `default` mode does.

If someone wants to get the old behavior, where Git Cola would strip `#` commentary, then they can `git config --global commit.cleanup strip` or use the "Commit Message Cleanup" drop-down in the preferences to set the value to `strip`.
