### ISSUE TITLE
remember user credentials

### ISSUE THREAD

**Issue by aleksejalex** [git-cola/git-cola#1340]
Is there actually an option to save/remember user's username and password (in case of private github repos github token)? 
If there is, please help me to find it, I'm new to gitcola :-) It's pretty awkward to type username and token everytime I want to fetch or push.

Thanks in advance

**Comment by davvid** [comment]
I personally recommend use of ssh URLs for pushing since that's the most secure.

Beyond that, a common approach is to use Git's built-in credential helpers.

https://git-scm.com/docs/gitcredentials

https://git-scm.com/doc/credential-helpers

If you configure Git to use a credential helper then Git Cola will use it automatically as well.

cheers!
