### ISSUE TITLE
Flatpak install: cannot access pre-commit hooks or launch editor

### ISSUE THREAD

**Issue by antoine-gallix** [git-cola/git-cola#1377]
I have git-cola installed as flatpak application, which I assume is maintained by the same developer community. This install can run my local git for things like staging changes, but cannot commit because it doesn't find the pre-commit binaries. Commiting from CLI works fine. I also experienced errors when trying to open an editor from git-cola. It doesn't find the editor binary, even though the path in the settings is absolute.

This make me think that there is a general issue with permissions in the flatpak distribution.

[https://flathub.org/apps/com.github.git_cola.git-cola](https://flathub.org/apps/com.github.git_cola.git-cola)

**Comment by davvid** [comment]
If you're on LInux you're better off just running the tool directly.

I don't have an opinion on the flatpak setup (it was contributed by folks from the flatpak community) so unfortunately I'm not able to help much since I don't know how to build it or how to run it.

Kindly report this issue to the flatpak repo since that'll get better eyes on it ~ https://github.com/flathub/com.github.git_cola.git-cola

Cola runs "git" commands and has to access the filesystem so some of the isolation features of flatpak can end up causing these kinds of issues. So, yeah, you're correct that these are probably general permission issues in the flatpak distribution.

You mentioned pre-commit hooks so I assume that there's some pre-commit binaries in your `$PATH` that the flatpak app is not able to access. That may or may not be something that flatpak allows. If there are general facilities for opening up filesystem locations to prebuilt flatpaks without changing the flatpak app then that's probably a solution since the base flatpak app can't/won't know about the custom tools in your environment. I didn't see such an option based on my 5 minutes of browsing their docs.

https://docs.flatpak.org/en/latest/sandbox-permissions-reference.html#filesystem-permissions

I'll keep this issue open for a bit to see how things pan out before closing it. Like I said, running the tool directly (rather than via flatpaks) is the simplest way to get things working.

Thanks for the heads-up.

(an aside ~ if anyone knows the steps to create and run the flatpak locally I can probably try it from that side)

**Comment by antoine-gallix** [comment]
Thanks for your quick and detailed answer. I hadn't found the flatpak package repo on github, it was not linked in the flatpak package page on flathub; now that I know of it I'll forward the issue to them.

I run an almost 2 years old ubuntu install with an old `git-cola` version, so flatpak was the way to get something fresher without having to upgrade my whole distro.
