### ISSUE TITLE
Git-cola crashes when no commit.template is defined

### ISSUE THREAD

**Issue by mroeling** [git-cola/git-cola#1384]
What:
Crash of Git-cola on commit. The resolution for me to fix is easy, but IMHO the application should never crash.

Version / deployment information:
* version: v4.5.0
* OS: Ubuntu 23.10
* install location: ~/Programs/git-cola using Git
* run location: ~/Programs/git-cola/bin/git-cola

Extra info:
* no global commit template available

Steps to reproduce:
* commit any file
* results in:
![image](https://github.com/git-cola/git-cola/assets/2706186/7f6bf89a-c377-43a6-9593-224fb55cf6fd)
* with error message:
```Traceback (most recent call last):

  File "/home/mark.roeling/Programs/git-cola/cola/cmds.py", line 3119, in do
    return cmd.do()
           ^^^^^^^^

  File "/home/mark.roeling/Programs/git-cola/cola/cmds.py", line 833, in do
    template_loader.do()

  File "/home/mark.roeling/Programs/git-cola/cola/cmds.py", line 1682, in do
    raise UsageError(

cola.cmds.UsageError: A commit template has not been configured.
Use "git config" to define "commit.template"
so that it points to a commit template.
```

Workaround: 
* `touch ~/.gitmessage`
* `git config --global commit.template ~/.gitmessage`

**Comment by davvid** [comment]
I suspect that you have `Automatically Load Commit Message Template` set in your preferences.

That's not really a crash.. it's reporting the misconfiguration, but I agree that it looks too scary, and it uses the same dialog that's used when we have an actual problem in the code.

I'm going to change these so that they emit messages to the Console widget instead. Thanks for the heads-up!
