### ISSUE TITLE
Mac Cmd+M (minimize window) is ignored by git-cola and has different action

### ISSUE THREAD

**Issue by mikeg-asi** [git-cola/git-cola#1390]
Hello,
In git-cola on Mac the Cmd+M triggers "Amend Last Commit".  Is there some configuration that will allow Cmd+M to be the normal Mac minimize window behavior?
Thanks

**Comment by davvid** [comment]
Thanks for the heads-up. I'll take a stab at this.

I'm going to try using a different hotkey on macOS. We can use `Alt-m` on macOS and `Ctrl-m` elsewhere.

It's either that, or we'll switch that hotkey on all platforms to be `Alt-m`. This is a slightly "cleaner" option, but it will mess with users that have the old hotkey memorized so it's not really a viable option.

Hmm.. so maybe what I'll do is I'll update the docs to only refer to `Alt-m`, but internally I'll also support `Ctrl-m` on non-macOS platforms so that existing users can continue using `Ctrl-m`. Best of both worlds.
