### ISSUE TITLE
please look into fixing the "flashbang" effect when the main window spawns (windows)

### ISSUE THREAD

**Issue by Ryder17z** [git-cola/git-cola#1398]
I set the theme to be dark, but the main window spawns in purely white - then draws everything after a couple of seconds as it should with the selected theme.

It is not a huge problem, but still very annoying to me.

**Comment by davvid** [comment]
Heh, dejavu. I fixed a similar issue in neovim-qt ;-) https://github.com/equalsraf/neovim-qt/pull/1101

I'll leave this issue open since the rationale in that issue applies here as well.

Is your window manager settings set to a dark theme as well? I'm wondering whether there's a Qt setting that can make it default to dark mode as well in your environment that could possibly fix it at that level as well.

If I'm understanding correctly, you're using one of cola's dark themes rather than using the default settings (which inherit the theme colors from the OS desktop environment).

Are you on Linux? Are you on Gnome?

**Comment by Ryder17z** [comment]
I think you misread the title?
Tested on win10
