### ISSUE TITLE
Feature request: custom keybindings(?)

### ISSUE THREAD

**Issue by birgersp** [git-cola/git-cola#1399]
(Title)

Would really like to switch between widgets with custom keys

Specifically, I would personally like these key bindings:

* alt+1: focus Status widget
* alt+2: focus Diff widget
* alt+3: focus Commit widget

**Comment by davvid** [comment]
This would be a fairly significant refactor, but being able to customize the builtin keybindings is something that has been lingering in the back of my mind for a while.

One way forward ("option A") would be to have a way to register custom hotkeys that don't overlap with the builtin hotkeys. It does kind of imply that we might need to have some special common chord or modifier that is reserved for user-defined hotkeys, and we've kinda already used all of the modifiers in some form, so we probably can't reserve something like `Alt-<anything>` at this point.

That would allow us to have a standard set (that's the same for *all* users) and a user-defined set without having to worry about future clashes, but it would be less flexible since all custom hotkeys would have to share the same modifier chord.

Supporting completely custom keybindings ("option X") would be the most general approach, albeit at a larger development effort and a much larger rework, so that might not be quite worth the tradeoff.

A middle ground would be to start reserving specific hotkeys for user-defined purposes ("option B").

By reserving specific hotkeys as being user-defined then it would be a smaller implementation effort (because we can leave the current hotkeys as-is) while also making the sug in this issue possible.

Having written that, I'm kinda leaning towards Option B where we start reserving a set of user-defined hotkeys that can be mapped to custom actions. We can start out by adding `Alt-<number>` to the reserved user-defined hotkeys and provide actions for focusing tools and other common actions.

Let me know if you think that'd be useful as a starting point. If so, then please also share some other actions that you think you might want to access via custom keybindings.
