### ISSUE TITLE
Feature: faster and easier commit hash copying in DAG

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#1401]
Hey,

Please consider adding a feature to DAG where in the Diff pane's caption, interacting with the commit hash is changed as follows:

1. Left-clicking copies the hash, copying the full hash is in a custom context menu. Add a subtle animation (toast popup, tooltip popup, short commit hash text color change) to provide feedback (text is proportionally smaller to the mouse sensitivity in 4K and clicking accurately is more of a problem).

2. The hash getting copied is the short version (configurable), the hash displayed in the UI is configurable as well. Why the short hash? Pasting long hashes into a terminal takes a decent chunk of the entire line, it's awkward to deal with it. Manually shortening the hash after pasting is awkward and error-prone.

cheers! -sh

**Comment by sthalik** [comment]
Also please consider making the DAG's commit email field non-clickable. It makes clicking on the commit hash harder, since avoiding clicking on the email field accidentally makes clicking on the commit hash harder.

**Comment by sthalik** [comment]
Also please consider adding to DAG a 'grab file' from just the previous revision. If the commit hash is FOO, then rather than the equivalent of `git show FOO:file`, do `git show FOO^:file`.

At least for me, doing `git show FOO^:file` from a terminal after copying the hash from DAG is a rather common operation, especially with feature branches 

I suppose it could become a bit flaky with merges, but in 99% of cases when I do to `git show ... > foo` into the terminal after copying the hash, merges aren't a factor.

Similarly, `git checkout -f FOO -- file` and `git checkout -f FOO^ -- file` are common operatios for me and they could be added to the same context menu.

**Comment by davvid** [comment]
I dig it. These all seem like pretty straightforward and useful enhancements.

**Comment by davvid** [comment]
The DAG commit ID copying interactions have been implemented. The "grab file" feature is up next.

**Comment by davvid** [comment]
The one thing I might suggest differently after using this a bit would be to leave the commit ID displaying the full SHA-1. The rationale is that it's a bigger hit area so it's easier to click on.

I'd like to get your opinion on that @sthalik after you get a chance to try it with the shorted display like it currently has, though.

**Comment by sthalik** [comment]
You're right about the ergonomics of displaying the short hash, additionally it looks weird to have the short string on the very top. 

Then the question is whether clicking on the label should copy the short hash or the long one. Copying the short hash would be a QoL improvement, but introduce a potentially confusing inconsistency.

How about this approach:
- long hash is displayed
- clicking on it copies the short hash
- long hash can still be copied by clicking and holding the left mouse button to the right of the hash and dragging the cursor leftward

For the last point to occur, you'd have to set the label to the `Qt::ClickFocus` focus policy.

**Comment by davvid** [comment]
The "Grab File from Parent Commit" feature was just added.

I did restore the full length of the Commit ID for display.

> Copying the short hash would be a QoL improvement, but introduce a potentially confusing inconsistency.

I'm personally okay with the inconsistency because the UI updates are now very consistent about calling out `Ctrl-c` as being the shortcut for `Copy Commit (Short)` and `Alt-Ctrl-c` as being the shortcut for `Copy Commit`, so the display length is the only tiny difference and pretty minor since the rest of the UI is consistent within itself.

>   *  long hash can still be copied by clicking and holding the left mouse button to the right of the hash and dragging the cursor leftward
>
> For the last point to occur, you'd have to set the label to the Qt::ClickFocus focus policy.

The behavior is so much nicer with `Qt::NoFocus` because I can have the commit list focused and jump between commits using up/down or j/k and clicking keeps the commit list focused, so I ended up leaving this part as-is.

That said, we already have the right-click context menu so the drag-leftward gesture shouldn't really be needed. It's probably a little harder to pull off, too, since it requires a bit more precision (dragging) so I think letting the context menu handle it is a good solution. Likewise, we also have the keyboard shortcut so we should be good on all fronts.

Thanks again for the sugs.
