### ISSUE TITLE
install & packaging issue on FreeBSD for 4.8.0

### ISSUE THREAD

**Issue by dch** [git-cola/git-cola#1407]
The current FreeBSD port is v4.1.0, but I can't upgrade past that. For example, v4.8.0.

I switched the build over the pep517, but see the [following failure](https://pkg.skunkwerks.at/poudriere/data/current_x64-default/2024-07-06_14h09m24s/logs/errors/git-cola-4.8.0.log)
Do you have any suggestions what might be going wrong here?

```
# snippet from full build log
===>   Building git-cola-4.8.0
pkg-static: Unable to access file /wrkdirs/usr/ports/devel/git-cola/work-py311/stage/usr/local/lib/python3.11/site-packages/cola/widgets/__pycache__/patch.cpython-311.opt-1.pyc:No such file or directory
pkg-static: Unable to access file /wrkdirs/usr/ports/devel/git-cola/work-py311/stage/usr/local/lib/python3.11/site-packages/cola/widgets/__pycache__/patch.cpython-311.pyc:No such file or directory
pkg-static: Unable to access file /wrkdirs/usr/ports/devel/git-cola/work-py311/stage/usr/local/lib/python3.11/site-packages/cola/widgets/patch.py:No such file or directory
pkg-static: Unable to access file /wrkdirs/usr/ports/devel/git-cola/work-py311/stage/usr/local/lib/python3.11/site-packages/git_cola-0.0.0-py3.11.egg-info/PKG-INFO:No such file or directory
pkg-static: Unable to access file /wrkdirs/usr/ports/devel/git-cola/work-py311/stage/usr/local/lib/python3.11/site-packages/git_cola-0.0.0-py3.11.egg-info/SOURCES.txt:No such file or directory
pkg-static: Unable to access file /wrkdirs/usr/ports/devel/git-cola/work-py311/stage/usr/local/lib/python3.11/site-packages/git_cola-0.0.0-py3.11.egg-info/dependency_links.txt:No such file or directory
pkg-static: Unable to access file /wrkdirs/usr/ports/devel/git-cola/work-py311/stage/usr/local/lib/python3.11/site-packages/git_cola-0.0.0-py3.11.egg-info/entry_points.txt:No such file or directory
pkg-static: Unable to access file /wrkdirs/usr/ports/devel/git-cola/work-py311/stage/usr/local/lib/python3.11/site-packages/git_cola-0.0.0-py3.11.egg-info/not-zip-safe:No such file or directory
pkg-static: Unable to access file /wrkdirs/usr/ports/devel/git-cola/work-py311/stage/usr/local/lib/python3.11/site-packages/git_cola-0.0.0-py3.11.egg-info/requires.txt:No such file or directory
pkg-static: Unable to access file /wrkdirs/usr/ports/devel/git-cola/work-py311/stage/usr/local/lib/python3.11/site-packages/git_cola-0.0.0-py3.11.egg-info/top_level.txt:No such file or directory
*** Error code 1
```

**Comment by davvid** [comment]
> `pkg-static: Unable to access ...egg-info/top_level.txt`

Is freebsd's packaging format similar to RPM in that the package has to provide a list of files that it expects to be generated?

If that's the case, updating the metadata to not expect these `__pycache__` and egg info files *should* produce a working package, though it's probably first worth checking whether those files do exist under a different name. If they do then the metadata needs updating to match those names.

Here's some more random debugging notes in case it helps. The `0.0.0` in the path suggests that setuptools-scm didn't find a git repo so it won't generate the expected version numbers. This shouldn't matter in practice; I think this means you're building from tarballs rather than cola's git repo.

I couldn't find the `make` invocation or the output from cola's Makefile in the log, but I hope it's still using the equivalent of `make install prefix=/usr/local DESTDIR=/wrkdirs/usr/ports/devel/git-cola/work-py311/stage` when trying to install stuff.

You could also use `make install prefix=/wrkdirs/usr/ports/devel/git-cola/work-py311/stage/usr/local` (i.e. mash DESTDIR and prefix together) to get the files in place physically, and that might work, but that approach can sometimes burn the temporary stage directory into the installed files, which is bad since the final location will be under /usr/local.

The semantics of DESTDIR is that it ultimately boils down to whether or not we're calling `pip` with the `--root` option specified. When `DESTDIR` is present the Makefile adds the `--root=$(DESTDIR)` option to its `pip install` invocations.

The `pkg-static` command or system might be something worth digging into, since the error is ultimately originating from its configuration.

It'd be helpful to see the output of `find /wrkdirs/usr/ports/devel/git-cola/work-py311/stage` since that might provide some more clues.

In case it helps, one approach might be to not use `pip install` like we're doing in the Makefile and instead do what this arch user does in their PKGBUILD file:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=git-cola

They use `python -m build ....` to generate `*.whl` wheel files and then they use `python -m installer ....` to install the wheels and then they use `make install-man ....` separately to get the man files in place.

I hope that helps, and let's see if we can get freebsd's package building again. If generating wheels and then installing them is what distros are supposed to do now then I can look into updating the docs to mention that once you've got it working.

**Comment by davvid** [comment]
Another possibility -- maybe when this package was first authored it didn't use a git repo so the `0.0.0` paths were correct, and now the metadata needs to be updated to reflect the now-correctly versioned paths. If a wildcard can be used in the freebsd package config files then that should let it get past that difference in pathing.

Feel free to chime back in case there's something else we can do to help. I don't have access to a freebsd runtime for debugging this but I'd be more than happy to suggest ideas in case you're still running into issues.
