### ISSUE TITLE
DAG crashes immediately after calling on Linux Mint 21.1. As well as when pressing "F1" or "?"

### ISSUE THREAD

**Issue by f91-test** [git-cola/git-cola#1414]
Issues i had observed on the system package (installed with apt-get, version 3.12):
* when i try to press F1 or ?, the program crashes immediately
* when i try to press View -> DAG, the program crashes immediately
* when i open GIT DAG first, it opens and allows me to select the repository, but then crashes as soon as i select it

Issues i had observed after installing with pip, version 4.8:
* all the same as above

Issues i had observed on the flatpak version:
* when i try to press F1 or ?, the program crashes immediately

This issue is rather related to my particular system because git-cola works well if i install it on a fresh Mint 21.1. Anyway, i spend some time trying to figure out what is wrong but without result.

I attach the list of all my installed packages for possible debugging
[installed-packages.txt](https://github.com/user-attachments/files/16552562/installed-packages.txt)

**Comment by davvid** [comment]
If you ran pip outside of a virtualenv then there's two things it could have done.

If run as root, it could have installed conflicting packages in system locations.

If run as a regular user, it could have installed conflicting packages in `~/.local/lib/python*` and the solution *might* be to delete those.

Things in theory should work just fine w/ the system packages. I'm running Debian/testing and it should be pretty darn close to Linux Mint and stuff works for me using the system packages so I am inclined to believe that `pip` may have left conflicting packages somewhere.

To debug your issue further, you can run `python` interactively and try importing modules (`from qtpy import QtWebEngineWidgets`.

Furthermore, to force use of PyQt6 you can:

```sh
export QT_API=PyQt6
```

The relevant Qt6 packages are:

```sh
sudo apt install python3-pyqt6 python3-qtpy python3-pyqt6.qtsvg python3-pyqt6.qtwebengine
```


If you're using PyQt5, the relevant packages are:

```sh
sudo apt install python3-pyqt5 python3-qtpy python3-pyqt5.qtsvg python3-pyqt5.qtwebengine
```

If QtWebEngineWidgets are not available then we fallback to launching a browser for the `?` help screen. A crash suggests a python module incompatibility.

When in doubt, remove anything installed manually by `pip` and install (or re-install) stuff via the `apt` package manager. The system-provided packages should work just fine.

You can check for further paths in the python console.

```sh
python3
>>> import sys
>>> print(sys.path)

# The locations printed by the above command are places where (conflicting) modules might be found.
```


You can also try importing stuff manually via the python interpreter and that might point out the exact library. e.g. `from qtpy import QtWebEngineWidgets` might point you closer to the problem.

Likewise, importing the modules directly might point you closer to the root cause. Here's a snippet of an interactive python session where I did that.

```sh
$ python3                                                          
Python 3.12.5 (main, Aug 22 2024, 13:11:09) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5 import QtWebEngineWidgets
>>> print(QtWebEngineWidgets)
<module 'PyQt5.QtWebEngineWidgets' from '/usr/lib/python3/dist-packages/PyQt5/QtWebEngineWidgets.abi3.so'>

>>> from PyQt6 import QtWebEngineWidgets
>>> print(QtWebEngineWidgets)
<module 'PyQt6.QtWebEngineWidgets' from '/usr/lib/python3/dist-packages/PyQt6/QtWebEngineWidgets.abi3.so'>
```

Repeating those steps should hopefully point you in the right direction. Hope that helps, and sorry about `pip` and library conflicts. My rule of thumb for `pip` is to never use it outside of a virtualenv.
