### ISSUE TITLE
Add `-u` when pushing to remote with a different name

### ISSUE THREAD

**Issue by brccabral** [git-cola/git-cola#1415]
When pushing to remote with a different name from local, need to add `-u` flag to the command.

https://stackoverflow.com/questions/5738797/how-can-i-push-a-local-git-branch-to-a-remote-with-a-different-name-easily

![image](https://github.com/user-attachments/assets/cb737e9a-584a-4b5a-96ed-454db0484b3e)

**Comment by davvid** [comment]
This isn't something you should be doing every time you push, as it changes the default behavior of `git push` on the command-line.

This is more of a one-off thing that you'd do for the case where the repo is not currently configured to be the repo that you "git push" to for this branch, and it's a "set it and forget it" kind of setting that you set once and no longer setup for the current branch.

Likewise you don't always want this behavior. I might have a dozen remotes and choose to push to them selectively and I wouldn't want this happening each time I pushed.

Anyways, there's already a, "Set Upstream" checkbox on the push dialog. If you enable that then it'll use `--set-upstream` (AKA `-u`) when  you push. This is a one-off checkbox and it isn't remembered across invocations, intentionally, due to the one-off nature of this setting.

cheers
