### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by ozyours** [git-cola/git-cola#1419]
**FileNotFoundError: [WinError 2] The system cannot find the file specified** error when using **Open Using Default Application** and **Open Parent Directory**
is this bug or i missed something?

**Comment by davvid** [comment]
Windows support for the "Open Default Application" code was added a long time ago. From `cola/utils.py`:

```python

def launch_default_app(paths):
    """Execute the default application on the specified paths"""
    if is_win32():
        for path in paths:
            if hasattr(os, 'startfile'):
                os.startfile(path)
        return

    if is_darwin():
        launcher = 'open'
    else:
        launcher = 'xdg-open'

    core.fork([launcher] + paths)
```

It uses `os.startfile(path)` to open the file or directory on Windows. Tha'ts a python builtin that takes care of everything (unless you know of an equivalent to `xdg-open` that we can use on Windows). It'll open the file using the default application. It's the equivalent of double-clicking the file via the Windows file explorer.

I'm not sure why it doesn't work for you, sorry, but hopefully that gives you an avenue to explore. I think the answer is you need to setup your default applications so that double-clicking on the file does the right thing from Windows and then cola will start doing the same.

If you're launching from within WSL, then that might be the reason. You can always submit an issue to microsoft to get them to make it work, as it could possibly be related to path translation across the OS layers (I'm totally guessing. I don't use Windows) or something specific to WSL that they might be able to fix.

This is very low-level and builtin to python so maybe they'd care about it. I just tested this myself in a Windows VM and opening directories is working as expected for me. I ran it directly from Windows not through any WSL layers so YMMV.

If you're running into Windows vs. WSL issues then the real answer is to switch to Linux. Sorry for being dismissive, but life is short and I don't have time to deal with WSL issues that are complete non-issues on Linux.

Thanks for the report. Even though I'm closing this, I would be more than happy for someone to suggest a better implementation or to debug and fix this issue, and for you to confirm whether or not WSL is in the mix.

I've gotten bug reports related to WSL in the past which is why I'm asking about it.

https://docs.python.org/3/library/os.html#os.startfile

I'm super curious whether this is really a low-level bug at that level because `os.startfile('filename')` is all we're doing on our end. There's not much we can do from python land if that function isn't working as advertised.

**Comment by ozyours** [comment]
> Windows support for the "Open Default Application" code was added a long time ago. From `cola/utils.py`:
> 
> ```python
> def launch_default_app(paths):
>     """Execute the default application on the specified paths"""
>     if is_win32():
>         for path in paths:
>             if hasattr(os, 'startfile'):
>                 os.startfile(path)
>         return
> 
>     if is_darwin():
>         launcher = 'open'
>     else:
>         launcher = 'xdg-open'
> 
>     core.fork([launcher] + paths)
> ```
> 
> It uses `os.startfile(path)` to open the file or directory on Windows. Tha'ts a python builtin that takes care of everything (unless you know of an equivalent to `xdg-open` that we can use on Windows). It'll open the file using the default application. It's the equivalent of double-clicking the file via the Windows file explorer.
> 
> I'm not sure why it doesn't work for you, sorry, but hopefully that gives you an avenue to explore. I think the answer is you need to setup your default applications so that double-clicking on the file does the right thing from Windows and then cola will start doing the same.
> 
> If you're launching from within WSL, then that might be the reason. You can always submit an issue to microsoft to get them to make it work, as it could possibly be related to path translation across the OS layers (I'm totally guessing. I don't use Windows) or something specific to WSL that they might be able to fix.
> 
> This is very low-level and builtin to python so maybe they'd care about it. I just tested this myself in a Windows VM and opening directories is working as expected for me. I ran it directly from Windows not through any WSL layers so YMMV.
> 
> If you're running into Windows vs. WSL issues then the real answer is to switch to Linux. Sorry for being dismissive, but life is short and I don't have time to deal with WSL issues that are complete non-issues on Linux.
> 
> Thanks for the report. Even though I'm closing this, I would be more than happy for someone to suggest a better implementation or to debug and fix this issue, and for you to confirm whether or not WSL is in the mix.
> 
> I've gotten bug reports related to WSL in the past which is why I'm asking about it.
> 
> https://docs.python.org/3/library/os.html#os.startfile
> 
> I'm super curious whether this is really a low-level bug at that level because `os.startfile('filename')` is all we're doing on our end. There's not much we can do from python land if that function isn't working as advertised.

Hi, thx for your help. Everything is run natively windows, no VM, WSL, or anything.
Btw, I just found out that **Open Using Default Application** and **Open Parent Directory** works on file on root folder, but not working for anything under another folder

![Untitled](https://github.com/user-attachments/assets/ffbef571-e63b-4b28-bd4a-664ab4fc764c)

Also, I added print to a file at above of `os.startfile`
```
 if is_win32():
        for path in paths:
            if hasattr(os, 'startfile'):
                with open(r'D:\\log.txt', 'w') as file:
                    file.write(path)
                os.startfile(path)
        return
```

when using **Open Parent Directory** on a file on root folder, the printed path is `H:\GitHub\godot\godot`
when using **Open Parent Directory** on a file inside another folder, the printed path is `core/crypto`
Btw, here is the full error message
```
Traceback (most recent call last):

  File "C:\Program Files\git-cola\pkgs\cola\cmds.py", line 3118, in do
    return cmd.do()

  File "C:\Program Files\git-cola\pkgs\cola\cmds.py", line 1818, in do
    utils.launch_default_app(dirs)

  File "C:\Program Files\git-cola\pkgs\cola\utils.py", line 313, in launch_default_app
    os.startfile(path)

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'core/crypto'
```
I think it might be related to the relative and absolute path.

**Comment by davvid** [comment]
Thanks for helping to narrow that down.

Does it work if you change the `os.startfile(path)` line to say `os.startfile(os.path.abspath(path))` instead?

If not, does it work if you change it to `os.startfile(path.replace('/', '\\'))` ?

If that doesn't work, then our last resort might be to use `os.startfile(os.path.abspath(path.replace('/', '\\')))` instead. Does that work either?

**Comment by davvid** [comment]
I did some quick tests and it looks like passing the path through `os.path.abspath(...)` makes things work correctly, so that's what we're doing now. Thanks for the report. Please let me know if this isn't working as expected in your environment.

**Comment by ozyours** [comment]
Yeah, it is working with ``os.startfile(os.path.abspath(path))``, thanks.
