### ISSUE TITLE
4.8.2 stopped working with Qt6

### ISSUE THREAD

**Issue by installgentoo** [git-cola/git-cola#1422]
Switching to pyqt6, cola exhibits a weird behaviour that prevents it from opening a repo when started from wm.

Edit: to replicate use keyboard to select a repo, click enter to open repo. On qt6 cola just exists

**Comment by installgentoo** [comment]
FOR SOME REASON qt6 doesn't register "enter" as open a repo, and instead as "close" being clicked. This is ridiculous!

**Comment by davvid** [comment]
Just that specific feature, yeah? I've been patching PyQt6-related compatibility fixes for the last year or two so I'm all ears if you've got any others.

I don't use the startup prompt very often so I never saw it during my PyQt6 testing. I'll start setting `QT_API=PyQt6` in my environment by default so that it gets more usage on my end as well. Thanks for the report.
