### ISSUE TITLE
Consider setting the TERM environment variable to `dumb` when running external commands on non WIN32 platforms

### ISSUE THREAD

**Issue by brlin-tw** [git-cola/git-cola#1426]
I've encountered a problem where Ansible-lint will have colorized output despite its stderr not being a terminal(ansible/ansible-lint#4347), upon inspecting their code to determine whether the colorized output should be enabled it seems that [it depends on the `TERM` environment variable's value before even checking the type of the output device](https://github.com/ansible/ansible-lint/blob/a3f8492505b60d4be2c9df973967dca436c0cfa4/src/ansiblelint/__main__.py#L498).

As our console implementation doesn't support colorized output(#310) we probably should set the `TERM` environment variable to `dumb` to avoid confusing the called subprocesses.

This seems to only apply to non-Windows platforms, but I may be wrong.

## References

* [term 7 2024-05-11 ncurses 6.5 Miscellaneous](https://invisible-island.net/ncurses/man/term.7.html)

**Comment by davvid** [comment]
Alternatively, do they support the `NO_COLOR` environment variable?

https://no-color.org/

**Comment by brlin-tw** [comment]
I can verify that setting the `TERM` environment variable to `dumb` can workaround the Ansible-lint problem:

![Screenshot](https://github.com/user-attachments/assets/eb4f6126-bda2-44a7-b2ac-2ce60bec5cad)

**Comment by davvid** [comment]
I wasn't sure whether `ansible-lint` was a separate tool from `ansible` so I checked and verified that they do support `NO_COLOR` in the lint script as well. Same file you linked above, just a few lines below:

https://github.com/ansible/ansible-lint/blob/a3f8492505b60d4be2c9df973967dca436c0cfa4/src/ansiblelint/__main__.py#L510

There are situations where we execute a terminal or external editors and we don't want our `NO_COLOR` setting to transfer to these tools. This can happen indirectly, e.g. when doing a rebase.

For that reason, I'm going to try to limit this to a few specific operations rather than setting that variable globally in cola's environment (e.g. `setup_environment()` in `cola/app.py` is a spot we shouldn't update).

The places where we'll set `NO_COLOR` will be the ones that you're running into. From the screenshot, it looks like one place it's getting triggered is during `git commit`. Remote operations (fetch/push/pull) can also have hooks that lead to similar output ending up in the dialogs we display, so we'll set the variable for those commands as well.

Let me know if there are other scenarios where you're hitting it.

**Comment by brlin-tw** [comment]
@davvid 

I can still reproduce the problem in the same context using the 966512f revision:

![Screenshot](https://github.com/user-attachments/assets/df1a653e-86b9-4ec9-a7ee-541cd6d7115e)

**Comment by davvid** [comment]
Interesting. I went ahead and added `TERM=dumb` as well. That's kinda surprising.

If it's still not working as expected then to help debug it it'd help if you could tweak the pre-commit hook in your `.git/hooks` directory to run the "env" command so that we can see the environment variables that it's seeing.

We should expect to see both `NO_COLOR=1` and `TERM=dumb` in there.

**Comment by brlin-tw** [comment]
Using the dd8ecdd5 revision works:

![Screenshot](https://github.com/user-attachments/assets/1616f3ed-f078-4206-a2d8-c5e7c312218f)

When I add the `env` pre-commit hook on the revision d66512f, the `NO_COLOR` environment variable is set however Ansible-lint still outputs colorized text:

![Screenshot](https://github.com/user-attachments/assets/43c37b48-bf6d-49a6-a99c-eed67e977f15)

**Comment by davvid** [comment]
Kindly reporting this to the ansible-lint project as well ~ it'd be good for them to correctly handle `NO_COLOR` without us needing to set `TERM=dumb`, /methinks. Thanks for verifying those details.

**Comment by brlin-tw** [comment]
@davvid 

Thanks for the help!

> Kindly reporting this to the ansible-lint project as well

Will do.

**Comment by brlin-tw** [comment]
@davvid 

After some testing, I noticed that Ansible-lint _does_ honour the `NO_COLOR` environment variable:

![Screenshot](https://github.com/user-attachments/assets/a90540e0-b3b7-448c-ac97-ad7c6a5b8f83)

 it's just that the ASCII escape sequence we noticed when the `NO_COLOR` environment variable is set is for [changing the _intensity_  of the text, not color](https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_(Control_Sequence_Introducer)_sequences):

![Screenshot](https://github.com/user-attachments/assets/694f0b2b-50a6-47c1-954c-27630eded65d)

![图片](https://github.com/user-attachments/assets/e3b0af5e-b5c2-4a57-99d4-58a32d0d8eb3)

So, to avoid the subprocess spewing ASCII escape sequences, we probably could only rely on `TERM=dumb`.

## Reference

[ANSI escape code - Wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_(Control_Sequence_Introducer)_sequences)

**Comment by davvid** [comment]
Good sleuthing! I wonder if they would be open to considering "intensity" as part of that since I suspect that most users of `NO_COLOR` would consider that to essentially mean "no ansi escape sequences".

I wonder if this was an oversight on their part in not looping the intensity values under the same umbrella or whether it was deliberate. I'm hoping that it was accidental, but I can only hope ;-)

All good either way. Thanks for the deep investigation.
