### ISSUE TITLE
DAG's columns keep over-resizing

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#1432]
In the DAG commit list, the tab widget auto-adjusts the individual columns in certain cases, such as resizing the window or moving it between monitors. 

The issue is that it resizes itself into just slightly too big so that the scrollbar appears. I can correct it in the UI, but it's going to resize itself again after a while. At least that's how it happens on Windows. 

In particular, there's this thing:

![image](https://github.com/user-attachments/assets/4768e531-9791-44be-8496-0aecb056ebb7)

Right now my DPI scaling is manually disabled in Cola options and Cola/DAG tends to run on my secondary display, but it happens the same on the 175% scaled 4K display.

Other than that, it's working great and I'm using Cola all the time while reading and writing code.

**Edit**: it also happens to the file list in DAG.
**Edit 2**: 'Lock Layout' is enabled.

**Comment by davvid** [comment]
I changed the behavior so that the horizontal scrollbar is only visible when you hover your mouse over the bottom of the widget.

I'm not sure why the columns are resizing themselves. The only situation where we set an initial size is on the very first time the DAG is opened. Later invocations will record the column widths that you've set interactively and restore them, and this restoration is only done once when the DAG widget is first opened.

There shouldn't be any code that's resizing the columns after this initial setup so it's interesting that you've observed it happened while the app is still running. Moving between monitors is an interesting scenario, though, and perhaps that's enough to have Qt resize the contents and have things barely not fit anymore.

I think this new behavior should help because it makes it so that even if the column is slightly too large it won't matter since the scrollbar won't be shown by default.

It should be noted that we've tweaked this behavior in the past. #674 was when this resize logic was last adjusted, so hopefully we've arrived at a better place now.

Thanks for the report and let me know if this is better behaved in your setup.

**Comment by davvid** [comment]
I found a few more places where this behavior was improved. I also realized that we were resizing to the widget's width (which includes its margins) instead of the header's width, which would cause the columns to always be slightly larger than the widget, thus leading to horizontal scrollbars.

This has been fixed as well so it should be better behaved all around.

**Comment by sthalik** [comment]
Hover the cursor over the bottom part of the widget. Then move it down below its boundaries, but *slowly*. The cursor will stick itself and won't stop displaying until reentering the widget.

Another thing, it possibly could help if the date column was resized to fit the date exactly (with perhaps some ~5 pixel additional grace size). See:

- https://doc.qt.io/qt-6/qtableview.html#horizontalHeader
- https://doc.qt.io/qt-6/qheaderview.html#resizeSections-1
- https://doc.qt.io/qt-6/qheaderview.html#ResizeMode-enum

**Comment by sthalik** [comment]
I'd fix it myself and send a PR but it's hard to find the right place in a dynamically-typed language, sorry :(

**Comment by davvid** [comment]
Thanks for the feedback. That's certainly funky behavior and it's probably better to avoid playing visibility games with the scrollbars. I was not able to reproduce this behavior on Linux (gnome) so I suspect that there's some edge cases when running across platforms so the original approach was getting a bit too clever.

I simplified the technique so that it should be better behaved.

Firstly, an important background piece of information is that the DAG remembers the column sizes that you last used (across restarts of the app). Setting the size on the final column prevents the Stretch resize policy setting from working nicely, and furthermore it causes the scrollbar to appear anytime the window is resized to be more narrow.

I've improved this by *only* restoring the column sizes for the first two columns. Not setting a size on the final column combined with setting the mode to Stretch for just the final column seems to be improving the behavior without needing to mess around with the scrollbar visibility.

The other option I considered was simply hiding the horizontal scrollbar completely. I'm not opposed to that option if the new behavior is still not good enough, but only if we agree that the horizontal scrollbar really isn't necessary. I'm hoping that this new approach is an overall improvement.

Let me know if this is working better as of 1cc6ba053e805ecce6d5b0a2c13f7db020b62abc.

**Comment by davvid** [comment]
> [...] in a dynamically-typed language

I totally know what you mean. I've definitely bumped up against the (performance) limits of Python in this project. I've considered a Rust rewrite (and even a C++ rewrite) and would probably do it if I had infinite time. While it's not on my radar for the time  being, I certainly won't rule it out completely down the line. Curious, which of those two languages would you consider a better option? cheers

**Comment by sthalik** [comment]
If you can start a project that you're going to use yourself, and one which can consist more of trying things out rather than having to finish it then it's good to try out Rust.

Personally I'm postponing learning it. The language is still fresh and is undergoing major changes such as the addition of GATs. Because it's so new it's bound to have tooling or library issues, and I'd be risking getting bogged down in reporting or fixing third-party problems rather than implementing my own project.

To write Rust it's necessary to appease the type system and the borrow checker, which is akin to appeasing the Haskell type checker which is more akin to appeasing the HM type checker in functional langauges. In C++ you don't need to appease anything, you just compute the type you want at compile-time using your own code (so-called partial type specialization along with constexpr). You can [still](https://github.com/sthalik/floormat/blob/master/editor/inspect-types.cpp#L29-L96) [write](https://github.com/opentrack/opentrack/blob/master/options/value-traits.hpp) zero-cost abstractions using declarative syntax.

With time the IDE tooling, platform support, libraries and documentation/educational material will only improve so later I learn it the better, even though I'm missing features such as exhaustive pattern matching, discriminated unions and macros.

**Comment by sthalik** [comment]
Oh, and — Rust doesn't have higher-kinded types. C++ has.
