### ISSUE TITLE
Staging - UI

### ISSUE THREAD

**Issue by MoritzMoreira** [git-cola/git-cola#1434]
It would be nice to have some space between **_Staged, Modified_** and **_Untracked_**. Also the headers could be more different from the files listed.

**Comment by davvid** [comment]
Adding some space between the fields would be nice. I'm not sure if that's possible but we can look into it.

That said, we might be able to resolve this issue as-is because we do have an appearance setting that's relevant, so please try this out.

Navigate to `Files -> Preferences -> Appearance`, enable the `Bold on dark headers instead of italics` setting and then relaunch the app.

If that setting does the trick then we'll go ahead and close this issue.
