### ISSUE TITLE
display something while scanning the filesystem

### ISSUE THREAD

**Issue by grandinj** [git-cola/git-cola#154]
When I first fire up cola on a repo, it is blank for quite a while because the LibreOffice repo is pretty big.

It would be nice if the UI displayed something while it was doing that, so I had some notion that it was not broken :-)

For bonus points, a progress bar would be cool.

**Comment by jalajk24** [comment]
@grandinj i would like to contribute can please assign it to me and drop some insight as i am new to open source??

**Comment by davvid** [comment]
Hello @jalajk24 I can help you if you're interested. I should probably find a good venue for development chat because we'll probably fill up this issue real quick with back-and-forth details (sugs appreciated).

Do you already have a Python + PyQt development environment in place? If so, the next steps would probably be to make add a "loading" notice somewhere (perhaps the status pane) that would start out in the "Loading..." state.

Then when data arrives it can hide itself. We'll need to reset back to the "Loading..." state when switching repos (Cf. the `OpenRepo` class in `cola/cmds.py`).

Most of the updating is handled via Qt signals that are emitted by the main model `cola/models/main.py`. The `cola/widgets/status.py` connects to a number of these signals and responds to them.

Let me know what you think.

**Comment by davvid** [comment]
A fair amount of changes have improved the startup time since 2012 so this might not be relevant anymore.

**Comment by grandinj** [comment]
Yeah, I haven't seen this lately, thanks for all the hard work @davvid
