### ISSUE TITLE
move installation into site-dir

### ISSUE THREAD

**Issue by jlec** [git-cola/git-cola#181]
How about moving the code from /ust/share/git-cola to python's site-dir? This would have the advantage of installing git-cola in parallel for multiple python versions.

**Comment by davvid** [comment]
@moceap and @comzeradd I'm considering going down the path of relying on distutils (or should I use setuptools? got a good exemplary repo to copy?) to install cola's modules, thus placing them in a public location rather than in a private directory at `/usr/share/git-cola/lib` that cola currently adds to its sys.path during startup.

Y'all seem to have most recently dealt with packaging cola on fedora.  If I do this it'll probably mean work for distros when `v3.1` comes around, but it might also mean that packaging becomes simpler since it'll be more akin to normal python projects that provide both scripts and modules.

Can y'all give me a thumbs up or thumbs down on this issue to help me decide whether or not to do it? I've dragged my feet on this issue for a long time to avoid breaking things for packagers. Any debian folks around?

I think we still have an implicit :+1: from gentoo since @jlec submitted this issue, and @cicku maintained the fedora package for a time too, so that's another vote, but I just wanted to check in with the current maintainers before making breaking changes to the packaging.

**Comment by davvid** [comment]
It took a while, but cola's modules are now installed into the standard site-packages directory.

In order to support different use cases, we now provide the cola modules in site-packages alongside the "private modules" (`share/git-cola/lib`) area where we have traditionally installed them.

We will continue to install the private `share/git-cola/lib/cola` package directory, but packagers can opt-out of this by using `make NO_PRIVATE_LIBS=1 install` when installing cola.  The private modules are not needed when the cola modules are available through the default `sys.path`.

Please see the updated [packaging notes](https://github.com/git-cola/git-cola/#packaging-notes) in the README for more details.

This is going to be a breaking change for distro packagers because spec files and scripts will need to be updated to reflect the newly added paths.  Since this requires packaging work, we used this as an opportunity to graduate one of our private scripts to the `$prefix/bin/git-cola-sequence-editor` for general use.  Either of these actions would have required changes to fedora's spec file, which is why we lumped these changes together.

This is unreleased, and will be included in an upcoming `v3.8` release.  I tagged `v3.7` before making any of these changes to give folks a longer runway before these changes land in a tagged release.
