### ISSUE TITLE
Simplify windows installation

### ISSUE THREAD

**Issue by cookacounty** [git-cola/git-cola#247]
Not an issue, more of a feature request.

I would like to distribute git-cola at my workplace but unfortunately it requires installing quite a few dependencies. Could all of these be packaged into one exe?

**Comment by takluyver** [comment]
For another approach, my project [Pynsist](http://pynsist.readthedocs.org/en/latest/) can easily make an installer that includes Python and PyQt. It's also possible to build Windows installers from Linux, which I don't think is possible using Inno Setup.

Bundling git into the installer would be a bit more work, but it should be possible. And even if git was still separate, that's two installers for the user to run instead of four.

**Comment by davvid** [comment]
That sounds like a great idea. I have no attachment whatsoever to current windows deployment setup. It was basically cobbled together from other projects, and since I'm not a windows user, I'm not really dogfooding that part. I just happen to have a crazy old win2k vm that works so I use it to create installers.

Yeah, the current windows deployment setup needs some work ;-) that's not really my area of expertise so I'm always happy to merge patches from people that know more about this stuff than me.

I also hate how I have to touch the nsis scripts to add a subdir every time a new python subdir was added in the code; if pynsist can eliminate that manual step than I'm sold!

**Comment by takluyver** [comment]
Yep, pynsist should make that easy. :-) When I'm back in my office tomorrow, where I have a Windows 7 VM to test things on, I'll have a go at making an installer for git-cola.

In the meantime, here's [the config file](https://bitbucket.org/taxonome/taxonome/src/f044248a401a81d6c7f56922aeb66e7bb3474d3d/installer.cfg?at=default) I use for Pynsist with another PyQt4 GUI application I've worked on. There's an extra step to download and unpack a Windows build of PyQt4 ([described here](https://github.com/takluyver/pynsist/tree/master/examples/pyqt)) - that could be automated if I can work around Sourceforge's download system.

**Comment by takluyver** [comment]
See #421 for a rough idea of what is involved in using Pynsist.

**Comment by c-geek** [comment]
Here is a free project of us which is python and bundles automatically for Windows using AppVeyor: https://github.com/duniter/sakia

We even just added InnoSetup installer, so everything is working out-of-the-box without any third party installation.

Maybe this can help you.

**Comment by davvid** [comment]
I believe this has been resolved already (we're happily using pynsist these days). The next major release is going to support `pip install git-cola` as well (we have an early alpha on pypi already, and you can do `pip install .` as well so I think this should be a non-issue these days.

Thanks again @takluyver 

Sorry if there's some aspect we missed.
