### ISSUE TITLE
Use pygments to do syntax highlighting on top of diff view

### ISSUE THREAD

**Issue by ugtar** [git-cola/git-cola#28]
From the mailing list:
"It would be a super hot feature to syntax highlight diffs using pygments. "
"Optionally, you could use the diff colors as background (light red, light green), and syntax higlight at the same time. "

What if we lighten the red/green background colors, and put the syntax highlighting on top of it. We should probably make the highlighting a preference so it can be turned off.

http://pygments.org/

**Comment by davvid** [comment]
reopening this.. I have a prototype working, I'll push a pygments branch to my fork branch shortly. @ugtar  @living180 I basically adapted the code from [here](http://wayzataresults.com/jheld_downloads/ipython-0.11/IPython/frontend/qt/console/pygments_highlighter.py) and the result was this

![pygments-python-lexer](https://cloud.githubusercontent.com/assets/13196/8717713/c5448c64-2b52-11e5-9a86-88ce0420470e.png)

We might want to choose a better theme (it's using `'default'`, or maybe make that configurable?

But that can't be used as-is, unfortunately.

That first screenshot is using the PythonLexer, which is wrong in general ~ the diff can be any language ~ and it does horrible things to commit messages, etc. but it really does look nice with that python diff.

Here's what happens when we use the pygments DiffLexer

![pygments-diff-lexer](https://cloud.githubusercontent.com/assets/13196/8718063/c738fa48-2b55-11e5-8fd0-da1b1f64a75a.png)

The unfortunate thing is that it relies on a pretty hard-core pygment  monkeypatch to make it work. The current one is good too, and colors the background, not the text, thus it seems to be ok for both dark and light background themes.

I couldn't seem to find the latest code in ipython's git repo, but their [docs](https://ipython.org/ipython-doc/dev/api/generated/IPython.qt.console.pygments_highlighter.html) still mention these classes.. I wonder if they have a newer version we could snarf.

So maybe we can let the user configure the Theme, and they have to opt-in to using pygments (unlike what my branch has, which is all-in).

The Lexer makes me torn. It would be awesome if we could maybe extend this WIP code so that the pygments highlight happens only after we've processed the diff header, or something like that.  It's also just coincidental that the pythonlexer looks ok for the diff.  Ideally, we'd highlight the +/- part and pygments only the text part.

Thoughts?

**Comment by davvid** [comment]
Another note: pygments does not guess the lexer, you must tell it.  We could certainly guess for it based on file extensions since there's only a limited number of pygments lexers, but we might need a facility to force git-cola to use a specific lexer, rather than what it might guess.  The .gitattributes file format could be something we could adopt.. .gitcolaattributes, perhaps?

This is only something we'd need to worry about if we figure out how to  coerce the code into highlighting just the non-diff parts.

**Comment by living180** [comment]
The current version of `pygments_highlighter.py` lives at https://github.com/jupyter/qtconsole/blob/master/qtconsole/pygments_highlighter.py.  It does appear to have at least some changes from the version you used (though I didn't do an actual diff).  The history for the file before it was moved out of the ipython repository can be viewed here:  https://github.com/ipython/ipython/commits/fd4ede243f5073b4a28b76cc15ebfb5ad0c7a10d/IPython/qt/console/pygments_highlighter.py.

As far as this overall feature is concerned, I'm undecided if I would actually use it.  I'm happy to test and provide feedback though.

**Comment by ugtar** [comment]
Hey @davvid, while it is neat to see syntax highlighting in the diff, I think usability-wise, the backgrounded diff colors (what you do today) is the best option.  Unless you could somehow manage to get both the syntax highlighting in *and* the background coloring, but that might cause other issues for visually impaired people because of potentially poor contrast.

**Comment by davvid** [comment]
Thanks everyone

**Comment by sils1297** [comment]
Hi, you might wanna take a look at https://blaxpirit.com/blog/1/diffs-with-syntax-highlight.html , @mr-karan is currently trying to work up something for coala (coala-analyzer.org) so you might be able to reuse that if we succeed.
