### ISSUE TITLE
Cannot load resource files when prefix contains non-ASCII characters

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#307]
### Reproduce steps
1. find a Windows command-line prompt
2. `make; make prefix=軟體\git-cola install`
3. `cd 軟體\git-cola`
4. `python bin/git-cola`
### Console output(partial)

```
Cannot open file 'D:/git-cola/?n??/git-cola/icons:git.svg', because: No such file or directory
Cannot open file 'D:/git-cola/?n??/git-cola/icons:git.svg', because: No such file or directory
Cannot open file 'D:/git-cola/icons:undo.svg', because: No such file or directory
Cannot open file 'D:/git-cola/icons:undo.svg', because: No such file or directory
Cannot open file 'D:/git-cola/icons:git.svg', because: No such file or directory

Cannot open file 'D:/git-cola/icons:git.svg', because: No such file or directory
```
### Reporter's environment
- Windows 8.1 x86 64-bit(version 6.3 (build 9600))
- Python 2.7.7(64-bit x86) is in the %PATH%
- Locale
  - Codepage 950(Big5)
- git-cola
  - commit 4b455208bad4

**Comment by davvid** [comment]
Sorry for the long haul on this issue. We're now solidly on Python3, where unicode is more nicely handled. Similarly, we have since slightly tweaked how the icons are discovered since this issue was submitted.

Please reopen this issue if you're still seeing issues. I want to believe that Python has improved this use case on the road to Python3, but apologies if it hasn't.

Thanks again for your help.
