### ISSUE TITLE
Support Markdown rendering in "Diff" widget

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#340]
Support Markdown HTML rendering if the changed file is a Markdown document.  This is just merely an eye-candy feature request suddenly popped into my mind :-).
## Current behavior

![20140816_002](https://cloud.githubusercontent.com/assets/1192163/3942202/50a63ffa-255a-11e4-9224-edbcd54f1b04.jpg)

**Comment by davvid** [comment]
Newer versions of Qt do have support for Markdown in their text fields but the `+` and `-` diff markers would probably prevent diffs from displaying as expected for various markdown features.

I do like the idea of this but it's probably not entirely straightforward to implement. I'm open to someone trying an experiment but I'm closing the issue since I don't think anyone is going to make any progress on this one.
