### ISSUE TITLE
Support git push --force

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#362]
As issue title

**Comment by davvid** [comment]
We already support this, or at least I think it should effectively do the same thing.  If you uncheck "Fast Forward Only" in the "push" dialog then it will force-push over existing history.

It does it by specifying `+<branch>` as the refspec, instead of the usual `<branch>`, but it has the same effect as specifying `--force`.

e.g. `git push origin +master` does a force-push, but `git push origin master` does a regular, safe push.
