### ISSUE TITLE
Feature request: Check for initialization of Git

### ISSUE THREAD

**Issue by strpeter** [git-cola/git-cola#385]
The GUI is not able to detect if user.name and user.email are initialized. This would be a nice feature as the user is able to create a git folder but cannot commit (no error - just inable to press 'Commit' - at least in Windows) after staging files. As a user it seems not evident that these information were missing.

**Comment by kyanres** [comment]
For the record, there is now an error message (I'm on ubuntu 20.04, inside WSL2) :
![commit without ident](https://user-images.githubusercontent.com/78018441/106789757-f5ac6700-6652-11eb-8349-2c1ac09a7c9e.png)

Ideally, it would be better to inform the user they can use the Preferences menu.

**Comment by davvid** [comment]
Good idea.  Ideally we should prompt users before they try to commit.

I wonder if it'd be too intrusive to check for `user.email` and `user.name` and show a popup with a button to let the user cancel or open the preferences?  (along with a "do not show ask me again" checkbox?)

Maybe we don't need the "do not ask me again" either, since once they set it up git'll be happy.

I'm slightly leaning towards making this a prompt that happens on startup.  Thoughts/opinions?
