### ISSUE TITLE
Feature Request: Checkout Remote Branch

### ISSUE THREAD

**Issue by excaliburHisSheath** [git-cola/git-cola#390]
In git-cola, going to `branch > checkout` only lists local branches. It would be nice if it would also list remote branches and would automatically create a local tracking branch if one doesn't already exist. Currently it seems like the only way to checkout a remote branch through git-cola is to go to `branch > create` and select a remote branch as the starting point.

**Comment by dmccuskey** [comment]
+1

**Comment by djhaskin987** [comment]
I like how git cola tracks very closely with the git commandline. This is one example. Git does not let you actually checkout a remote branch. Instead, when you run "Git checkout <remote>", it figures what you *wanted* to do was create a banch to track a remote branch.

How does git cola even know from which remote you want to track? `git checkout <remotebranch>` only works because git _assumes_ you mean the remote `origin`. What if you have two remotes? What will the branch name be? I don't know if a dialogue other than the current "Create branch" dialog would be useful here.

I think the improvement to make here is to add a menu entry `branch > checkout remote...`, which would pop up the "create branch" dialogue with appropriate defaults set in that dialogue. That way the dialog can more easily present a list of the remote branches and the user would not be confused.

**Comment by davvid** [comment]
very true. These sound like they'd be good improvements.

**Comment by wolftune** [comment]
This answer above seems to misunderstand. It would be nice to be able to do just like in the CLI `git checkout remotename/branchname` which does *not* make a new branch, it puts you in detached HEAD and lets you look at the remote files. Git-cola should support that, and it doesn't right now.
