### ISSUE TITLE
Windows - failed to push when remote branch name contains non-ASCII characters

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#402]
It's possible to name a branch with non-ASCII characters, when I tried to push to such branch git-cola errors with:

```
早就已經是最新版本。

Pushing to https://github.com/NTOUCS-Java-Programming-103-Team-13/youtube-dl-helper.git
fatal: remote part of refspec is not a valid name in ?銝凋蜓閬???development_master):?銝凋蜓閬???development_master)
Unexpected end of command stream
```

The non-ASCII part of the string are garbled.
### Git Cola

2.0.8
### Locale

BIG5(CP950)
### Git

1.9.2.msysgit.0
### Windows

8.1

**Comment by davvid** [comment]
Thanks, this is very interesting. I'll read up on what the "officially supported" branch/ref naming entails and see if we need to limit it within cola, or whether there's something we can do to make this work.  I'm a little bit surprised.

An open question: is it possible that the remote host itself is imposing this limitation? I'll do some testing and see what I can find.

**Comment by davvid** [comment]
What does your branch name look like?  It looks like we create a refspec that is considered invalid -- it's the remote end that's complaining there.  I wonder if we can get the exact command it's running?

Are the names utf8-encoded?  Do they contain parentheses?

The curious part is that all git commands go through the same encoding/decode code paths, so it's odd that this command doesn't work but all the others do.

**Comment by davvid** [comment]
I wonder if windows is converting our unicode branch names into BIG5 encoded strings before execing the underlying git command?  That might explain why it's garbled.  Is the behavior different on python2 vs python3?

In general, using utf8 everywhere is known to work well.  Mixing encodings is troublesome, and there's a limit to what we can sensibly do in python (which has its own terrible unicode semantics between 2 and 3).  I really don't know much about Windows, but hopefully using utf8 is an option.

**Comment by sthalik** [comment]
@davvid there are A and W versions of each win32 call that involves strings. W is for wchar_t while A is for utf-8. You might need to interface with win32 directly through cffi though.

**Comment by kkofler** [comment]
A is unfortunately not for UTF-8, but for the local legacy code page, which is the main cause of this kind of issues.

**Comment by sthalik** [comment]
How about QString::toLocal8Bit then?

**Comment by davvid** [comment]
Back in 2015 we were PyQt4-only, and we were using the old PyQt sip API that actually dealt in QStrings.

These days we're using sip API v2, where QString does not exist, and only native python strings are available to the application.  Is this still an issue?

If so, this might be a shortcoming with python, unfortunately.  Do you what encoding the branch names in?  is it big5?  That can probably break things for cola since it assumes that stuff it's going to read from git is utf-8, and we don't really have any way to configure the "default encoding".

Are you able to push these branches using the git command line interface?  If so there might be something we can do.

**Comment by Vdragon** [comment]
This issue is no longer reproduced in Git Cola 3.1
