### ISSUE TITLE
Editing of commit text inside git-cola rebase

### ISSUE THREAD

**Issue by ptbrowne** [git-cola/git-cola#417]
`git-cola rebase` is awesome ! It would be awesomer (!) if we could edit the commit text inside `git-cola rebase`. I always found confusing that the reword option of `git rebase -i` did not allow edition of commit text inside the $EDITOR (while putting pick etc..).

The way I see it:
- You double click on the commit text.
- The commit text changes into a QLineEdit/QTextEdit with only 1 line displayed.
- If you click outside the input, the input changes back to normal text, bold and with the reword option if changed.
- If text has been edited through `git-cola rebase`, after clicking on Rebase, the commit text should be automatically edited without stopping the rebase process.

I would be glad to contribute to this project by doing a pull request. What do you think ?

**Comment by davvid** [comment]
That would be really cool. It's probably doable, but it'll need some tricks to get it to behave nicely. There's a few gotchas around how git interacts with editors.

We probably don't want to limit the editing to a single line. Commit messages can be many lines in general so it'd be cool if we could reuse the commit message editor widget and use it when editing the message. That'll probably take a fair bit of refactoring (the current widget is probably coupled a bit too tightly with the behavior of the main widget) but should be doable.

The final instruction sheet that we write for `git rebase` still needs to be a single line, so we need to differentiate between the actual message they want and what we write into the instruction sheet.

We probably need to hijack $GIT_EDITOR so that the reword operation runs an editor command we control. The rebase-editor-interceptor can immediately save the output file with the updated message when it sees that we're on one of the commits that was reworded via the GUI.

This implies that we need to stash the messages away somewhere (maybe under `.git/cola/rebase/`) so that we can get them back. There's also the general problem that you can reword multiple messages, but only edit some of them. We need to have our special editor kick in for only those that we've explicitly reworded in the GUI.  Other rewords, where the user actually wants to use their editor, should be handled by executing the editor that would have been run instead.  One way to do this would be to export a new GIT_COLA_EDITOR variable, similar to GIT_EDITOR, that can hold the original value of GIT_EDITOR for use in the "run the user's editor" use case.  We can then override GIT_EDITOR with the interceptor. We'll need to make sure that it's smart enough to know when it should and shouldn't do anything.

The reason we need to use an "editor interceptor" is because `git rebase` is executing us, not the other way around, and GIT_SEQUENCE_EDITOR and GIT_EDITOR are the only hooks we have available for customizing git's behavior.

There's another gotcha.  Once we get kicked back to a shell we are no longer in control, and the GIT_EDITOR overrides that we set earlier will no longer exist since our process has already exited. That might require us to add explicit `git cola rebase --{continue,abort,skip,edit-todo}` actions. This is probably a good idea in general since it makes the cli syntax even more `git rebase`-ish.

These options will need to be special-cased in the `cmds.Rebase` class since the presence of the options means that no other option can be present (`git rebase` enforces that). I'll try and make it so that those options are honored by `git cola rebase` later tonight since that could help later when implementing this topic.

Unrelated to this issue, but I also want to add support for `-x,--exec`, with inline editing.

**Comment by ptbrowne** [comment]
This sounds more tricky than I expected. I do not have much time for the moment :S If I find some, I will try to follow what you wrote but I do not think I will be able to do all this by myself...

**Comment by ptbrowne** [comment]
Maybe instead of hijacking the GIT_EDITOR variable, we can request the user to set it to something like 'git-cola-rebase-editor vim/emacs'.
We could tell the user this when he tries to edit a commit inside git-cola. It could be a first step before finding something where the user does not have to do something.
