### ISSUE TITLE
Feature suggestion: support Save Archive to: tar.xz

### ISSUE THREAD

**Issue by peter1000** [git-cola/git-cola#424]
would be nice if: File - Save Archive would have an entry for saving in: **tar.xz format**

Cheers
P

**Comment by davvid** [comment]
This feature already exists.  It actually existed from day 0 but I didn't realize it when this sug was submitted.  From `git help archive`:

```
       git config tar.tar.xz.command "xz -c"
           Configure a "tar.xz" format for making LZMA-compressed tarfiles.
           You can use it specifying --format=tar.xz, or by creating an output
           file like -o foo.tar.xz.
```

So, I think all you need to do is run:

    git config --global tar.tar.xz.command 'xz -c'

...and your `git archive' will now support creating tar.xz format archives.

Furthermore, because `git cola` queries `git archive --list` for its list of supported formats, this command also adds this feature to `git cola` without any code changes whatsoever.  :+1:

**Comment by peter1000** [comment]
Thanks a lot for the info

P
