### ISSUE TITLE
Installation fails on OSX 10.9.5

### ISSUE THREAD

**Issue by ricardograca** [git-cola/git-cola#434]
Followed instructions. I did not have Homebrew before this so I installed as explained in its homepage:

    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Then I just typed in the commands as on the Readme:

    brew install git-cola

Result:

    Error: Permission denied - /Library/Caches/Homebrew/Formula/git-cola.brewing

The user is admin
Xcode 6.2

**Comment by davvid** [comment]
Hmm, maybe you need to open up permissions? This seems like more of a homebrew issue, unfortunately, and outside my area of expertise. Try poking around in there and see if the paths around there are writeable.

For example, my global `/Library/Caches/Homebrew` tree is owned and writeable by my user, despite it being in a system location.

I believe there's a `brew doctor` command that can print out debugging info, but I'm not sure if it would be able to identify what's wrong.

I actually use homebrew in a very non-official way. I have it installed in `~/src/brew` and symlink its `bin/brew` script into ~/bin/brew`.  This lets me keep `/usr/local` to myself.

brew will then install symlinks in my home directory rather than `/usr/local`, but I have a very custom setup. My setup is upsets `brew doctor` ;-) so I wouldn't recommend it. I've never seen this error before, though.

You could try doing `sudo chown -R $USER /Library/Caches/Homebrew`, but umm, I'm totally guessing! ;-) (but I'm sometimes a very good guesser)  I would expect that if this is happening then any formula, not just `git-cola`, would be having issues.

Did you maybe run homebrew as a different user initially? That would explain why the permissions are wrong.
