### ISSUE TITLE
Support user customizable "Copy <> to clipboard" functions

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#437]
![_497](https://cloud.githubusercontent.com/assets/1192163/7220626/02f66f0e-e702-11e4-8c1b-16baecf0a03f.png)
Hi Git Cola developers, please support user customizable "Copy <> to clipboard" functions so that user can easily customize their prefered "Copy <> to clipboard", for example I could copy `<topic> <separator>` as commit title while reserve the flexibility of which &lt;separator&gt; I prefer(which is not changeable when hardcoded in code), the config UI could be like:
![_498](https://cloud.githubusercontent.com/assets/1192163/7220778/8b3a7c8a-e706-11e4-9585-a7ae1eff0154.png)
(Screenshot from Create Link 0.2.9 Chrome extension)

Thanks in advance!

**Comment by davvid** [comment]
This sounds pretty cool. In this example, would the path itself be the `%text_n%` and then a urlencoded version of the path would be the `%url%`?  Is `%htmlEscapedText%` the same as `%url%` since we only have a path?

Is `%title%` the `Name` column in the table? I'm guessing you have relative paths and you want to add some helpers for formatting these paths.  I guess those variables are just examples. In which case we could leverage the shell syntax and have variables like...

```sh
$basename # the path without directory components
$dirname # the relative directory path
$abspath # absolute path
$url # urlencoded path
$text # urlencoded name column
```
then someone could have `$basename: ` as a configured format. Or, `<a href="$url">$text</a>` or `[$text]($url)`.  Is that what you were imagining?

**Comment by davvid** [comment]
Related-to: #436

**Comment by davvid** [comment]
Related-to: #435
