### ISSUE TITLE
Should share/doc/git-cola/hotkeys.html be automatically generated using Python?

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#442]
Hi Git Cola developers, 
I wonder if its sane to generate hotkeys.html by code instead by manually maintain it since the format is same between different locales?
![_047](https://cloud.githubusercontent.com/assets/1192163/7330475/cdcce0e6-eb21-11e4-85e4-189db6d856d8.png)

**Comment by davvid** [comment]
That could be a doable.  I suppose you're thinking that we can have something like `hotkeys.html.in` in the source tree and then generate the other variants using a template and some python code to load the translations and fill in the template?

That's probably easier to maintain than separate files, that's for sure. This sounds useful, and we can probably hook it into the `python setup.py build` step.

**Comment by Vdragon** [comment]
@davvid 
> I suppose you're thinking that we can have something like hotkeys.html.in in the source tree and 
> then generate the other variants using a template and some python code to load the translations
>  and fill in the template?
Yes, although I originally planned to make webpage generation during *runtime* instead during the build process.

**Comment by davvid** [comment]
That's an even better idea

**Comment by Vdragon** [comment]
That's a performance/storage tradeoff issue, nowadays storage is cheap so lets stick with generating all documents during build-time.

**Comment by davvid** [comment]
After the pain we had to go through to eliminate build-time generation of `.po` files due to the whole python PEP-517/518 build system rework I'm going to unfortunately have to say that we shouldn't really bother trying to do this. It'll be too much of a pain to integrate.

Having a full html file to keep in sync is not ideal, but at least it's just a single file. I like the idea in principle.
