### ISSUE TITLE
Include other OS distros' packaging data?

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#448]
I wonder if it's sane to include packaging data into the upstream source, as distro maintained version usually not reflecting the latest version of Git Cola?

It also made binary package releases possible if we use a method to automate package building.

Any ideas?

**Comment by Mailaender** [comment]
As I said in https://github.com/git-cola/git-cola/issues/449 that isn't a good idea and won't magically update Git Cola on all Linux distributions. You still rely on thirdparty maintainers who need to upload the packaging data onto the distribution repositories. I assume your scripts will be redundant and bit rot pretty fast. You also get zero review if you store them here bypassing the usual package contribution process by the distributors.

**Comment by davvid** [comment]
I build the win32 installer because that platform doesn't have a good package manager, but otherwise it's probably best to let packagers maintain distro-specific packages.

It's already easy enough to upgrade to the latest git-cola without touching the global install.  It's easier to ask users to clone our repo than it is to provide more pre-built packages.
