### ISSUE TITLE
uninitialized diff.tool error message not shown graphically

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#457]
The diff operation will only print following message to stderr and nothing else.

```
This message is displayed because 'diff.tool' is not configured.
See 'git difftool --tool-help' or 'git help config' for more details.
'git difftool' will now attempt to use one of the following tools:
opendiff kdiff3 tkdiff xxdiff meld kompare gvimdiff diffuse diffmerge ecmerge p4merge araxis bc3 codecompare emerge vimdiff
No known diff tool is available.
external diff died, stopping at po/zh_TW.po.
```

**Comment by davvid** [comment]
This is probably because we don't launch git-difftool and block on it, we fork it off in the background.

I wonder if we can improve what that does.  We could instead have a thread launch it, and it could be in charge of capturing stdout+stderr.  When difftool finishes, it can post the message back to the main thread, where it can be displayed to the user.  Good catch!

The `core.fork()` function has always bothered me, especially the windows version. Doing it this way might actually allow us to improve it.  The thing that the fork() function doesn't seem to get right is launching `gitk`..

I was thinking I might be able to simplify it by rewriting each command as sh -c "...." on win32, which will then get things like gitk working correctly since it'll be launched by bash, which understands the `#!/bin/sh` shebangs.

I'd especially like to get this one fixed before the next relese.
