### ISSUE TITLE
[Feature Request] PPA for Ubuntu based distros

### ISSUE THREAD

**Issue by mbnoimi** [git-cola/git-cola#460]
May you please create an official PPA for Ubuntu based distros because building from source whenever you created a new release is very frustrating procedure.

PS.
- Ubuntu repositories always have old version of git-cola
- I found [this PPA](https://launchpad.net/~eraserix/+archive/ubuntu/git-cola) which is somehow older than recent release (2.1.2)

**Comment by Vdragon** [comment]
:+1:

**Comment by davvid** [comment]
If someone steps up to maintain it I'd happily link to it in our docs.

**Comment by davvid** [comment]
This also plays into @Vdragon 's issue to have these built by Travis CI, which would be awesome.

**Comment by davvid** [comment]
Pardon my ignorance (and comment spam).. is it possible to install packages from e.g. debian sid on ubuntu?

I'm just wondering whether packagers can pool resources, rather than duplicating work, since the cola package itself intentionally dependency-free (just python, pyqt + git, essentially) and does not need to be rebuilt across archs.  It's noarch.

I thought ubuntu imports from debian, so contributing to debian seems like the right thing to do. I might be missing something. Maybe this person could just help (or become) the official debian package maintainer. Would that help things?

(note to self: I should probably help debian too)

**Comment by Vdragon** [comment]
@davvid It's possible by [APT Pinning](https://help.ubuntu.com/community/PinningHowto) but it is kind of dangerous operation for traditional, native apps.

**Comment by davvid** [comment]
True, it can be dangerous in general for apps and libraries. It should be safe for git-cola, though, since it's pure Python.  Nonetheless, if a CI or script-maintained ppa makes things easier for users then I am certainly sympathetic to the cause.

**Comment by probonopd** [comment]
@davvid if I see it correctly, then git-cola is already installed to and running on Travis CI these days. Why not [bundle it up](https://github.com/search?utf8=%E2%9C%93&q=%22Package+the+binaries+built+on+Travis-CI+as+an+AppImage%22&type=Code&ref=searchresults) as an [AppImage](http://appimage.org/) for Linux?

**Comment by pavreh** [comment]
PPA with the latest git-cola release:
[https://launchpad.net/~pavreh/+archive/ubuntu/git-cola](https://launchpad.net/~pavreh/+archive/ubuntu/git-cola)

**Comment by probonopd** [comment]
@pavreh can you make one for Ubuntu 14.04 trusty please? It is still a supported LTS version. Thanks!

**Comment by pavreh** [comment]
@probonopd I am afraid not. I created the repository for trusty but an error occured when I was installing the bionic package in trusty. I tried to make trusty package but an error occured because of missing build dependencies.

**Comment by probonopd** [comment]
> I tried to make trusty package but an error occured because of missing build dependencies.

Can the build requirements be lowered so that this application runs on all still-supported LTS versions of Ubuntu?

**Comment by pavreh** [comment]
Done.
There is a [bug](https://bugs.launchpad.net/ubuntu/+source/dpkg/+bug/1730627). Trusty do not accept a deb package with control.tar.xz. The bug was fixed but unfortunately I had still the problem after update.
So I decreased debhelper dependency version and built the package for xenial (it contains control.tar.gz). It works in trusty.

**Comment by et304383** [comment]
Can we please get this?  Need the latest git-cola to fix Control-C being broken.

**Comment by pavreh** [comment]
Done.

**Comment by pavreh** [comment]
The PPA with the latest git-cola release:
https://launchpad.net/~pavreh/+archive/ubuntu/git-cola

**Comment by probonopd** [comment]
Cannot install on trusty:

```
Broken git-cola:amd64 Depends on libjs-jquery:amd64 < none | 1.7.2+dfsg-2ubuntu1 @un uH >
  Considering libjs-jquery:amd64 1 as a solution to git-cola:amd64 9999
  Re-Instated libjs-jquery:amd64
Broken git-cola:amd64 Depends on libjs-underscore:amd64 < none | 1.4.4-2ubuntu1 @un uH >
  Considering libjs-underscore:amd64 1 as a solution to git-cola:amd64 9999
  Re-Instated libjs-underscore:amd64
Broken git-cola:amd64 Depends on libjs-modernizr:amd64 < none | 2.6.2+ds1-1 @un uH >
  Considering libjs-modernizr:amd64 1 as a solution to git-cola:amd64 9999
  Re-Instated libjs-modernizr:amd64
Done
```

**Comment by jm4R** [comment]
> The PPA with the latest git-cola release:
> https://launchpad.net/~pavreh/+archive/ubuntu/git-cola

Could you please update it to 3.3 ?

**Comment by axel-h** [comment]
Seem this has been abandoned last update says "134 weeks ago"

**Comment by LightTemplar** [comment]
May it be opened again, as there is no actual PPA again?
