### ISSUE TITLE
windows, file notification causes dag to refresh all the time

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#480]
With pywin32 installed for notification support, building with "make -j4" causes dag to relaunch git, refill the commit list and reset the selected line position back to the first commit.

Note, the build directory is ignored by .gitignore and none of the files in it are tracked by git.

**Comment by davvid** [comment]
I made it so that we remember and restore the selection, but it sounds like maybe we can improve things some more.  This was not a windows-specific issue (the selection part, at least).

It's curious that you noted that all of your files are .gitignored.  I do not observe that behavior on linux.  @kbielefe any thoughts?

**Comment by sthalik** [comment]
Sadly this doesn't work. The list becomes empty for split second, then newest commit becomes active.

**Comment by sthalik** [comment]
Other than the flicker and #477 (Popen doesn't hide window) it works, thanks!
