### ISSUE TITLE
Bug when initializing application?

### ISSUE THREAD

**Issue by djhaskin987** [git-cola/git-cola#495]
I found what looks like a bug in the code [here](https://github.com/git-cola/git-cola/blob/master/cola/app.py#L350):

```
def new_application(args):
    # Initialize the app
    return ColaApplication(sys.argv)
```

The code doesn't use `args` to initialize the cola application; rather, it just short circuits the parsing of arguments entirely and uses `sys.argv`. Is this a known workaround or bug?

**Comment by Vdragon** [comment]
I believe it's just by design not needed, though I don't speak Pythonese.

**Comment by davvid** [comment]
It's by design.  Here `args` is the parsed command-line, which in an earlier version of the code was used, but is no longer so. I still want to keep it here since I can't predict the future, where some new command line flag is added and this part of the code would need to use `args`.

`sys.argv` thing is for Qt, which uses the raw unparsed command line for its own purposes (e.g. the x11ish `-geometry` flag that qt apps get by default).

I guess we don't really need that function anyways as it's a one-liner, but earlier that was the place where special initialization-related code lived.  I still want to refactor the code the eliminate all globals.  In the future I imagine that most of those would be moved into local app-specific objects created in `new_application()`, which is probably why it's still there ;-)
