### ISSUE TITLE
git-cola takes long to start on very large repos

### ISSUE THREAD

**Issue by jlec** [git-cola/git-cola#499]
Please checkout `https://anongit.gentoo.org/git/repo/gentoo.git` and start `git-cola`. it takes very long, where as a simple `git status -v` or similar is fast. Perhaps some optimizations can be done here.

**Comment by davvid** [comment]
Taking a closer look, here's a guess.  Do you have `cola.browserdockable` configured to `true`?

That option is opt-in because having the File Browser as a dockwidget makes it slow to startup since it'll spend a bunch of time looking up the last latest commit message and modfication time for every file in the repo.  Startup time is decent when `cola.browserdockable` is turned off.

It's a nice feature, but when dealing with larger repos this stuff starts to become a drag.  We don't have a fast way in Git to ask for the author, most recent commit message, and date for every file in the repo without querying each file individually, so the File Browser tool does just that.

The operation is O(N) for the number of files in the repo, so being able to shut off the message/author/date feature in exchange for performance seems like a good trade off.  We can add a `cola.fastmode` config knob to enable this mode.

It may be possible to defer updating the browser details until after the widget is shown, which we'll do as well.  Let me know if my hunch about the browser setting is on the right path.

**Comment by davvid** [comment]
I've reopened this issue to track optimizations we want to do and link other performance-related issues to it.

Please see the notes in the linked issues for related issues and ideas.

**Comment by davvid** [comment]
Since 2015 (and more recently) we've offloaded a lot more of the startup sequence to background threads and minimized the git calls that we perform to query data. I think this issue can be closed now, since the startup time has much improved since this was submitted.

The upcoming v4.0.2 release will contain these optimizations.

There's still stuff that could be offloaded to background tasks that we'll continue pushing on, but they're not part of the startup sequence so this issue can be considered complete now.

 Thanks again @jlec for the report.
