### ISSUE TITLE
Usability: Remember repository

### ISSUE THREAD

**Issue by Zeioth** [git-cola/git-cola#513]
Hi, it would be nice to have an option to do not be prompted for which repository do you want to open when you open git-cola, and instead remember the last repository I opened. I have a keyboard short cut for git-cola and it's very annoying to be asked for it every time I open it. Thank you.

Also, when you open git-cola, the last repository you opened should be marked and be opened after press enter.

**Comment by davvid** [comment]
Adjust the command the keyboard shortcut runs to include the `--repo path/to/worktree` argument.  and cola will not prompt.  cola will start in that worktree.

The default behavior is actually not to  prompt when cola finds a git repository in the current working directory. It only prompts when nothing is found, or the `--prompt` option is specified.

Likewise, if the working directory is changed before launching cola then the `--repo` option can be omitted.  If the shortcut has a working directory options then changing that would also do the trick.

What are you using for the shortcuts stuff?  Sounds interesting...  If its mapped to some default system menu item, then it's probably the git-cola.desktop file in /usr/share/applications/.  Tweaking that one adjusts the action that's run in the menu launcher.

**Comment by davvid** [comment]
That said, I think I just about finished implementing this feature.  I can see it being useful to have a way to tell cola to check one last directory before falling back to the prompt dialog.

I've made it so that you can right-click in the Bookmarks widget and set one of the repos to be the "Default Repository".  I'm always hesitant to add new features, but if this is useful to others too then I can be persuaded.

I'll push what I have to a "default-repo" branch and we can see what others think.

**Comment by Zeioth** [comment]
Also, it would be great to have the same feature in git-dag in the future. Thank you so much davvid, i think that will do the trick perfectly. 

By the way my system shortcuts are:
cmd+A: Open git-cola
cmd+S: Open git-dag

**Comment by Zeioth** [comment]
I just installed git-cola from your last commit and i can confirm it, it's a great usability boost.

**Comment by davvid** [comment]
dag+cola reuse a lot of code, so it got it for free, they both share this feature.  Thanks for testing.
