### ISSUE TITLE
pywin32 notify during build makes dag refresh all the time

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#516]
With pywin32 for notify support, `make -j4` makes the `git dag` blink all the time. `dag` feels the need to refresh commit list on changes to gitignored build directory.

**Comment by living180** [comment]
Can you report which git-cola version you are using?  My unreleased changes to the filesystem notification code should hopefully help alleviate this problem, as it now avoids refreshing until it has not detected any filesystem activity for at least 888ms (previously upon detecting filesystem activity, it would wait 888ms and then refresh, even if there had been more filesystem activity in the interim).  However, as I just commented in issue #517, an additional improvement would be to not refresh at all if the file in question is ignored by git.

**Comment by sthalik** [comment]
For the case of DAG, unless dot.git gets refreshed should be more precise, yes? DAG doesn't care about uncommitted changes.

**Comment by living180** [comment]
Ah, yes.  I don't really use `git dag` but it makes sense that it doesn't need to refresh the way the status browser does.  I'll need to look at a way to make sure filesystem monitoring doesn't affect the DAG.  Thanks for reporting.

**Comment by living180** [comment]
@davvid, @sthalik  Do you think it makes sense to have `git dag` auto-refresh on new commits?  Trying to decide whether to use more limited filesystem monitoring for `git dag` or to disable it altogether.  Since I don't really use `git dag`, user input would be helpful.

**Comment by sthalik** [comment]
@living180 it could be refreshed on any new commit, branch, rebase, or tag change. These changes are rare enough to warrant no additional processing. Note the commit-ish selector in dag that can point at anything.

**Comment by sthalik** [comment]
@living180 a simpler option would be to use Nagle's algorithm for notify refreshes in `git dag`.

**Comment by davvid** [comment]
@living180 refreeshing on new commits or branches would be pretty cool, but maybe there's some things that can be tweaked project-side to make it more amenable.

If "make" is triggering refreshes then that suggests that the directories where file creation/modification is happening is inside a directory that is not ignored.

If you don't want git-dag refreshing then one way to make that happen is to add that directory to your .gitignore.  That's the first thing to try to do.  Possibly re-arranging the directory structure to place non-source files in a .gitignore-able subdir would help since we would no longer be watching items inside that directory.

For example, In the git-cola project we can do `make && rm -rf build/scripts-*` in a loop and git-dag will not refresh.  This is because we have `/build`in .gitignore.  But, there are still situations where the file being created is adjacent to a tracked file, so maybe we can do something to make that less painful.

@sthalik, if I'm understanding your Nagle reference correctly then you are suggesting that fsmonitory/inotify refreshes should be throttled so that they don't happen too often.  That's a great idea ;-) it actually already works that way, but our interval is rather short.  I can imagine that maybe someone might want to crank this number up to something much higher if it makes their workflow smoother.  Here's where the throttle is currently defined:

https://github.com/davvid/git-cola/blob/master/cola/fsmonitor.py#L75

I can see it being useful to make that a configurable run-time thing.  `git config cola.updateinterval` or something like that.

The only downside is that we won't see new files appear in the untracked file list until after the interval expires, but it would help avoid this papercut.  What do you all think?

**Comment by sthalik** [comment]
@davvid the build subdirectory is ignored and doesn't appear on Cola's untracked files list either.

The Nagle in this case is to ignore idempotent changes until they no longer come, and fire the signal after the last of them.

To my understanding none of the tracked project files change during the build process, only contents of the latter.

**Comment by sthalik** [comment]
What should optimally be done is filter out everything but `.git/*` changes and ignore in dag for the purposes of commit list changes.

**Comment by sthalik** [comment]
@living180 @davvid unfortunately there are refreshes in cola dag while compiling. `.git/index` is untouched for days or more. This is on Windows.

**Comment by living180** [comment]
@sthalik sorry it has taken me a bit to look at this.  Although I don't normally use `git-dag` (just `git-cola`), I do use Windows as my dev environment.  I haven't been able to trigger refreshes in `git-dag` through any sort of filesystem changes in the worktree.  (FWIW, `.git/index` changes shouldn't trigger refreshes either - just changes to `.git/HEAD` or anything under `.git/refs/`).

I'm happy to try to help figure this out - can you give me more information about your system/setup so we can figure out what is going on?

**Comment by living180** [comment]
@sthalik - I just stumbled upon a way to reproduce this.  When running `git-dag` by itself, the problem is absent, but when choosing `View -> DAG...` from within `git-cola`, I see what you reported.  I'll need to change my approach to handle that case.

**Comment by sthalik** [comment]
@living180 thanks for the continued interest. Ping me when you need to test something.

**Comment by living180** [comment]
@sthalik if you want, you can try the [fsmonitor_check_ignore](/living180/git-cola/tree/fsmonitor_check_ignore) branch in my fork and see how it does for you.  I'll be testing it a bit for myself and if everything looks good will submit a PR.

**Comment by sthalik** [comment]
@living180 I get no refreshes at all during `ninja install`. On the other hand `git checkout HEAD^^^^^` results in no automatic update to DAG.

**Comment by sthalik** [comment]
@living180 with pywin32 I get a refresh when HEAD changes, No refreshes during build. All is fine.

**Comment by sthalik** [comment]
@davvid @living180  please consider merging. The rebased version of this build works great after all the time.

**Comment by sthalik** [comment]
Here's my rebase for cola master: https://github.com/sthalik/git-cola/commits/fsmonitor_check_ignore

**Comment by davvid** [comment]
I'm on vacation right now so I haven't had a chance to get back to this but I do want to merge this topic.  @living180 would you mind opening a PR so we can merge this?  If you're busy I won't mind taking @sthalik 's rebased version

**Comment by sthalik** [comment]
@davvid thanks for merging this. I can confirm that modifying staged files, adding and removing files all work with cola following the rebase and the last commit of the series.
