### ISSUE TITLE
How to add submodule?

### ISSUE THREAD

**Issue by mbnoimi** [git-cola/git-cola#534]
Hi,

I search in the git-cola docs but unfortunately I couldn't find any mentioning for adding submodules.

How can I add submodule using git-cola?

**Comment by Vdragon** [comment]
Me too, probably not implemented yet.

**Comment by davidkhala** [comment]
Will there be any update on this missing features?

**Comment by davvid** [comment]
Unimplemented but I'll take patches.  I'll be getting to the current PR queue later this week.  This issue can stay open until it's implemented.

**Comment by mbnoimi** [comment]
Is there any progress on this issue?

**Comment by davvid** [comment]
Hot off the presses!  Thanks for the sug @mbnoimi -- please test it out if you can.

**Comment by mbnoimi** [comment]
> Hot off the presses! Thanks for the sug @mbnoimi -- please test it out if you can.

Thanks @davvid it works fine but I prefer to add check box for adding submodules recursively.

**Comment by davvid** [comment]
@mbnoimi according to the Git documentation:

```
--recursive::
        This option is only valid for foreach, update, status and sync commands.
        Traverse submodules recursively. The operation is performed not
        only in the submodules of the current repo, but also
        in any nested submodules inside those submodules (and so on).
```

`git submodule add` does not support `--recursive`.  Submodules are really only registered one level deep, which is why `--recursive` may not make sense as an option for that sub-command.  Nested submodules are not registered in the super-project.

I'm not sure if this is what you were suggesting, but one possibility would be to change all of our `git submodule update` usage to always include the `--recursive` flag.  Recursive updates would probably hit the 90%+ use case, so it seems like a sensible default.

Please let me know if I'm missing anything, and let me know what you think about changing the `git submodule update` behavior.  Thanks again!

**Comment by mbnoimi** [comment]
@davvid Yes I agree with you, modifying `git submodule update` is the right choice.

**Comment by davvid** [comment]
Thanks for the sug, `--recursive` is now used when available.
