### ISSUE TITLE
.gitignore management

### ISSUE THREAD

**Issue by paulhildebrandt** [git-cola/git-cola#553]
Great Tool!   Any plans or interest to add .gitignore management?  Things like:
- Creating one if not there
- Adding acceptable defaults such as vi or emacs tmp files
- Ability to add a new file to the ignore by name or pattern
  If there is interest I can mock something up.

**Comment by Vdragon** [comment]
Git Cola already supports adding specific file path into .gitignore, but is not customizable to ignore specific pattern.

**Comment by davvid** [comment]
Thanks Paul, it looks like we already have the ability to add untracked paths to .gitignore with minimal fuss. The right-click "Ignore" action also lets you add custom patterns so I think we're good as far as that feature goes.

For personal settings like editor-specific ignore patterns then I would probably suggest using something like `git config --global core.excludesfile ~/.config/git/ignore` and adding editor exclusions in a global personal excludes file.

https://git-scm.com/docs/gitignore#_description (see `core.excludesFile` there for more details)

That's a nicer approach because projects don't have to carry around editor-specific cruft and the settings take effect in all repos.

It might not hurt to offer some common language-specific presets, like ignoring `/build`, `/env*` for python projects or `/target` for Rust projects, and have them easily accessible from the same "Ignore" dialog in case someone wants to take a stab at that.
