### ISSUE TITLE
mac os brew install git-cola not ok

### ISSUE THREAD

**Issue by zb188** [git-cola/git-cola#559]
➜  ~ brew install git-cola
Warning: git-cola-2.4 already installed
➜  ~ brew uninstall git-cola
Uninstalling /usr/local/Cellar/git-cola/2.4... (142 files, 1.2M)
➜  ~ brew install git-cola
Error: You must `brew link qt` before git-cola can be installed
➜  ~ brew uninstall qt
Uninstalling /usr/local/Cellar/qt/4.8.7_1... (2794 files, 121M)
➜  ~ brew install git-cola
==> Installing dependencies for git-cola: qt
==> Installing git-cola dependency: qt
==> Downloading https://homebrew.bintray.com/bottles/qt-4.8.7_1.el_capitan.bottle.tar.gz
####

**Comment by davvid** [comment]
I just tried `brew install git-cola` from a fresh OS X install and it seemed to work fine.

Perhaps the hassles `brew` was giving you above were mainly related to there being an older version installed, and it needed you to get it over a packaging bump?  Bummer.

Anyways, closing this for now since things seem to work fine for me on a fresh Yosemite OS X install.  Maybe the quirks you ran into can be reported to the homebrew project so that the tool can help make it easier?

e.g. maybe they can add a new mode, `brew install --force-reinstall git-cola` and it'll take care of doing the whole uninstall/reinstall shuffle for you.

Let me know if there's anything that's not working.
