### ISSUE TITLE
`git-cola` does not cleanup after itself.

### ISSUE THREAD

**Issue by envygeeks** [git-cola/git-cola#566]
After running git-cola on several directories over a period of a few days, I have well over 20 temporary directories in my `/tmp` folder because `git-cola` didn't cleanup after itself when it was told to exit. This might be related to me launching it with `git cola` and then doing a C-c on it when I'm done (but personally I don't think that should matter.)

Note: They all seem to be empty, so maybe it is trying to cleanup just the parent is not being removed?

**Comment by Vdragon** [comment]
I wonder if the temp folder removal can/should be implemented in the interrupt signal handler instead, then the temp folders will only be preserved when the process is killed (but not when it is interrupted, such as using the Ctrl-C keystroke)

It'll prevent repeatedly cleaning up the temp files(less code being run?), and also solves this issue...?

**Comment by davvid** [comment]
@Vdragon I tried that first, but adding a custom handler has strange behavior in pyqt. Instead of immediately exiting like `signal.SIG_DFL`, the shell shows `^C` but nothing happens until you give focus back to cola and then the custom signal handler finally runs.

I think I can even do away with the need for a tmp directory period, then we don't need to `rmtree`, just `unlink` for each temp file.
