### ISSUE TITLE
Improve compatibility with dark themes

### ISSUE THREAD

**Issue by itaranto** [git-cola/git-cola#568]
Tested using KDE Plasma 5 with the Dark Breeze theme, icons and diff screens are difficult to read.

![screenshot_20160501_165747](https://cloud.githubusercontent.com/assets/11463919/14944009/664f4310-0fbe-11e6-9027-8ed5fa0bc2d1.png)
![screenshot_20160501_165813](https://cloud.githubusercontent.com/assets/11463919/14944010/6a54de34-0fbe-11e6-8270-fa591b856ffc.png)

**Comment by davvid** [comment]
For the diff screen we do have a way to configure the color. I agree that something could be done about the icons.  One idea is to have an alternate "icon set", but I'll let the idea stew for a bit in case others have good ideas. Ideally it'd be nice if we could swap the icon color without needing a separate svg file.

Here are the config knobs for changing the diff colors:

http://git-cola.readthedocs.io/en/latest/git-cola.html#cola-color-text

I'd very much welcome any changes that help improve the situation for dark-theme users.

**Comment by davvid** [comment]
I think this is mostly solved by any of the following these days:

- option: `git cola --icon-theme=dark`
- git config: `git config --global cola.icontheme dark`
-  environment variable: set `GIT_COLA_ICON_THEME=dark`

**Comment by guoyunhe** [comment]
Just have another idea for the automatic dark/light theme support (in Linux). All Linux distributions have two basic icon sets: hicolor (fallback for light theme) and locolor (fallback for dark theme). If you install icons into system icon folders `/usr/share/icons/hicolor` and `/usr/share/icons/locolor` and load icons by icon name instead of file path, then Qt can load the right icon for current desktop theme.
