### ISSUE TITLE
Feature: patch queue management

### ISSUE THREAD

**Issue by lkraav** [git-cola/git-cola#571]
Ever since discovering `stgit` http://procode.org/stgit/, I really don't enjoy manually rebasing and amending feature branches anymore. Things like `stg refresh -p some-older-patch-name` is just super convenient and fast.

What are the developers current thoughts on patch queue management functionality for `git-cola`?

**Comment by davvid** [comment]
I think that could be a good feature to add. I would need a little bit of guidance as to what the user experience should be like since I don't personally use stgit, but I would be open to trying it out.

Another meta-question -- is stgit actively developed?  I guess actively developed is not as important as stable and well-maintained.  @ctmarinas what are your thoughts on having tools integrate stgit?  Is stgit a project that will be actively maintained, or should we consider alternatives?

I would also like to note that we do have support for adding custom "guitool actions" that can be invoked from cola. There may be a few of these features that can be implemented as "git config"-driven actions, perhaps as a prototype.

http://git-cola.readthedocs.io/en/latest/git-cola.html#custom-gui-actions

**Comment by davvid** [comment]
Related: #1261 added support for `git cola --update-refs`, which helps a bit with stacked branch workflows.

`git cola rebase --update-refs` is now supported as well. The UI will prompt and ask whether related "stacked" branches should be updated during a rebase.

I think we can close this issue for now. If someone has concrete suggestions for stgit or other workflows to support then it'd be helpful to spec that out.

For now, I think the `--update-refs` feature should be helpful for stacked branch workflows. Git v2.38.0 is required to unlock this feature.
