### ISSUE TITLE
Support for //GIT_DO_NOT_COMMIT at line level inside a file

### ISSUE THREAD

**Issue by RaghavendhraK** [git-cola/git-cola#602]
Like the gitginore, which ignores at file level, we need a support in the cola git, which can omit the lines under some predefined sections like GIT_DO_NOT_COMMIT, so that we can have these lines in our local, but ignored while committing/pushing/pulling the code.

**Comment by davvid** [comment]
Hi, git-cola can't currently support this feature because it's not supported in core git.  We could try to do something fancy in our diffparse  / patch generation code, but I think it might make the even more complex than it already is.

If core git were to add this feature then we can make cola exploit that core feature.

The best place to ask is on the git developer mailing list `git@vger.kernel.org` or their irc channel. Someone there might suggest that you can accomplish this today using `.gitattributes` and some custom smudge/clean or textconv filters, and that core git doesn't need a new feature because it already can accomplish it using a gitattributes.

I also wouldn't want a halfway implementation that only touches the interactive staging tool. The reason is that the behavior then becomes inconsistent with what happens when you press Ctrl+S to stage the entire file (which just uses `git add`) as core git does not understand these markers.

You're kind of asking for something that is against the very nature of Git itself, so it probably doesn't make sense for cola to handle it.
