### ISSUE TITLE
use repo realpath

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#610]
On Windows, Cola shows recent repositories' dirname as both `c:/users/sthalik/dev/` and `d:/dev`. I use directory symlinks/junctions.

Can repository's realpath be tried unless it fails?

**Comment by living180** [comment]
Unfortunately realpath() on Windows is just an alias for abspath(). I've submitted some patches to actually implement realpath() on Windows for Python 3 but they've never gone anywhere and I haven't had sufficient motivation to push them forward.

**Comment by Vdragon** [comment]
This bug I presume: [Issue 9949: os.path.realpath on Windows does not follow symbolic links - Python tracker](http://bugs.python.org/issue9949)

**Comment by sthalik** [comment]
@living180 is it acceptable to add it to cola's util module? I can write the logic, no worries.

**Comment by living180** [comment]
@sthalik - I'm fine if you want to use any of the code wrote for Python Issue 9949.  It did require some C changes, but I think that was because the general case requires handling corner cases like paths that contain broken symlinks in the middle, which doesn't apply here because we know that any symlinks in the repo path resolve to an actual path.

I also know of at least one other project that has written a pure-Python implementation of `realpath()`, which it might be possible to incorporate if there are no licensing issues:  https://github.com/jbernard/dotfiles/blob/v0.6.4/dotfiles/compat.py.  I'm sure there are others as well.

**Comment by sthalik** [comment]
@living180 the latter's license is simple ISC - see <<https://github.com/jbernard/dotfiles/blob/v0.6.4/LICENSE.rst>>.

**Comment by davvid** [comment]
I don't have a way to test this but os.path.realpath seems to already have been fixed in newer python versions.

I'm closing this issue but if this isn't actually fixed then I'll still happily accept a pull request to improve it.
