### ISSUE TITLE
git-cola.github.io: Support I18N

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#635]
I'll be willing to translate <http://git-cola.github.io> as long as it is possible, please support I18N of the website

**Comment by davvid** [comment]
This would be great.  I'm open to any sugs on how to go about it.

It seems like the most common ways to do this are these projects, each of them different.  These are the ones I found:

- minimal approach without any plugins
  https://www.sylvaindurand.org/making-jekyll-multilingual/
  https://github.com/sylvaindurand/jekyll-multilingual

- jekyll plugin
  https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin

- octopress's multilingual plugin
  https://github.com/octopress/multilingual

- another plugin
  https://brendamour.net/en/2014/08/03/multilingual-jekyll-how-to-post-in-more-than-one-language/
  https://github.com/drallgood/jekyll-multilingual


I don't know if any of the plugin solutions would work with github pages as-is. They might require that we pre-generate all of the content, which is not out of the question, but it would be nice to avoid that.

The no-plugins approach is appealing since making contributors and translators deal with the additional ruby/gem/bundle jekyll workflow might be something we'd like to avoid.

We should choose carefully between these (or other) options and then migrate the site over.  Whatever works best for translators is probably what we should do.  Do you have any thoughts or opinions on how we should do it?

**Comment by davvid** [comment]
another simple way to do it might be to simply have "_${LANG}.html" variants of each of the pages, and then we can internally link to the different languages.  There'll probably be a bit of copy/pasted markup between the html files (like we currently have in the translated hotkeys html) but it works and is simple.
