### ISSUE TITLE
"Amend commit" feature accessibility(prev: Feature Request: Amend a commit)

### ISSUE THREAD

**Issue by TimSchumi** [git-cola/git-cola#640]
Please add the possibility to amend a commit.

If this feature already exists, then make it easier to access. At least I did not find it.

**Comment by davvid** [comment]
Ctrl+M (or Cmd+M on Mac OS) in the Commit Message Editor will switch to Amend mode.

There's also a checkbox in the Option drop-down sprocket menu next to the left of the Commit Summary input field.

**Comment by Vdragon** [comment]
Refer screenshot, this feature is already implemented.
![_086](https://cloud.githubusercontent.com/assets/1192163/21673067/8909f078-d361-11e6-8aee-eed7b7c726ec.png)

Maybe we should move the feature to the commit menu

**Comment by TimSchumi** [comment]
Or like it's in git-gui (if we have enough free space for that). Just add in two radio buttons:
1) New commit
2) Amend commit

**Comment by davvid** [comment]
Thanks for the sug.  I think we can add it to the `Commit` menu since that's a nice, logical place for it, and I suspect that others who go hunting for this behavior will be able to discover it there.

I'd prefer not to add extra radio buttons/UI elements for this since it's kinda ugly and we already have a more-convenient `Ctrl+m` hotkey for it.
