### ISSUE TITLE
After window maximisation, git-cola hangs with no display.

### ISSUE THREAD

**Issue by Parashurama** [git-cola/git-cola#641]
As title said, I am unable to use git-cola, if **gui_state.mainview.maximized** is **true** in .config/git-cola/settings with latest **master**. 
The program launch just fine, but hang with no visible window. 
Also deleting settings file restore default settings, but the problem comes back as soon I quit the window and relaunch.

After git bisecting, I think I found the problem in 5b7b85a918ee17092cd01c2. 
Any commit before works fine for me.

OS: Lubuntu 16.04 64bits

**Comment by Coacher** [comment]
So this is what causing these hangs! @Parashurama, thank you very much for getting to the bottom of this. I can also confirm this behaviour with python-2.7 or python-3.4 and the current master @ e38a026. OS Gentoo amd64.

Steps to reproduce:
1. Wipe `~/.config/git-cola` directory.
2. `cd` into any git-repo
3. Execute `git-cola` (git-cola window opens as usual).
4. Maximize window and close git-cola.
4. Execute `git-cola` again.

Expected results:
git-cola window opens again.

Actual results:
git-cola window doesn't appear. No errors are printed in terminal. In terminal I see `$ git-cola` indefinitely. Nothing related in ~/.xsession-errors.

Please fix, this is very annoying.

**Comment by davvid** [comment]
I'm picking this up now, thanks for the heads-up.

The changes that were made for handling the maximization was implemented by a Windows tester, so I suspect that we can make it behave correctly by special-casing Windows to use the current code path and then let the rest (Linux, Mac OS) use the older code path, which did not have this problem.

I wonder if I should special-case both Windows and Mac OS, and only restore the old code path for Linux?  I'm going to go down that route for now unless we hear from Mac OS users that are also experiencing this issue until I have some time to test it on Mac OS as well.

The next release will not be tagged until this issue is fixed.

**Comment by Coacher** [comment]
I can confirm this is no longer reproducible with the current master @ 4d76169e4dc27.
Thank you for the fix!
