### ISSUE TITLE
Creating branch - starting revision issue

### ISSUE THREAD

**Issue by nickdtodd** [git-cola/git-cola#667]
Hi,

I'm getting the following error when trying to create a branch and setting the starting revision:

```
[nick@manjaro-desktop ~]$ git-cola
qt5ct: using qt5ct plugin
Traceback (most recent call last):
  File "/usr/share/git-cola/lib/cola/widgets/completion.py", line 323, in paint
    rect = style.subElementRect(item_text, params)
TypeError: subElementRect(self, QStyle.SubElement, QStyleOption, QWidget): not enough arguments
Aborted (core dumped)
```

Git-cola version: 2.8
Manjaro: 16.10.3 (64 bit)
Xfce desktop: 4.12
Linux: 4.4.48-1-MANJARO

Many thanks,

Nick.

**Comment by nickdtodd** [comment]
Update:

I upgraded to 2.10-1 and it is still happening.

**Comment by Vdragon** [comment]
This appears to be [Qt-related](https://www.google.com.tw/search?q=subElementRect), it would be helpful if we know the version of Qt/QtPy/PyQt(4) your using.

**Comment by nickdtodd** [comment]
Hi,

I'm running:
Qt: 5.8.0
QtPy: 1.1.1
PyQt5: 5.7.1

No reference to PyQt4

Thanks, Nick.

**Comment by davvid** [comment]
This is technically a bug in pyqt since it should never segfault, but I have a change that I think should avoid the problem. I'll push a fix shortly; please test it on your version and let me know if it works.

I don't have Qt 5.8 onhand for testing so please report this upstream. From reading the Qt docs, the `widget` parameter is still optional in Qt 5.8, so this is possibly a PyQt5 bug when using Qt 5.8 since it should allow us to omit it.

In any case, please test out the fix once I push it up and let me know if it works for you.
