### ISSUE TITLE
date column in dag is truncated

### ISSUE THREAD

**Issue by sthalik** [git-cola/git-cola#674]
Hey,

The commit date column is truncated on my end. Furthermore, I'm unable to persist the column resize unless making the graph smaller. My date format includes the day of week, like so:

> Wed Mar 22 03:38:11 2017 +0100

Could you resize the column to fit on dag startup, please? It can be as simple as making a sample date and `QFontMetrics` width and multiply by `1.25` or some other coefficient.

sh

**Comment by davvid** [comment]
in the tree widget's add_commits() if it does `self.resizeColumnToContents(2)` it'll roughly do what you want, but it then ends up truncating author names.

Both author names and subject lines are arbitrary length, so resizing to their content width isn't that great either.

Is the root problem that any manual adjustment is not persisted?  It might be better to just remember the header widths and restore them instead of special-casing the date column.

FWIW, manual resizing does seem to persist fine in-session. It's just lost when restarting.

Also, if you hover your mouse on the right-most part of the date column, next to the scrollbar, you can actually grab it there and resize the date column wider so that it's not truncated.  Is that what you mean by "unless making the graph smaller"?

Once I resize the header by dragging the right side outwards to the right, the scrollbar on the bottom expectedly increases in size since we've now made the table data wider.

Does the resizing work for you as-is, or should the header widths persist across sessions, aka stored in `~/.config/git-cola/settings` ?

**Comment by davvid** [comment]
We now remember the column sizes across sessions.

**Comment by sthalik** [comment]
It works fine except for the initial position. Starting from an old config, the first two columns are very small and the date column is stretched over the entire screen.
