### ISSUE TITLE
Text entry commit summary/description is laggy when docked

### ISSUE THREAD

**Issue by eliao** [git-cola/git-cola#677]
Using git-cola 2.5 on ubuntu, x-forwarding to Mac.  

Just started using git-cola and it seems promising.  The one hangup I have is that text entry for commit messages is extremely laggy.  I'll type in text and there is a noticeable delay for it to appear.  

Interestingly, this delay does not occur if I "pop out" the commit subwindow to its own window.

**Comment by davvid** [comment]
That's probably the nature of macos' X11 implementation, and x11 in general.  It's not laggy at all when running locally, as I'm sure you've noticed if you launch it from ubuntu or macos natively.

The "pop out" thing can be explained by x11.  Instead of having to send drawing commands for the entire git-cola window, only the commit editor is drawn, which will be less data over the network.

I think the "NX" servers and clients might be what you'd need to make it snappy.  Run the server on ubuntu and the client on macos.

- https://en.wikipedia.org/wiki/NX_technology
- http://wiki.x2go.org/doku.php/doc:newtox2go
- http://wiki.x2go.org/doku.php/doc:installation:x2goserver
- http://wiki.x2go.org/doku.php/doc:installation:x2goclient

The x2go client has a setting that lets you run in single-app session mode, and you can just enter /path/to/git-cola (on the ubuntu server) into the command field and it should do the trick.  If you're using the ubuntu-provided one, that's `/usr/bin/git-cola`, though I'd highly recommend testing the latest version in `master` since we're just about to tag that as the next stable.

I actually had the same problem as you but going from linux to linux, but never thought to look into it.  I installed the server remotely and the client locally, and was quite surprised at how much snappier it became when running through the x2goclient.

**Comment by eliao** [comment]
Thanks, I'll give it a try!
