### ISSUE TITLE
git-worktree support broken?

### ISSUE THREAD

**Issue by esran** [git-cola/git-cola#701]
git-cola master (2.11), git (2.10)

Git cola isn't recognising git-worktrees. Example: in a valid repository:
```
% git worktree add ../test -b test
% cd ../test
... make some changes
% git cola
```
The worktree is not recognised as a git repository, even though standard git commands (`git status`) work fine.

**Comment by davvid** [comment]
bummer, I just tried this but it works for me.  What does the `.git` file in the worktree look like?

If you add ```python
    print(paths.git_file, paths.git_dir)
```
at line 127 in `cola/git.py` right before the return statement in `find_git_directory()` what does it print?

What's the observed behavior?  Does it go back to the "choose repo" dialog?

**Comment by esran** [comment]
The .git file contains an absolute path. The output from the print:
```
(u'/home/local/sean/work/PostgreSQL/preplan/.git', u'/home/local/sean/work/PostgreSQL/master/.git/worktrees/preplan')
(u'/home/local/sean/work/PostgreSQL/preplan/.git', u'/home/local/sean/work/PostgreSQL/master/.git/worktrees/preplan')
```
Poking around that worktree directory, `commondir` does have a relative path of "`../..`".

The observed behaviour is that `git-cola` opens normally but shows nothing in the status list, which is different to opening in a non-git directory which does open the choose repo dialog. Similarly, launching `View->DAG` and `View->File Browser` result in empty windows.

So its as if it has detected it as a repository but is somehow unable to identify any of the file changes (I have staged, unstaged and untracked files).

**Comment by davvid** [comment]
Hmm that's curious.  If you share the output of `env GIT_COLA_TRACE=1 git-cola` that might shed some light on what's going on.. a fuller trace can be obtained with `env GIT_COLA_TRACE=full git-cola`.

The full trace might be rather long, but it will have lots of information, so it might be worth uploading it as a gist for ease of inspection if the shorter trace doesn't show something obvious.

The calls to `diff-files` and `diff-index` are the ones that provide the status info, so that's where I would start digging.  A startup trace (without performing any actions in the GUI) should provide enough info to start drilling in.

**Comment by esran** [comment]
Trace for `GIT_COLA_TRACE=1` : https://gist.github.com/esran/4ba1c9ae598f83b9658a2e1ec042dff1
Full trace : https://gist.github.com/esran/e6410a8825b5538c4757605c5bc9b3e8

Looking at the full trace it looks like git-cola is picking up the wrong git. I've a locally installed version (2.13 HEAD build) in my `PATH` before the system git (1.9.1 `/usr/bin/git`).

**Comment by esran** [comment]
Okay, looks like I've resolved it. I was running directly from the git checkout (via a symbolic link). If I install (via `make prefix=... install`) it works ok.

**Comment by davvid** [comment]
Thanks @esran .. I'm going to run with `v2.13` now since we should be portable to any Git version going back to `v1.6` era (I was using a slightly older version).

I'm kinda curious -- is the problem that git-cola was picking up the newer git v2.13, or was it picking up the v1.9.1 version?

If it was finding v1.9.1 I can see that not working because worktrees are a new feature.  But, if it found v2.13 it should work (I hope!).  I ask because you mention that you have the newer one in your `PATH`, and we use whatever is in `PATH`.

I like living on the edge so I'll update git to v2.13 ASAP to make sure it's not a problem related to that version.  Having it not work from the source tree is a little surprising.  Let me know if you have any more insights.

**Comment by davvid** [comment]
Sorry to bug you with that question, I just read the full trace.  In case anyone runs into this issue, the problem was indeed `v1.9.x` being used on a repo that uses worktrees. :joy_cat:

**Comment by esran** [comment]
It picks up the older version from /usr/bin rather than the newer version in my home/bin which is ahead on the path.
