### ISSUE TITLE
Drag and dropping multiple selected files only drops the last selected file

### ISSUE THREAD

**Issue by nocnokneo** [git-cola/git-cola#720]
Expected behavior is that all files are dropped into the receiving application (same behavior as with a file browser)

**Comment by davvid** [comment]
Which tool is initiating the drag event, and which program is receiving the drop event?

The status and browser tools both seem to include the full set of paths in their `text/uri-list` mimedata.  The drop app I'm using is a quick pyqt mimedata viewer I threw together that I could post online if that would help debug it.

**Comment by nocnokneo** [comment]
The drag is coming from the Status widget and Qt Creator is receiving the
drop event. I'm stuck on Windows at the moment in case that makes a
difference. If you share your drop app with me I'd be happy to run it to
help debug the problem.

**Comment by davvid** [comment]
Here's a link to a qtpy-based drag+drop debugging app:

https://gist.github.com/davvid/5dd2231af1fb744701f8e90a1076593e

You'll need `qtpy` and `PyQt5` in order to use it.

That said, this behavior *should* be better behaved in modern versions of Git Cola. I'm able to drag+drop multiple paths onto gvim, for example, and it does the right thing.

If anything is misbehaving then there's a chance that it could be platform-specific. Git Cola should be providing the correct information at this point.
