### ISSUE TITLE
By default select the working branch as remote branch in the push or pull screen

### ISSUE THREAD

**Issue by RaghavendhraK** [git-cola/git-cola#729]
Hi,

As we will always push and pull from the remote branch to the same branch that are locally checked out, it will be nice if we have the branch selected by default. Thus it saves a time on choosing the remote branch every time while push or pull to the GitHub.

Thanks,
Raghu

**Comment by davvid** [comment]
You don't need to select it.  Just don't click anything and it'll push the current branch, which is what `git push` does by default unless you've configured it to do otherwise.

Likewise, it can push all matching branches under other configurations, which is a workflow we would be impeding by making this change.

If the "remote branch" field was required then we would disable the "push" button, but we don't.

In fact, the way I use it is I do "git cola push", select 3 different remotes on the left, and then hit enter.  That's the expected workflow: just hit enter.

The purpose of the "remote branch" field is if you are pushing and you need to name it something else on the remote side.  e.g. push master, but call it "release" over there.  If they match, you simply don't specify it.

**Comment by pkzc** [comment]
That's all right, but it would still be reassuring to see in the "Remote branch" field where the push will eventually go. Currently, that field is empty, which might be interpreted as "I know what I'm doing but I'm not going to tell you". But telling me would be a point to git-cola over the command line git.

**Comment by davvid** [comment]
That's fair. Git does have advanced behavior where having the field empty can be configured to push multiple branches at once (not just the current branch).

That's a bit of an advanced usage, though, and I can imagine adding some persistent state that makes it restore the previous selections the user made. For example, if an advanced user is using that capability and they clear the remote branch field then we could remember that they cleared it and apply that state the next time the dialog is opened.

Similarly, we should probably remember the last selected branch and remotes. The restore logic will have to be careful to only re-apply the selections when they involve the current branch and that the stored state refers to branches that still exist in the current repo. It'll all probably have to be stored as a per-worktree data.

Right now we don't really have per-worktree state, but it seems like a useful concept. One idea is we could store it in the worktree under `.git/...` somewhere.

The usual approach would be to drop it into a dict that's keyed by the worktree. That's kinda better since we can use the existing settings code fro it. We'd just need to to periodically cleanup stale data for worktrees that no longer exist, which we can do periodically (e.g. once a month or so) when the dialog is launched.

**Comment by davvid** [comment]
> it would still be reassuring to see in the "Remote branch" field

+1 to this as well. I think it'd be interesting if we could unobtrusively show the git command that the UI state would run when "fetch", "push" and "pull" are used. That way the user can see how their UI actions map to the underlying git commands. A collapsible section just above the buttons could be a good place for it, perhaps collapsed by default so that users aren't unnecessarily overwhelmed.

That section could also indicate the remote branches that are being updated.

**Comment by davvid** [comment]
Thanks for the sugs. Please test the latest from git ~ this has all been implemented.

**Comment by pkzc** [comment]
I need to use it under windows, is there somewhere a windows package? I suppose the implementation is not yet in 4.6.1.

**Comment by davvid** [comment]
It'll be in the next release for sure. Until then we do build installers on every commit that you can use.

Go to the "Actions" tab: https://github.com/git-cola/git-cola/actions

and then from there click on one of the runs and it'll take  you to a page that looks like this:
https://github.com/git-cola/git-cola/actions/runs/8153431935

When you scroll to the bottom you'll see the artifacts produced by the run. One of those artifacts is the Windows installer.

**Comment by pkzc** [comment]
I tried git-cola-latest-213.exe, but when I started Push the Remote Branch field in the dialog panel came up empty:

![Screenshot 2024-03-11 090805](https://github.com/git-cola/git-cola/assets/23018794/69e401a2-64af-4ec5-968c-5de4fb7ea2b0)

In this state, when I click Push, it will go to origin/devel according to the rules documented in the git manual. My idea was to show that target explicitly in the Remote Branch field before the user clicks Push.

If the the text that I added in red handwriting is shown  in the Remote Branch field , then, for educative purposes, the command line is all right in the form of
  git push --verbose --tags origin devel
even if its explicit form in this particular case would be
  git push --verbose --tags origin devel:devel

**Comment by davvid** [comment]
@pkzc the reason I didn't select the remote branch by default is that I wanted to avoid seeing and running `devel:devel` because it's a bit of an unfamiliar syntax and not typically what users should be running on the command-line.

That said -- the answer was staring at me right in the face. What we should do is special-case the scenario where the local and remote branches are the same and instead of displaying and running with a `devel:devel` argument we should special-case it and use `devel` instead. We'll only see `src:dst` when `src != dst`, which is pretty intuitive to me.

**Comment by pkzc** [comment]
I am sorry to report that I feel uneasy about the behavior of git-cola 221: the Push works now differently from earlier git-cola, and I am afraid that that might cause confusion:

When I start Push, local branch is _devel_, remote branch is _devel_, and the name of the remote branch is shown. **So far, so good.** Now, if I select local branch _main_, remote branch remains _devel_, but git's default behavior is to send _devel_ to _devel_, _main_ to _main_ **unless I select a different remote branch**. The fact is, that I did not select a remote branch, I just selected a different local branch, and expected that I will be shown the matching default remote branch as the target.

It would be a quite different matter if I had selected a non-default remote branch to push a local branch to. In that case it might be a feature of git-cola to memorize this non-default pairing and treat it as a new default in the future.

I don't know whether the memorizing logic should be global for all remote servers or it should be specific to that remote server for which the user sets up the non-default pairings.

And, as you said, it must also be local to the worktree.

It starts to get too complicated.

I could well accept such a decision that **nothing** is changed in the operation of Push **except one thing:** show where the push will go in the Remote Branch field **right when the Push dialog is fired up** (later on, when one starts selecting local or remote branches that field keeps to be filled out all right). The empty field on start is scaring for the less experienced ones and keeps them unnecessarily busy about selecting the remote branch. Unfortunately, I failed to emphasize what I have just said in the present paragraph in my very first comment.

**Comment by davvid** [comment]
Thanks for the detailed feedback. That's a good point -- I think what we should do is when the user clicks on `main` then we should also select the remote branch so that it also says `main`.

That'll make it more closely match the previous behavior and it'll be a bit more intuitive. Likewise, if they explicitly select a different remote branch then we can allow them to be disjoint, but we should try to keep them in sync otherwise.

**Comment by davvid** [comment]
Yeah, I agree that I like the behavior better now that I've applied your suggestions @pkzc . Let me know if that looks good to you!

**Comment by pkzc** [comment]
As long as I do not switch remote servers, git-cola_lates_222 is fine.

But I have two remote servers, _origin_ and _gitlab_, and the following scenario took me by surprise:

1. Started Push:
    Remote: _origin_, Local Branch: _devel_, Remote Branch: _devel_
    That's OK.
    
2. Selected local branch main:
    Remote: _origin_, Local Branch: _main_, Remote Branch: _main_
    That's OK.
    
3. Selected the other server:
    Remote: _gitlab_, Local Branch: _main_, Remote Branch: _**devel**_
    Here I would have expected either _main/main_ or _devel/devel_, since I had never
    touched the remote branches, I only made choice of a local branch and the server and the branches have the default pairings on both servers.


I also got an extra proof of how important it is to indicate the target branch in the Remote Branch field, because I played the above sequence with git-cola 4.3.2 (and I beleive that the released 4.6.1 works the same).  In the 3rd step I got this:

. . . 

3. Selected the other server:
    Remote: _gitlab_, Local Branch: _main_, Remote Branch:

That is the remote branch indicator is cleared when I switch servers. Since I did not have the courage to click on Push I don't really know to which branch it would have gone. Of course, selecting the remote branch at this point prevents any potential catastrophies.

**Comment by davvid** [comment]
Well spotted! That was an edge case around how we were selecting the remote branch. We were prioritizing the currently checked-out branch rather than the local branch field. This has been corrected so that (3) is correctly handled. Thanks again.
