### ISSUE TITLE
Ctrl+C closes commit failed dialog

### ISSUE THREAD

**Issue by joshnoe** [git-cola/git-cola#734]
To reproduce:

1. Fail a commit
2. Click "Show Details"
3. Highlight some text and click "Ctrl+C"

Expected: Text is copied
Actual: Text is not copied, dialog is closed

**Comment by davvid** [comment]
woah, nice find. What OS are you on?  We actually don't have `Ctrl+C` anywhere for close, but we do use `CLOSE = QKeySequence.Close` in `cola/hotkeys.py`.  Usually what we really want is `Esc` for closing, regardless of platform.

It's possible that Qt may be following the OS convention and mapping Ctrl+C to Close, unfortunately.

Are you on Windows?  If you can verify that you're on Windows then we can add an OS-specific tweak to use `Qt.Key_Esc` instead of `QKeySequence.Close`.  IIRC, both Linux and macOS use `Esc`, but maybe it's not worth using `QKeySequence` anymore on all platforms, so we should just use our own definition instead of relying on QKeySequence.  Thanks for the heads-up.

**Comment by davvid** [comment]
Nope, that doesn't seem to be related, actually.  We're using a built-in Qt widget for the prompt, so this is definitely an OS or Qt-specific issue.  What version of Qt are you using?

**Comment by et304383** [comment]
I am seeing issues with Control-C not copying either.  Please fix.

I'm using Ubuntu 18.04.

Right click copy works.

**Comment by davvid** [comment]
We've since switched to a custom widget.  Fix forthcoming.
