### ISSUE TITLE
Unable to open popup window in git-cola on ubuntu 16.04 with gnome3

### ISSUE THREAD

**Issue by muawijhe** [git-cola/git-cola#744]
Hi!
As I said in the title, I am running git-cola on two machines,
- Ubuntu 16.04 with Unity 
- Ubuntu 16.04 with Gnome3

On the second machine, git-cola is not able to open popup windows (i.e. fetch, push).
However, if I run the command from terminal (i.e. git-cola fetch), the correspondent popup window is opened.

Hope you can provide me some info to trace the bug even further.

Best regards,

V.

**Comment by davvid** [comment]
Interesting, it looks like this might be something related to how we create our dialogs that's incompatible with Gnome3, which is kinda surprising.  I'll have to install Gnome3 to reproduce the issue.

I have a hunch that it may be related to a bit of code that's used in a few places.  e.g. in `cola/widgets/remote.py` ~line 126-127 it has:

```
        if parent is not None:
            self.setWindowModality(Qt.WindowModal)
```

Can you try removing or commenting-out those lines and test either the Fetch, Push, or Pull dialogs?

If that fixes it then we can remove that setting, or only apply it on macOS where it makes a small difference to how the popup dialogs behave.  Thanks for the report, and let me know if that makes a difference.

**Comment by davvid** [comment]
Update: I tried master on gnome3 in debian/testing and the popup windows work fine.  It looks like the gnome3 experience is closer to macOS when these flags are enabled, so I no longer think we should remove them.

**Comment by muawijhe** [comment]
Apperently the problem is related to the global menu extension in gnome
shell 3.18.
Disabling this extension leads to normal behavior.
Thanks for the support.
Let me know if I should keep testing something else.
V.

**Comment by davvid** [comment]
phew, at first I thought it might be a wayland issue, which would be harder for me to test.  I'll try out the extension and see what's up.

It might be worth checking if there are any bugs filed against the extension -- we're using a very common Qt feature so there there should be other apps which have hit the same issue, and it's something they would need to fix.

Curious, did those flags make any difference?

You might have to clear the settings for those widgets from your `~/.config/git-cola/settings` to test the behavior since it will record the values from a bad earlier run (e.g., if the sizes were saved with a tiny window size, for example).

**Comment by davvid** [comment]
I was able to reproduce it.  It's actually worse -- I can't even get the main cola window to come up when that extension is enabled.  Please file a bug against that extension as it seems broken.

Is it this one?  https://extensions.gnome.org/extension/1250/gnome-global-application-menu/

It looks like it's abandonware, so it may be that this is one of many problems caused by the extension.

**Comment by muawijhe** [comment]
Hi David,
thanks for your feedback.
I will look forward to see if they can manage to fix it :)

Have a nice day,

V.
