### ISSUE TITLE
Git-cola steals the Super +  E global shortcut key in cinnamon desktop

### ISSUE THREAD

**Issue by s101d1** [git-cola/git-cola#760]
I'm using Antergos Linux with Cinnamon desktop.

Git-cola version is 2.11. 

In cinnamon, Super + E shortcut key is binded to launch file browser at home folder, after installed git-cola, I found out pressing Super + E will launch git-cola instead. I checked in shortcut key settings, the Super + E is stll binded to launch file browser, and no custom shortcut key added too, so nothing changed. Uninstalling the git-cola will restore the Super + E key behavior.

----------

Another issue is compatibility with dark GTK theme.  When using dark theme, only application's title bar that gets affected by the dark theme, the rests are not affected.

**Comment by davvid** [comment]
Regarding the dark theme. you can set `git config --global cola.icontheme dark` and it should swap out the icons for the ones that look good on a dark background.  Set it back to `default` to get the regular icons (or remove the configuration from `~/.gitconfig`).

For the window colors themselves, you might need to set `QT_QPA_PLATFORMTHEME=Gtk2` in your environment.  Test it by running `env QT_QPA_PLATFORMTHEME=Gtk2 ./bin/git-cola` and see if it changes the appearance.

If you're using Qt5 with Gtk3 then there may be a different way to get Qt to respect the theme.  I often refer to this page: https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications

The instructions there work with git-cola since we use Qt.

Regarding the Super-E shortcut, I think what's really happening is that Super-E is simply bound to "Open a Directory" with the home folder as its argument.  We do provide a desktop launcher that handles folders:

https://github.com/git-cola/git-cola/blob/master/share/applications/git-cola-folder-handler.desktop

I suspect that this launcher is getting associated with "Open a Directory".  If you check your "Preferred Applications" (or "Default Applications"?.. something like that) in the settings/preferences there should be a way to choose which app gets launched when double-clicking a folder.

For whatever reason, the newly-installed desktop file is getting chosen before the default file browser.  In the preferences for the default apps you should be able to change it back to the file browser app "nemo" provided by cinnamon.

Let me know if any of these tips lead to dead ends.

**Comment by s101d1** [comment]
Thanks, all are solved. I wonder if you know how to set environment variable for GUI application? I have tried to put `export QT_QPA_PLATFORMTHEME=Gtk2` in .profle, .xessionrc, and .xprofile, all don't work. The only way works is by modifying the git-cola menu launcher command to `env QT_QPA_PLATFORMTHEME=Gtk2  git-cola`.

About the preferred application issue, is this a cinnamon issue or git-cola issue?

**Comment by Vdragon** [comment]
>  I have tried to put `export QT_QPA_PLATFORMTHEME=Gtk2` in .profle, .xessionrc, and .xprofile, all don't work.

These should be fine, you have to restart your X session to let it take effect.

> About the preferred application issue, is this a cinnamon issue or git-cola issue?

Cinnamon shouldn't consider a newly installed application as most preferred application.

**Comment by s101d1** [comment]
> These should be fine, you have to restart your X session to let it take effect.

It didn't work, I even had restarted the pc.

> Cinnamon shouldn't consider a newly installed application as most preferred application.

Can this be controlled by the installer script (in case of antergos that would be the arch linux package script) to prevent the issue happening ?

**Comment by Vdragon** [comment]
> Can this be controlled by the installer script (in case of antergos that would be the arch linux package script) to prevent the issue happening ?

I believe this should be rather fixed by the desktop environment instead of packaging scripts

**Comment by davvid** [comment]
Thanks @playmyskay ! I've added these notes to the docs. Do they still work in Ubuntu 21/22? Let me know if they're outdated, but at least they're written down now outside of this issue so that they're easier to find.

https://git-cola.readthedocs.io/en/latest/git-cola.html#dark-mode-and-window-manager-themes
