### ISSUE TITLE
Feature request: deactivateable "Stage all"

### ISSUE THREAD

**Issue by futureweb** [git-cola/git-cola#777]
Hey there,
it would be nice if the "Stage all" (press "Stage" when nothing is selected) Feature could be deactivated in Settings.
It happened not the first time that one of our Devs / Template Creators unintentionally staged+pushed all modified Files within our Repository.
thx, bye from Austria
Andreas Schnederle-Wagner

**Comment by davvid** [comment]
I added a "Safe Mode" feature that effectively disables the "Stage" button from staging all files.  Thanks for the report.

BTW you mentioned template designers -- we recently added an Image Diff viewer to cola for png, svg, jpg, and other image file types natively supported by Qt.  It has built-in `git-lfs` and `git-annex` support too since i figured that folks that are checking images into git might be using those systems.

If y'all are checking images into git, please share that feature with your designers so that more people become aware of it -- it's very new in `master`, and will be in the forthcoming `v3.1` release.  It's fully integrated so all you need to do is click on a modified image and you'll see both the pre-image and post-image.

cheers

**Comment by futureweb** [comment]
Hey David,
thx for your extra fast solution to my Tickets! ;-)

Will fetch latest master and have a look into Image-Diff Viewer and drop a notice to our Tpl-Devs! :-)

thx & bye from snowy Austria
Andreas
