### ISSUE TITLE
Feature Request: DAG: Generate & copy formatted changelog from selected commit range

### ISSUE THREAD

**Issue by Vdragon** [git-cola/git-cola#783]
This simplifies the progress of reviewing the git-log(1) manpage and run the following command:

```
git log --format='* %an - %h - %s' previous-release-tag..HEAD | xclip -in -selection clipboard
```

The interface should be similar to the "Copy..." action in the status widget, and allow user to customize the changelog format.

**Comment by kakra** [comment]
I'm using a similar approach but made it into a git command:
https://gist.github.com/kakra/31d88f05f80e6240e502624077ec6304

Download this to `/usr/local/bin` or to your `~/bin` and run `git changelog` in your repository before tagging. It will locate the latest previous tag and generate a summary of commits since then. As a convenience, I did `git config alias.cl changelog` so I can simply run `git cl`.

You can also supply a branch, commitid or tag to operate on. It will then rewind to the latest tag in the parent commits and use that as the base to create a changelog.

The summary is made as follows: It generates a git shortlog summarizes authors and commits. Then it inspects all commits for hashtags to generate a headlines list. It considers all commit messages containing `#headline` or `#somenumber` (as in `Fixes bug #100`) for as a headline.

If you `git tag -a` with vim as your editor, you can just run `:!git cl` to paste the output into your vim buffer and start ammending the changelog template, then save, done. :-)
