### ISSUE TITLE
ModuleNotFoundError: No module named 'PySide' (using 3.1-beta windows installer)

### ISSUE THREAD

**Issue by birgersp** [git-cola/git-cola#787]
Tried installing git-cola on a Windows10 system (Python is **not** installed), using the 3.1-beta installer. When trying to run git-cola, I get the following error:

```C:\Program Files (x86)\git-cola\bin>.\git-cola.exe
Traceback (most recent call last):
  File "C:\Program Files (x86)\git-cola\pkgs\qtpy\__init__.py", line 148, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\git-cola\bin\git-cola-script.py", line 24, in <module>
    from cola.main import winmain
  File "C:\Program Files (x86)\git-cola\pkgs\cola\main.py", line 7, in <module>
    from . import app
  File "C:\Program Files (x86)\git-cola\pkgs\cola\app.py", line 15, in <module>
    from qtpy import QtCore
  File "C:\Program Files (x86)\git-cola\pkgs\qtpy\__init__.py", line 154, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found```

**Comment by davvid** [comment]
Thanks for the heads-up, I'll try to get this resolved before the next release.

I have win2008 server and win2012 server installed in virtualbox and they worked there.  I'll try installing https://developer.microsoft.com/en-us/windows/downloads/virtual-machines to see if I can reproduce it there.

@takluyver this sounds like it could be related to takluyver/pynsist#90, perhaps?  I'll see if I can reproduce it.

**Comment by takluyver** [comment]
Looking at the [Qtpy code in this repo](https://github.com/git-cola/git-cola/blob/master/qtpy/__init__.py), I think that error means that the QT_API environment variable must be set to request Pyside. I've no idea why that would be the case if Python isn't already installed, but since you're bundling PyQt5 and not Pyside, it's no surprise that it doesn't work.

Maybe the easiest workaround is for the preamble in the Windows build to unset the QT_API environment variable, or set it to `pyqt5`.

**Comment by davvid** [comment]
We typically see that traceback if it can't find any bindings, e.g. if PyQt5 fails.  qtpy cascades and tries to find other bindings and only reports the final error (Pyside).  The root cause is likely that it can't find PyQt5 because of DLL errors, /methinks.

I was seeing this on a fresh (not updated) Windows2012 server VM until I added the `$PATH`-munging `extra_preamble`, so it's not too surprising that it showed up again under a different Windows version.

**Comment by takluyver** [comment]
Ah, I see. I'd missed that the API variable gets modified throughout the file.

When we know what Qt bindings it should use (i.e. when we've bundled them in the installer), it would be good to have a way to stop it trying all the fallbacks, so you see the original import error rather than the error for the last thing it tried. Maybe an environment variable called `QT_API_NO_I_REALLY_MEAN_IT` ;-)

**Comment by davvid** [comment]
The latest installers now use 64bit Windows and use a modern version of PyQt5, so this shouldn't be an issue anymore.  Thanks for the helper everyone.  Please let me know if the latest installers aren't working for you.
