### ISSUE TITLE
[Feature Request] Allow editing hunks in staged view

### ISSUE THREAD

**Issue by kakra** [git-cola/git-cola#794]
During coding I often come across wanting to stage some changes I made some hours before so I can cherry pick them into my upstream/integration branch. This already works very well and convenient with git-cola due to its feature of selecting single lines for staging.

But I also come often find that I already added some feature or refactoring into the hunks which is far from being ready but I still want to just fix that one bug. What I currently do is using copying the relative path from git-cola, then `git add --patch <filename>` and manually edit the hunk to be compatible with upstream. Afterwards, it automatically shows up correctly in git-cola which is good. But I'd like to do this right inside git-cola.

I could imagine doing this directly from the stage view: It should be possible to right click on a hunk, select "Edit hunk" and an internal editor (or external editor if configured) fires off to let me do the final tweaks before committing. I'd prefer an internal editor to have it well integrated and this is really only for very easy tweaks (otherwise you're doing something wrong probably). The editor should be able to check that the hunk stays valid and support the usual workflows of `git add --patch` by allowing to convert between `+`, `-` and ` ` patch lines.

Such a feature would also need another context menu item in the stage view: You should be able to split hunks (if possible) so that you can break it down to just the hunk you want to edit.

I hope I could properly line out what I'm trying to achieve...

Here's some more read-up:
  1. https://kennyballou.com/blog/2015/10/art-manually-edit-hunks/
  2. https://johnkary.net/blog/git-add-p-the-most-powerful-git-feature-youre-not-using-yet/

**Comment by Tyler799** [comment]
I agree. I manually edit hunks constantly, and I find it very unfortunate that there is no way to do so in git-cola, meaning I have to run back to the command line every time. It's mainly useful when I've performed multiple changes on a line that I want made into separate commits. IE, a line has ```int x = 6;``` and my change is to ```int numBoxes = 10```. In one commit I may have changed some variables for clarity, but in another I intended to fix a specific bug caused by the default value being wrong. Those should be separate commits! No way to do that in git-cola currently. Obviously sometimes the edits are more complicated, but git seems to handle them very gracefully when I do so manually.

**Comment by davvid** [comment]
What editor are you using?  If you're configured to use gvim, emacs, sublime, notepad, or textpad, then the `ctrl-e` edit hotkey from the diff window will jump you right to that file, on that exact line (though you'll need the latest version of git-cola to get that behavior in all scenarios).

I usually do that, temporarily edit it to `int x = 10;` save, stage in cola, and then undo in the editor to get back to `int numBoxes = 10;` 

On linux inotify will automatically refresh the diff view when edits are saved in an external editor; on macOS we have to use `cmd-r` to refresh tho.

This is an cool idea.  It has a lot of edge cases in its implementation but it'd be cool to see some POCs.

An open question, if we had this feature, is should we rectify the worktree with our edits or not?  Both have upsides and downsides; one downside being that the diff "disappears".

Should this editing only be allowed for "modified" changes that have yet to be staged?   If so, it suggests that we don't need to worry about rectifying the worktree because we already have the `ctrl-u` feature to do that, and it keeps it simpler.

I've found myself wanting this occasionally.  Ditto for being able to have a diff in the diff viewer relative to arbitrary commits, for the purposes of grabbing code snippets using the interactive staging editor.  We had that feature a long time ago but I removed it at one point.. maybe I should bring that back too.  I digress -- being able to edit hunks in the diff editor seems like a more common occurrence.

If someone took this then the places to start looking are the `cola/cmds.py` and `cola/widgets/diff.py` modules.  There's a command object that handles the interactive staging, and would need to be extended to know about edits.  The editor in the widgets directory is where the widgets and controller for the diff editor live, and should maybe toggle whether the text area is read-only or not based on the cursor position or some other interaction.  If applying the diffs fail we could let the user know and give them a chance to fix the diff, or start over from the latest diff.

There will need to be a tighter coupling between the command and the editor, namely the patch text for edited lines will now need to be sent to the command object from the editor.  Currently, the editor only communicates line numbers and selected line number ranges.  The command and model data is able to transform the diffs using that information.  This is a new case where the editor will be the origin of the text, so that part will need some rework.

We should try to avoid feature creep, though.  It's easy to eventually end up in a situation where we are getting asked to transform cola into a full blown editor, but if we limit it to just the default Qt TextEdit behavior for editing lines to stage then that sounds pretty reasonable and small in scope.

**Comment by Tyler799** [comment]
@davvid I'm currently using QTCreator for the project I'm working, though I enjoy Atom as an editor. The reason this often happens is I often screw around, try lots of things until I can get something I'm happy with - and then revert changes I don't need, and stage hunks and edit hunks until I get just what I want. I often do not know in advance if I'll be keeping a specific change and thus cannot just stage one change at a time. If someone does add this, that'd be amazing.
