### ISSUE TITLE
Feature request: Single clicking icons to toggle staged

### ISSUE THREAD

**Issue by MurphyMc** [git-cola/git-cola#811]
In git gui, single clicking on _the icon_ of an unstaged item immediately moves it to staged (and vice-versa), as if the item had been double clicked.  While minor and a bit nonstandard in terms of UI convention, this can be nice, and git cola doesn't do it.  Is there any hope of changing that?

I patch my git cola locally to do this.  Since treating the icon differently than the rest of the item is a bit nonstandard, I didn't see a particularly simple and elegant way to do this, so my solution is a bit hacky (though I'm not much of a Qt programmer, so it's possible if not likely that there's a better way).  Indeed, it's a bit hacky all around.  But for what it's worth: MurphyMc/git-cola@347bc967297457587fcf72ba030a0559c2a990a1.

(I can certainly convert that to a PR if desired, though it's just slapped on top of the current master, untested.  It's actually written against 2.11 from Ubuntu 17.10, though a friend applies it to 3.0 without issue.)

**Comment by davvid** [comment]
We used to have that feature a long time ago.  That behavior is surprising from a UX perspective, so we nixed it.

We have a few ways to stage files, but the one interface we should encourage is using `Ctrl+s` keyboard hotkey over all of them.  We shouldn't encourage away from that by having more ways to stage files.

`Ctrl+s` rhymes with using `s` to stage when stuff is selected in the diff editor, so it's consistent.

Also, if we did have this feature, it means that we have a tiny action area for the icon (compared to the entire row) so that's another UX anti-pattern.

Hope that helps explain why we nixed it.
