### ISSUE TITLE
How to change the target comparison branch on the Status window ?

### ISSUE THREAD

**Issue by s101d1** [git-cola/git-cola#816]
It seems the Status window can only show the file change differences to the `origin/master` branch. Is there a way to switch to other repo + branch for the Status window?

**Comment by davvid** [comment]
Hmm.. I think I misunderstood your question when I first read it.  At first I thought you were asking about how to configure a different upstream branch so that the "Branches" widget would display different behind/ahead counts in its branches display.

It now believe that you are actually asking about the behavior where the status widget shows diffs relative to the `HEAD` aka current branch (it does not hard-code `origin/master`, tho when creating your first commit they'll often point to the same thing).  This is primarily because the status widget approximates what `git status` tells us, and is oriented around preparing new commits.

We were able to have the status widget diff against arbitrary heads in an older version, and the code is already mostly setup to still handle this because of that older feature.

Being able to use a different ref to diff against lets you do things like selectively pull changes in from random other branches which is why it was originally added and can still be useful.  There are a few usability things that need to be smoothed out (mainly disabling stuff) like preventing the ability to go into "Amend" mode when this mode is active, visual indicators of the mode (in the title like Amend, for example), and having a way to exit this mode.

The core part of this feature is adding a command to edit the `context.model.head` variable so that it contains a value other than `HEAD`.  We already do this to go into "Amend" mode by setting it to `HEAD^`, so the handling for it would be pretty similar.

Am I understanding this request correctly?

My original response follows below, where I might've been misunderstanding the feature request.  In case I didn't, here it is.

---


In the `Branches` widget right-click on the branch and set a new upstream.

In Git the "associated remote branch" is conveyed through two configuration variables.  The "remote" variable specifies the name of the remote, and the "merge" variable specifies the name of the ref (branch) on the remote side to track.  The variable name changes depending on the branch you're on.  For master, these are as follow.  Run the `$ git ...` commands in your shell to follow along.  The output they produce for me is listed immediately afterwards.

```
$ git config branch.master.remote
origin

$ git config branch.master.merge
refs/heads/master
```

If you want to track a different remote, e.g. a remote called `example`, and branch called "branch", you can run:

    $ git config branch.master.remote example
    $ git config branch.master.merge refs/heads/branch

The branches widget edits these variables, and Cola respects them.

**Comment by s101d1** [comment]
Yeah, basically I want to be able to see one-way diff to other `<remote>/<branch>`. There is `Diff -> Branches` menu, but it's two-way comparison.

**Comment by davvid** [comment]
This is now possible using the new `Diff > Against Commit.... (Diff Mode)` menu action.
