### ISSUE TITLE
Interoperation with Pageant of PuTTY

### ISSUE THREAD

**Issue by laerreal** [git-cola/git-cola#824]
There is the Pageant application for Windwos OS from
[PuTTY](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) distribution.
It caches SSH keys and frees a user from neceserity of entering passphrase each
time he instantiates a SSH connection (a Git over SSH connection in particular).
It is known that [TurtoiseGIT](https://tortoisegit.org/) can interoperate with Pageant.
Hence, it seems possible for outer software to do this.
It would be very handy if Git-Cola may cache keys in Pageant instance.
Because of security reasons this option must be disableable.

**Comment by davvid** [comment]
This should be possible already. The beauty of Git Cola is that we just run the stock `git` commands so if you configure things to work correctly for `git` on the command-line then we'll pickup that configuration.

The advice around `GIT_SSH` on this page seems like it should do the trick.

https://superuser.com/questions/1114912/how-can-i-use-the-ssh-config-file-with-pageant-under-windows

If that works for you please share which configuration variant you're using and we can consider adding tips to the documentation.

Patches kindly accepted. I don't use Windows so help is appreciated for anything in the Windows realm.

I should also mention the "git credentials" ecosystem. I don't think there's much for us to do here since there's already plenty of support for handling credentials in core git.

https://git-scm.com/doc/credential-helpers

https://git-cola.readthedocs.io/en/latest/git-cola.html#setting-up-credential-helpers

https://git-cola.readthedocs.io/en/latest/git-cola.html#ssh-agents-for-key-based-authentication
