### ISSUE TITLE
Windows Defender SmartScreen kinda blocked the installer from running in Windows 10 (1803)

### ISSUE THREAD

**Issue by brlin-tw** [git-cola/git-cola#829]
![default](https://user-images.githubusercontent.com/13408130/40582583-6164d354-61ad-11e8-8e74-6090c6f6f0c7.png)

I got this window when I attempt to run the setup program.  Though the setup is still launchable via clicking the "Other Info（其他資訊）" text and then the "Still execute（仍要執行）" button will pop up the behavior is still discouraging.

![default](https://user-images.githubusercontent.com/13408130/40582609-0adf0652-61ae-11e8-9382-a5ed2b401f0e.png)

Digital signing the program might solve this issue, but probably with a cost.

**Comment by davvid** [comment]
This is a bit unfortunate.  Maybe we can leave this issue open so that if someone wants to donate a certificate we can setup a secure communication channel to get the certs to me for signing.

Bummer, I was able to eliminate Windows from the release process by relying on pynsist to build windows installers on linux.  I'd like to not need Windows when making new releases. According to this link, we should be able to do the signing from linux:

https://stackoverflow.com/questions/18287960/signing-windows-application-on-linux-based-distros#18288049

**Comment by davvid** [comment]
It's been a few years so I'll close this now since there's not much I can do about it.
