### ISSUE TITLE
doesn't work on Mac OS

### ISSUE THREAD

**Issue by kopach** [git-cola/git-cola#851]
Following current [installation instruction for Mac OS](https://github.com/git-cola/git-cola#mac-os-x) I've installed git-cola which isn't working for me. In the beginning it shows me popup where I need to choose project to open but once I select project - git-cola crashes. 

I do understand, that latest stable working version is `3.1`. But in such a case - would be great to have `master` branch unchanged and have all ureleased work on some other branch. Or as an option - add step to the installation instruction to `git checkout v3.1`

**Comment by davvid** [comment]
Thanks for the heads-up.  I'll take a look at the macos issues tonight.

As a curiousity -- how are you launching cola -- through the application bundle?  If it's that way, do you see any output in the `Console` app that might have come from cola, maybe a traceback?

Otherwise, does it work if you launch it from the command-line?  Does it work when run from the source tree?

**Comment by kopach** [comment]
Hi @davvid. On the time of opening this issue - latest commit on master was 59e686e099abe0a3ff7da7e35e9bc8ca0d1b4b39. I can confirm, that build from this commit still reproduces described issue. However current latest commit from the master 4409089292cbdf86282c54a4b7e95d2d8e48f3fb doesn't have the defect anymore. So, we can close this issue, I think. 
Anyway, to prevent such a case for new users in future - I would still put a step with `git checkout` on latest stable and tested version.
