### ISSUE TITLE
Cursor in commit box - please revert to bar

### ISSUE THREAD

**Issue by et304383** [git-cola/git-cola#889]
It's a box now, apparently somewhere between 3.0 and 3.2 releases it changed.

I don't know about anyone else, but the box cursor doesn't improve anything, and makes it more difficult to know where you're going to insert a character if you type. The bar is 100% clear.

Please, let's not go back to DOS days.

**Comment by davvid** [comment]
I'll think about it.  The current cursor is consistent with stuff like `terminator`, and it's much easier to visually see and find.  The problem with the line cursor is that we have to give it a width, which makes it not great for handling HiDPI screens.

**Comment by et304383** [comment]
A toggle switch option would be much appreciated.

**Comment by char101** [comment]
The normal GUI text cursor shape is a bar, if you want to provide a better alternative at least please let the user decide and not make it as the default.

**Comment by scop** [comment]
Using the block is a source of confusion, because as others have noted, the normal shape for a cursor is a bar in a lot of apps, and it usually switches to block to indicate overwrite mode being in effect.

My personal opinion is that no user config or switch should be added for this, but the change should be just reverted. I think the stated reasoning for why the change was made indicates a toolkit wide problem (which I haven't experienced myself in any way), which would be better to be fixed in consistent manner in the affected toolkit(s), not in individual app fields here and there.

**Comment by et304383** [comment]
@davvid When do you think you will have time to cut a release?

**Comment by et304383** [comment]
@davvid when will you publish this to the apt repo at http://ppa.launchpad.net/pavreh/git-cola/ubuntu ?

**Comment by Lin-Buo-Ren** [comment]
@et304383 The following message is in the [archive's page](https://launchpad.net/~pavreh/+archive/ubuntu/git-cola):

For questions and bugs with software in this PPA please contact [Pavel Řehák](https://launchpad.net/~pavreh).
