### ISSUE TITLE
GUI to rollback to a previous commit

### ISSUE THREAD

**Issue by firestar9114** [git-cola/git-cola#890]
Can you please add a section to the GUI that lists past commits and allows an easy way to rollback back to them?  For instance scrolling down to a past commit in this section that you want to rollback the project to, right clicking it, and selecting something like "restore this commit", "more info".  So, for example let's say I make a project on the Aug 1st and do an initial commit & push.  The project is empty.  The next day, on Aug 2rd, I add a text file the next day "test.txt" that contains the text "this is a test".  I then commit & push this as "test one" and have a commit message of "testing commits".  Finally, on Aug 3rd,I rename the file to "test1.txt" and add a second file "test2.txt".  test2.txt contains the text "this is ANOTHER test".  I now commit & push this as "test two" with the message of "Still testing commits"

In this case there should be three rows show in the section:
======================
test two:Still testing commits
test one:testing commits
initial commit:initial commit
=====================

Now, lets say I want to roll back the project to Aug second when I only had one text file called "test.txt" that contained "this is a test".  To achieve this in this system I would want scroll to the element "test one:testing commits" in the gui and right click it, then choose "restore this commit".  Git-Cola would then pull the commit for that state, removing the 2nd file(which is still exists, just not in this state.)  and either renaming the other file or replacing it with the old version outright. I'm not sure how that works.  When I tried to figure out how to do this all the information I could find was this: https://stackoverflow.com/questions/14876395/recover-previous-version-of-project-using-git-cola

If you don't want to implement this, can you please make the console accept input so we can run these commands right from in git cola?  Being able to switch versions of a project was one of my favorite features of GUI git programs on windows, I would love to see that functionality come to git-cola.

**Comment by davvid** [comment]
This feature already exists in the "DAG" window.  It shows the entire history, and you can "Reset" your branch and/or worktree back to any commit.

Right-click on any of the commits listed in the "View > DAG" window and you should be able to do this by choosing one of the "Reset" actions.

If you want to take just a single file, use the "Grab File..." action.  Please feel free to re-open this issue if I misunderstood your request.  cheers

**Comment by nekromoff** [comment]
I only found revert option by going here, then decoding what the "DAG" means. And only then I was able to do a revert. I think this would be much better suited being part of standard main menu, where flow would be choosing Revert and only then choosing which commit to revert. 

Current setup allows only to go view current branch tree and only then being able to revert. #ux

**Comment by davvid** [comment]
@nekromoff @firestar9114 the beginner's perspective can be really helpful to make the tool easier to understand for new Git users.  I'll need your help in helping me understand exactly what we want this feature to do.  I'll explain what I mean so that we can try to come up with something intuitive yet powerful.

First thing first -- advanced Git users see the word "revert" and they are going to think `git revert <sha1>` command, which has a very explicit behavior -- it does the reverse of the changes that were introduced in the `<sha1>` commit.  That's why our "Revert" option in the tree view implements that behavior.

This seems to be very different from how you describe "revert" in this issue, so let's explore how we might actually implement the idea presented here.

What you describe is something, as a Git advanced user, that would not be described in terms of "revert" at all.  What @firestar9114 is describing is one of 2 natural things in the Git world:

1) The first is to create a branch at the old point in history, and then checkout that branch so that the worktree files are updated to match exactly that commit.  Branches have no cost so switching branches is a simple way to keep the current branch head as-is while exploring an old point in the history.  This is the first thing someone comfortable with Git does because it's non-destructive and safe.

2) What I mistakenly suggested above is the more dangerous behavior of force-resetting your branch head and worktree files to that point in history.  This has the same effect to someone looking at the filesystem, in that the worktree files get updated to match the sha1, but it's often not something someone would do with a public repo branch that is shared with others, because it drops history.

Your branch head pointer gets pointed to an older point in the history, and all the intermediate history is lost (commit messages and all the snapshots).  This is not really a common thing to do.  For Git users, intermediate commits get rebased + squashed together before they are published/pushed, and losing commits is only done with your own personal private branches that have not been published anywhere.  Sorry for the long explanation, and I shouldn't direct users to that behavior -- we should err on the safe side.

For a new repo where you are fine throwing away commit snapshots `git reset --merge <sha1>` does the trick, but it's not what a Git user would call "revert" so let's come up with a more explicit description.  In cola this is the "Reset" sub-menu.  Also, maybe we don't want to lose the intermediate snapshots, so a different behavior might be wanted altogether.

Now, here's something that neither of these two workflows do, and something that might actually make more sense to a user coming from a different version control context.

Instead of creating a branch to go to that point in history, or resetting the current branch to point there, a different behavior is that we could basically throws out the current state of the worktree files, take the content from the selected commit, and brings the content into the current worktree so that a new commit can be created from that state.

We could even automatically commit this, but filling in the commit message with a "Revert files to commit <sha1>" message might be a better option since it makes the commit operation explicit and under the user's control.

To me, that is what it seems like you're describing, @firestar9114, in that you would get your worktree files to match exactly as they were in the selected commit.  It's also safe because no commits are lost -- the user is guided towards creating a new commit that takes the worktree to that state.

On the command-line, this is the rare `git read-tree <sha1>` command, and we currently do not have any way to do that from cola.

How do you feel about a new menu action, "Revert files to committed snapshot...", that would implement this feature?

**Comment by nekromoff** [comment]
My use case is very simple as I am also very basic user of Git (and therefore don't really know how to do reverts/reset properly.

I would therefore expect to have a shortcut to do a revert in Actions menu.

I am sure advanced users will process it in different way, maybe using Reset etc.

**Comment by nekromoff** [comment]
BTW, I used tutorial here, which uses revert directive:
https://www.hostingadvice.com/how-to/git-rollback-commit/

**Comment by firestar9114** [comment]
Oh, I just realized this is still open, sry.  I have learned a lot more about git and just moved to using the cli.  Essentially I wanted some more convenient GUI shortcuts for a command like `git reset HEAD~<commits# to reset> --hard`.  Having gotten much more experience with git, a `git reset HEAD~<commits# to reset> --soft` could also be very handy.  Maybe add to the context menu in the commit list with options like "Reset to state at this commit discarding local changes", "Reset to state at this commit keeping local changes" or something similar? Commit reverts would also be handy.  I haven't used git-cola in about a year now, so I'm not sure if these features currently exist in the project.  Sorry for my extremely delayed feedback, my life got busy and I haven't logged into this github account in quite a while.

**Comment by davvid** [comment]
Thank you to everyone who replied to this old issue here.  Re-reading it to refresh myself, we currently do have the soft reset feature available, but this issue deserves to stay open because it's not discoverable enough. 

The menu entry is `Actions -> Reset -> Reset Branch Head`.

Even though we have this feature, I think this issue should stay open since y'all had trouble finding it.  I'm totally open to sugs on tooltips or renaming this to something that makes more logical sense to a non-git.

Here is my best sug on what we should call this: "Undo Commit" could be this action hard-wired to `HEAD~` which seems like a really logical name for the action.

The general "Reset Branch Head" action that takes arbitrary ref names might be better called "Soft Reset Branch" with a tooltip that says "Use `git reset --soft` to reset your branch head to the specified commit".

**Comment by davvid** [comment]
`git dag` seems to have this figured out nicely in that the context menu when you right-click on a commit has a complete Reset submenu with the various `--hard` `--soft` actions.  I'm starting to think we should basically do the same and add a Reset top-level menu to the main cola UI and add the various `--keep`, `--merge`, `--soft`, `--hard` actions to fill it out beyond the "soft" and "keep" behavior it currently exposes under `Actions -> Reset -> ...`.

<img width="632" alt="Screen Shot 2021-01-24 at 10 13 44 PM" src="https://user-images.githubusercontent.com/13196/105668348-fd6d4e00-5e91-11eb-9d76-abe895b57654.png">

Thoughts?

**Comment by nekromoff** [comment]
I checked the DAG visualizaton and there are command available on right click (in a context menu).

I think what you describe @davvid makes sens to me as a user - restoring and older version (commit), but not dropping history, but rather adding this as another commit in DAG. This would basically just take state of that older commit and recommit it and it would serve the purpose of returning to any point in the history while keeping full DAG tree.

As a user more on basic side, I wouldn't know the difference between Soft, Hard and Merge reset, though. I am sure this is the official lingo of git on the other hand.

Undo commit makes sense to me as it is easy to understand from UX point as Undo functionality has been commonly used for ages.

**Comment by davvid** [comment]
Alrighty, we now have a "Reset" menu and we've brought parity to the context-menu from the DAG and the Reset menu.  There's a new "Undo Last Commit" action, as well as a new "Restore Worktree" action that grabs content from an existing commit.

**Comment by nekromoff** [comment]
Cool, guys, thanks!
