### ISSUE TITLE
Dual-Booting Conflict

### ISSUE THREAD

**Issue by zauberparacelsus** [git-cola/git-cola#892]
On my computer, I dual-boot, with one SSD devoted to Windows and the other devoted to Linux.

On the Windows drive, I had created a number of .txt documents, and used git with git-cola to manage my changes over the course of a few months.  Some time later, I booted up with my Linux drive, and when I used git-cola to open the folder containing these documents, it falsely showed *every single file* as being changed.  When looking at the diff, it was showing every single line of every file as being changed, but no actual changes were made.

I think what what is going on here has something to do with differing line endings.  Windows uses `\r\n` to end lines, while *nix systems just use `\n`

**Comment by Lin-Buo-Ren** [comment]
I believe this is rather a Git configuration issue, check out [Git - Git Configuration](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace)

**Comment by davvid** [comment]
Correct, you'll probably want to deal with this by configuring `core.autocrlf` accordingly.  Maybe you want `input` and then configure your editors to use `\n` instead of `\r\n`, but only after fixing up your repo to use normalized line endings.

https://help.github.com/articles/dealing-with-line-endings/
