### ISSUE TITLE
UI is broken in macOS dark mode

### ISSUE THREAD

**Issue by werkshy** [git-cola/git-cola#905]
On macOS Mojave with the new dark theme, Cola seems to not pick up the text and background colors properly, it is probably overriding one without overriding the other.

I'm attaching two screenshots. In one nothing is visible, in the other I have selected some text elements to show that they are indeed there.

## Steps to reproduce:

1. Enable dark theme in macOS Mojave (Settings->General)
2. Open git cola in a modified git directory (must be opened after theme is selected)
3. Notice that text (diff, filenames, commit headline, commit body) is invisible

## Expected Result

Text is visible (either white-on-black or black-on-white)

## Screenshots

<img width="1265" alt="screenshot 2018-11-14 at 01 36 07 pm" src="https://user-images.githubusercontent.com/3298/48504446-c2335700-e812-11e8-8628-305c624ac0b1.png">

<img width="1265" alt="screenshot 2018-11-14 at 01 36 26 pm" src="https://user-images.githubusercontent.com/3298/48504452-c8293800-e812-11e8-802d-7c0c75827d24.png">

**Comment by Navaneethsen** [comment]
Same here

**Comment by davvid** [comment]
Related upstream Qt issue:

https://bugreports.qt.io/browse/QTBUG-70346

We'll keep this open until we have validation that it's been fixed in something that users can update to using homebrew.

In the meantime you can get the "dark" style icons in cola by doing `git config --global cola.icontheme dark` and that'll fix all the icons in cola.

Any remaining issues are likely related to QTBUG-70346, unfortunately.

**Comment by toanho-kms** [comment]
+1

**Comment by jrosco** [comment]
please fix.

**Comment by jm4R** [comment]
I am currently writing Qt stylesheet(s) for git-cola with dark and light theme, but I don't have acces to Mac hardware. Maybe somebody could test it on Mac when its done?

**Comment by turbolent** [comment]
A workaround for now is to follow [Apple's guide](https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_app) and patching Cola like so:

```python
import AppKit

app = AppKit.NSApplication.sharedApplication()
aquaAppearance = AppKit.NSAppearance.appearanceNamed_(AppKit.NSAppearanceNameAqua)
app.setAppearance_(aquaAppearance)
```

This requires pyobjc to be installed.

**Comment by kurtmckee** [comment]
@davvid I recommend closing this issue. The linked Qt bugs have been closed, and there have been no updates to this ticket for 4.5 years.

**Comment by davvid** [comment]
Thanks for the pointer @turbolent!

@kurtmckee I agree that we could can close this issue, but instead of just closing it I dug into helpful code example above from @turbolent and integrated into cola as a new feature.

We now provide macOS-specific application themes in the Appearance settings when the pyobjc package is installed.

The following macOS-specific themes are now supported alongside their high-contrast variants:

* Aqua
* Dark Aqua
* Vibrant Light
* Vibrant Dark

I don't currently know how to detect whether the OS has dark mode enabled, so this does require the user to configure the setting, but at least there's a simple way to enable a native macOS dark mode theme now.

enjoy!
