### ISSUE TITLE
Git cola freezes at aplying patch

### ISSUE THREAD

**Issue by antoniodemora** [git-cola/git-cola#906]
I'm on windows 10, git cola 3.2, I try to apply some patches and it freezes. I used command line to apply the patches but got some errors and didn't know what to do, went to git cola to some visual assistant but it freeze at soon as I click "Apply" button

**Comment by davvid** [comment]
Are you able to run it from a shell so we can inspect the debug logs?  It might help to install python and pyqt manually rather than using the installer so that we can run cola from the source tree.  Another place to check is the Ctrl+0 console log.

Launch cola from the source tree using:

    env GIT_COLA_TRACE=1 ./bin/git-cola

Setting `GIT_COLA_TRACE` to `1` in the environment will make it print out the git commands it's running to stderr, which can let us see what happens when you run it.  The interesting lines are the ones that are running `git ... am <path-to-your.patch>` in case there's something that's tripping it up there.

You can skip straight to the patch dialog by doing `./bin/git-cola am`, and you can also pass patch files to the command-line, just like `git am`.

The lowest layer is just the `git am` command, which is how you apply patch files.  These are Git patch files created by `git format-patch` (or cola's export patches dialog)  that create commits when applied.  It'd be good to know what happens when you apply patches using the `git am` command with your patch files.

Non-git patch files can be used with `git apply` to apply the changes directly to the worktree.  These are created by doing something like `git diff >tmp.patch`, but aren't currently supported in the UI.

In any case, it should report an error, so the freeze is interesting.  Let me know if you find anything, and if you're using patches generated by `git format-patch`..

**Comment by antoniodemora** [comment]
I think It was an issue with the .Net included python, I uninstall it from Visual Studio and installed CPython and now everything is ok.

Thanks for the tips on debuggin git cola on windows
