### ISSUE TITLE
Question : why treewidget instead of tablewidget ?

### ISSUE THREAD

**Issue by azzamsa** [git-cola/git-cola#917]
Hi @davvid.

This is not an issue, I just wanna as your design decision. I want to develop small-medium size pyqt app. I read and learn git-cola code to understand pyqt under the hood. Cause I can't find comprehensive blog/book/videos explaining pyqt. Just found some simple blog tutorial.

Why in DAG, you use treewidget, instead of tablewidget. I don't see git-cola using clid-item, it's just like table item. 

![2019-01-16-14 31 29](https://user-images.githubusercontent.com/17734314/51233066-711f1b00-199b-11e9-8726-98d7ae8ceb09.png)

I want to discuss this on email, but I am worried inbox will distrub you time. I don't find any discussion platform for git-cola e.g gitter/irc. So I just via issue.

Thank you

**Comment by davvid** [comment]
Code reuse is one reason -- QTreeView/Widgets are flexible and we already use them everywhere else so it's easier to just use a treeview in a list-like mode since we already have support code in place for tree stuff.

Another reason is that it's slightly easier to make flat lists like this because you don't have to disable the vertical headers that we get with Table widgets.  It's a feature we would have to disable, so it's simpler to use a widget that doesn't have vertical header labels so that we can avoid that extra work.  Another example is the grid that it shows by default.  We would have to disable that too.

For the use case of a very simple flat list of items with multiple columns, using a QTreeWidget/View is a perfect fit and a great feature in Qt.

For a use case closer to a spreadsheet, QTableWidget/View makes more sense.

**Comment by azzamsa** [comment]
Really sum every things up. Thank a lot. I never think about those reason. I agree with you.

Summary:

1) Code reuse - git-cola already use QTreeView a lot
2) No need to customize vertical headers 
3) No need to customize grid that it shows by default.

Point two and three are really the key, I never think of them.

> For the use case of a **very simple flat list of items with multiple columns**, using a QTreeWidget/View is a perfect fit and a great feature in Qt.

>For a use case closer to a **spreadsheet**, QTableWidget/View makes more sense.

Great advice. :)

Thank a lot awesome git-cola, and making its source accessible to everyone. :tada:
