### ISSUE TITLE
segfaults on start in Ubuntu 18.04 (running in vbox 6.0.2)

### ISSUE THREAD

**Issue by f-scholer** [git-cola/git-cola#918]
This is probably related to the vbox environment as git-cola was working before in vbox 5.x before I updated to version 6.0.2

$ git-cola 
Traceback (most recent call last):
  File "/usr/bin/git-cola", line 53, in <module>
    from cola.main import main
  File "/usr/share/git-cola/lib/cola/main.py", line 6, in <module>
    from . import app
  File "/usr/share/git-cola/lib/cola/app.py", line 43, in <module>
    from . import fsmonitor
  File "/usr/share/git-cola/lib/cola/fsmonitor.py", line 41, in <module>
    from . import inotify
  File "/usr/share/git-cola/lib/cola/inotify.py", line 48, in <module>
    _libc = ctypes.CDLL(ctypes.util.find_library('c'), use_errno=True)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/VBoxOGLcrutil.so: undefined symbol: crypt_r
Segmentation fault (core dumped)

**Comment by f-scholer** [comment]
disabling 3D acceleration in vbox removes the error

**Comment by PetrGlad** [comment]
With older guest additions for vbox 5.2x, it worked fine. I see the error after upgrade to VirtualBox guest additions to 6.x version.

**Comment by davvid** [comment]
Please report this upstream to the Ubuntu virtualbox package maintainers.  That looks like a bad build:

   OSError: /usr/lib/x86_64-linux-gnu/VBoxOGLcrutil.so: undefined symbol: crypt_r

As a wild experiment, try doing `env LD_PRELOAD=libcrypto.so git-cola` and see if that helps.  It seems looks like that dso isn't linked against libcrypto -- in any case, that's a packaging bug and there's not much we can do about it.  Does LD_PRELOAD help?  If so, maybe the vbox build should link against libcrypto.

I don't know  much about virtualbox and why its libraries are getting loaded but the code in question is trying to load libc using ctypes and that seems to be getting intercepted by virtualbox, somehow.

Here is a simple test case.  Perhaps we need to do this differently, but as you noted, this has worked for a long time.

    #!/usr/bin/env python
    import ctypes
    ctypes.CDLL(ctypes.util.find_library('c'), use_errno=True)

Ultimately, this is the root cause.  Can you test something out?

In cola/inotify.py line 53 there's a try/catch that's catching AttributeError.  What happens if you change it to say:  `except (AttributeError, OSError):`  so that it also catches OSError -- does it start working?

That's basically working around the traceback when loading libc, but if that works for you then we can put that bit of defense in place to make it a little more resilient.
