### ISSUE TITLE
Ambiguous hotkeys by default for Alt+U (formerly triggered Stage Untracked)

### ISSUE THREAD

**Issue by Poikilos** [git-cola/git-cola#926]
I have git-Cola 2.10, the latest packaged version on Fedora 28.
Formerly, I could do Alt+A, Alt+U (I'm pretty sure that's correct) to stage tracked then untracked, even with the Actions panel enabled, but now it highlights the Unstage button on the Action panel and says, "The key sequence 'Alt+U' is ambiguous. Use 'Configure Shortcuts' from the 'Settings' menu to solve the ambiguity. No action will be triggered." (Alt+A still works). Also, since Ctrl+Enter or Commit only stages tracked files automatically using the dialog box, there is now no way to Stage Untracked using the keyboard.

**Comment by poikilos** [comment]
resolved in 3.3-git downloaded today. It may have only worked "before" I tried it on 2.10 because I have 3.0 on my other computer.

**Comment by poikilos** [comment]
Reopened since issue still occurs when Submodules is shown in tab form (u is alt key for that, so issue occurs in latest git version) in same panel as Status tab, even when a different panel is active.

**Comment by davvid** [comment]
Hmmph how weird.  Is anyone else able to reproduce this issue?  I'm on Debian/testing and I don't get the ambiguous overloads.  In the code, the only place we register for Alt+U is in the main widget.

Hmm.. the one thing that is kinda related is that "Unstage" starts with "U", so maybe there's some desktop integration where it makes "Alt" able to select buttons, activate menus, etc?

I'll see if there's something we can do to make the buttons ineligible for that feature (we don't currently do anything to opt-in to that behavior).  As a workaround, I bet you can hide the Actions widget since you really don't need it -- every button there has a hotkey associated there.

That widget is mostly there for legacy users -- I removed it once and the users complained, so I brought it back.  I'm on gnome-shell so our environments should be pretty similar.  I'll need some help to reproduce it, though, since I'm not seeing this behavior.

**Comment by davvid** [comment]
This is probably fixed and worth testing again. We now enable Qt's Wayland integration when we detect Wayland by default, which could make a difference. We also reworked the hotkeys a bit so this shouldn't be an issue anymore.
