### ISSUE TITLE
Launch Diff Tool not working from 3.1 onwards

### ISSUE THREAD

**Issue by drewhemm** [git-cola/git-cola#935]
I recently upgraded to v3.3 and when I went to perform a merge with conflicts, I saw the following:

![screenshot from 2019-03-06 12-56-37](https://user-images.githubusercontent.com/4614943/53882843-523e1c00-400f-11e9-8aea-195f3aecb7c6.png)

I was previously running 2.x. I tried v3.2 v3.1 v3.0 and v2.11. The problem only occurs in 3.1 onwards. 

I am on Ubuntu 18.04.2 LTS and I use meld as my diff and merge tool, specified in my git global config. I tried also installing xxdiff, as this was the default tool specified in git-cola, but that did not help. 

Running the command `git mergetool --no-prompt -- crate/playbook.yaml` from the terminal opens the mergetool without error.

**Comment by davvid** [comment]
Are you using gnome terminal?  At one point we changed to use `gnome-terminal -c "git mergetool ...."` as the command, and perhaps the behavior of gnome-terminal changed and now it just wants a command instead of having the `-c` argument shell quoted into a single string.  Let's get this fixed before the next release.

**Comment by davvid** [comment]
I can repro the issue.  I'll push a fix shortly.  Thanks for the report.

**Comment by drewhemm** [comment]
Thanks. I have tested that commit and can confirm it clears the issue for me.
