### ISSUE TITLE
layout in full-screen mode not properly restored

### ISSUE THREAD

**Issue by WanWizard** [git-cola/git-cola#943]
Long time git-cola user on Fedora.

After the last fedora update, I got git-cola version 3.2 installed:
````
Installed Packages
Name         : git-cola
Version      : 3.2
Release      : 1.fc29
Architecture : noarch
Size         : 4.5 M
Source       : git-cola-3.2-1.fc29.src.rpm
````

From what I can deduct:
* git-cola starts up in non-fullscreen mode
* the widgets are positioned as saved in the layout, taking the smaller window into account
* the window resizes to full screen, widgets resize acoordingly
* widgets are now no longer the size the where when the layout was lasted saved

I've seen this problem before with an older version (a year or more ago), it was fixed, but now it seems to be back. Very annoying if every time you open git-cola, you first have to resize all widgets.

When you don't start up in full screen, but manually size the window to be like 20px less than full screen, this issue doesn't happen, but as a window like that automatically expands to fullscreen, it is not a fix or workaround.

**Comment by WanWizard** [comment]
To add to this, it is easy to replicate:
- click the full-screen button to zoom the window to full screen
- resize the widgets to your liking
- make sure you've got "Save GUI settings" checked in the configuration
- use the full-screen button to toggle, and you'll see all widgets are resized, and the layout is ruined.

**Comment by davvid** [comment]
This is really curious -- what Qt5 version do you have?  I'm on debian/testing and the problem doesn't reproduce here so this could be a Qt bug.  I'm running Qt  5.11.3 + debian's patches.

We have gotten similar reports in other apps when using Qt 5.6 at work, so it's possible that a bug may have been fixed in that range.

We are using the idiomatic pattern documented here: https://doc.qt.io/qtforpython/PySide2/QtWidgets/QMainWindow.html#PySide2.QtWidgets.PySide2.QtWidgets.QMainWindow.saveState

But we were not using that in older versions, so if you can clone the repo we can try a couple of different versions to see if the behavior is different.

There is only one use case where we're in control: closing and reopening the program.

The repro instructions mention toggling the full screen (maximize?) button -- and for that action we don't actually have any code in play.  It's all controlled by Qt itself, so changes in behavior would be attributed to the underlying Qt version.

To test the differences in behavior related to closing and reopening the app, that behavior should be tested against the following tags: v3.0 v3.1 v3.2 v3.3

Clone the repo, checkout the tag, run `./bin/git-cola` and shutdown/restart at least once before starting to test.  If any of these are better behaved then it could be related to the changes to `cola/widgets/standard.py` in the `apply_state()` methods between those versions.

This Qt bug https://bugreports.qt.io/browse/QTBUG-16252 seems relevant, and possibly the root cause.

**Comment by WanWizard** [comment]
I'm running a stock Fedora 29, up to date, it seems to have installed both 4 and 5?
````
qt.i686                                              1:4.8.7-45.fc29                        @updates                  
qt.x86_64                                            1:4.8.7-45.fc29                        @updates                  
qt-common.noarch                                     1:4.8.7-45.fc29                        @updates                  
qt-mobility-common.x86_64                            1.2.2-0.32.20140317git169da60c.fc29    @fedora                   
qt-mobility-location.x86_64                          1.2.2-0.32.20140317git169da60c.fc29    @fedora                   
qt-mobility-sensors.x86_64                           1.2.2-0.32.20140317git169da60c.fc29    @fedora                   
qt-settings.noarch                                   29.0-1.fc29                            @fedora                   
qt-x11.i686                                          1:4.8.7-45.fc29                        @updates                  
qt-x11.x86_64                                        1:4.8.7-45.fc29                        @updates                  
qt5-qtbase.x86_64                                    5.11.3-1.fc29                          @updates                  
qt5-qtbase-common.noarch                             5.11.3-1.fc29                          @updates                  
qt5-qtbase-gui.x86_64                                5.11.3-1.fc29                          @updates                  
qt5-qtdeclarative.x86_64                             5.11.3-1.fc29                          @updates                  
qt5-qtmultimedia.x86_64                              5.11.3-1.fc29                          @updates                  
qt5-qtquickcontrols.x86_64                           5.11.3-1.fc29                          @updates                  
qt5-qtscript.x86_64                                  5.11.3-1.fc29                          @updates                  
qt5-qtspeech.x86_64                                  5.11.3-1.fc29                          @updates                  
qt5-qtspeech-speechd.x86_64                          5.11.3-1.fc29                          @updates                  
qt5-qtsvg.x86_64                                     5.11.3-1.fc29                          @updates                  
qt5-qttools-common.noarch                            5.11.3-1.fc29                          @updates                  
qt5-qttools-libs-designer.x86_64                     5.11.3-1.fc29                          @updates                  
qt5-qtwayland.x86_64                                 5.11.3-1.fc29                          @updates                  
qt5-qtx11extras.x86_64                               5.11.3-1.fc29                          @updates                  
qt5-qtxmlpatterns.x86_64                             5.11.3-1.fc29                          @updates                  
qt5-srpm-macros.noarch                               5.11.3-1.fc29                          @updates                  
qtwebkit.x86_64                                      2.3.4-23.fc29                          @fedora 
````

**Comment by WanWizard** [comment]
> To test the differences in behavior related to closing and reopening the app, that behavior should be tested against the following tags: v3.0 v3.1 v3.2 v3.3

Did this. Took a while to figure out I needed to use `python3 ./bin/git-cola`.  v3.0 and v3.1 work fine, they start up maximised with the widget layout I've set, and toggling the maximize button doesn't destroy that. v3.2 and v3.3 have the problem, as soon as you toggle maximise (to the non-fullscreen state), the widgets are resized to fit the new window size, and when you then toggle maximise again to go back to full screen, the widgets resize proportionally, so they're all wrong.

**Comment by WanWizard** [comment]
If I do the same on the master branch, it seems to work fine too. 

So I guess whatever it was, it is already addressed, and Fedora just needs to catch up (as it still has 3.2 in its repo). For the moment, I'll run from source.

Sorry to have taken your time.

**Comment by davvid** [comment]
Thanks for your careful testing and investigation.  It certainly helps us out in the future nonetheless.
