### ISSUE TITLE
Create --force-with-lease equivalent checkbox on push dialog

### ISSUE THREAD

**Issue by jm4R** [git-cola/git-cola#946]
Currently we have `force` checkbox, but `force-with-lease` is safer alternative and in most cases should be used instead:
https://git-scm.com/docs/git-push#Documentation/git-push.txt---force-with-leaseltrefnamegt

I think the version without additional arguments will be enough for now.

**Comment by davvid** [comment]
Sounds good.  Let's dig up the version number where the feature appeared and we can add a `force-with-lease` version value to the `_version` table in `cola/version.py`.

When `self.action == 'PUSH'` and `version.check_git('force-with-lease')` is true we can use `'force_with_lease'`, and `'force'` otherwise.

https://github.com/git-cola/git-cola/blob/master/cola/widgets/remote.py#L519
