### ISSUE TITLE
Integrate/edit in Qt creator

### ISSUE THREAD

**Issue by tobschu94** [git-cola/git-cola#954]
Hello,

git-cola seems interesting for my project. I would like to use some features for my own Tool with a GUI created with Qt Creator. Is there a way to open git-cola in Qt designer or get the callbacks for the GUI buttons and keys?

**Comment by davvid** [comment]
This page shows how to create a designer plugin for pyqt widgets:

https://wiki.python.org/moin/PyQt/Using_Python_Custom_Widgets_in_Qt_Designer

That approach should still work with pyqt5 I would imagine.

The simplest way to reuse the widgets is to import the modules from your code and interface with widgets in the same way as cola.  We've never really had a public API (yet) so caveat emptor, as we're still free to refactor, rename, and rewrite stuff as needed, but there are lots of things that probably won't be changing if you stick to the widget level.  As you improve things, please do feed enhancements back.

A designer plugin for cola would be pretty interesting, so if you're able to come up with a `contrib/designer/colaplugin.py` designer plugin then I'd be happy to help maintain it, and then you won't have to worry when stuff gets refactored since it'll get updated alongside cola.

Let me know if you have any questions about how stuff works.
