### ISSUE TITLE
Unable to pull or push

### ISSUE THREAD

**Issue by razaviimran** [git-cola/git-cola#958]
KARMA3@KARMA3-PC MINGW64 /e/Mega/Source/shotpixels (master)
$ git pull origin master
From https://gitlab.com/razaviimran/shotpixels
 * branch            master     -> FETCH_HEAD
fatal: refusing to merge unrelated histories

KARMA3@KARMA3-PC MINGW64 /e/Mega/Source/shotpixels (master)
$ git fetch origin

KARMA3@KARMA3-PC MINGW64 /e/Mega/Source/shotpixels (master)
$ git fetch origin master
From https://gitlab.com/razaviimran/shotpixels
 * branch            master     -> FETCH_HEAD

KARMA3@KARMA3-PC MINGW64 /e/Mega/Source/shotpixels (master)
$ git push -u origin master
To https://gitlab.com/razaviimran/shotpixels.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://gitlab.com/razaviimran/shotpixels.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

KARMA3@KARMA3-PC MINGW64 /e/Mega/Source/shotpixels (master)
$ git pull origin master
From https://gitlab.com/razaviimran/shotpixels
 * branch            master     -> FETCH_HEAD
fatal: refusing to merge unrelated histories

KARMA3@KARMA3-PC MINGW64 /e/Mega/Source/shotpixels (master)
$ git push -u origin master
To https://gitlab.com/razaviimran/shotpixels.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'https://gitlab.com/razaviimran/shotpixels.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by davvid** [comment]
Git is telling us that the commit history you have in your local repository, and the one that was pushed to gitlab, do not share the same history.  That's what it says here: `fatal: refusing to merge unrelated histories`.

The remedy to this is to use `git pull --allow-unrelated-histories origin master` if you indeed want to combine two unrelated histories.  This will merge both unrelated histories together, which will then allow you to push and pull from either sandbox.  If your version of git doesn't have that option, you can do `git merge --allow-unrelated-histories origin/master` instead.

But, before doing, that take a look at `gitk --all` or `./bin/git-dag --all` and inspect the history visually.  This is the most important step.  You should eventually find that there are two roots, not one, and your merge operation will attempt to combine them.  This is sometimes *not* what you want to do, though, since the file structure in both snapshots will need to be merged together in the event of conflicts, and only the author of both histories will know the correct content.

Without knowing how you came to have two histories, it is hard to know what the next step to do.  Sometimes the correct answer is to forget about one of the two histories, and only keep one.

For example, if you don't care about the remote history, you can force push to replace that history, but that, too, is not something that is done without inspecting the history first and being absolutely sure.

Scenario 1: Both histories are precious.  If this is the case, use the flag to merge unrelated histories.  You can deal with merge conflicts by merging files manually in your editor, or by swapping between versions of the file using `git checkout --ours <filename>` and `git checkout --theirs <filename>` when a file is in an unmerged state.  You'll eventually resolve all the conflicts and commit the result.  That can then be pushed as-is.

Scenario 2: One of the histories was temporary, not needed, and we only want to use one of the two histories.  In this scenario, open `./bin/git-dag --all`, find the commit that's the one that's the newest commit in the correct history, and then right-click and use the `Reset > Reset Hard` option to force your worktree and branch head to that commit.  You can then do a `push --force` to replace whatever is on the remote.  If the correct commit happens to be the commit that's the same as `origin/master` then force is not needed, since nothing will need to be pushed.

If you're not sure, the first scenario is "safer" in that you keep all files in both branches, but you may have to deal with your first merge conflict.
