### ISSUE TITLE
Ambiguous error message if started in non-existing directory

### ISSUE THREAD

**Issue by ookull** [git-cola/git-cola#961]
Sometimes the current directory in shell prompt does not exist. This probably can happen in Unix-like environments if directory is deleted after changing the current directory. In this condition git-cola fails to start and error message with traceback is returned. This message does not help to understand the cause of failure.

steps to reproduce:
```
> cd /tmp

> mkdir path

> cd path

> ( cd .. ; rmdir --verbose path )
rmdir: removing directory, 'path'

> pwd
/tmp/path

> cola
Traceback (most recent call last):
  File "/usr/bin/cola", line 54, in <module>
    sys.exit(main())
  File "/usr/share/git-cola/lib/cola/main.py", line 26, in main
    args = parse_args(argv)
  File "/usr/share/git-cola/lib/cola/main.py", line 38, in parse_args
    add_cola_command(subparser)
  File "/usr/share/git-cola/lib/cola/main.py", line 73, in add_cola_command
    parser = add_command(subparser, 'cola', 'start git-cola', cmd_cola)
  File "/usr/share/git-cola/lib/cola/main.py", line 68, in add_command
    app.add_common_arguments(parser)
  File "/usr/share/git-cola/lib/cola/app.py", line 386, in add_common_arguments
    parser.add_argument('-r', '--repo', metavar='<repo>', default=core.getcwd(),
FileNotFoundError: [Errno 2] No such file or directory
```

Version: 3.4
Python: 3.7.3

**Comment by davvid** [comment]
We'll have to test this on python2+3 to see if the exception-throwing behavior is different.  It's unfortunate if python3 throws an exception instead of just returning the current directory (even if it doesn't exist) because our code is already prepared to handle it.

What we can probably do is catch the exception and fallback to `$PWD` from the environment when python's getcwd fails, with `/` as a final fallback (which will trigger the prompt-for-a-repo code path to kick in).

Thanks for the heads-up, we'll see what we can do.  I'm all for making it bulletproof to these edge cases.

**Comment by ookull** [comment]
This exception is thrown by os.getcwd (or os.getcwdu in py2) that is used by core.getcwd . I tested with python2+3, both versions behave in similiar way and throws OSError (FileNotFoundError is also OSError):

```
> python3 -c 'import os ; os.getcwd()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory

> python2 -c 'import os ; os.getcwd()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [Errno 2] No such file or directory
```

Catching OSError is not enough as staying to non-existing directory will affect the later behaviour of program:
```
...
  File "/usr/share/git-cola/lib/cola/git.py", line 183, in __init__
    self.set_worktree(core.getcwd())
FileNotFoundError: [Errno 2] No such file or directory
```

I made quick hack for py3 in app.py to escape from non-existing directory before shooting the application. Just an idea as i have not explored the workflow of git-cola.

```
    # Specifies a git repository to open
    while True:
        try:
            core.getcwd()
            break
        except FileNotFoundError as err:
            os.chdir('..')
    parser.add_argument('-r', '--repo', metavar='<repo>', default=core.getcwd(),
                        help='open the specified git repository')
```

**Comment by davvid** [comment]
I was thinking that we would catch the exception in `core.getcwd()` so that all the call sites don't have to worry about it.  It should work to return the non-existing directory from there since the worktree discovery logic already handles searching up the tree.  `core.getenv('PWD', '/')` should be a sensible fallback when python raises in `core.getcwd()` during the initial setup phase.

Once the worktree is discovered we do a final chdir so `core.getcwd()` should be the only place we'll need to update.

Right now `core.getcwd` is not an actual `def` but rather a variable that points to the various possible getcwd functions.  That can be replaced with a real function, and the current `getcwd` variable can be renamed to `_getcwd` so that it can be used inside the new wrapper.

**Comment by davvid** [comment]
I ended up using a hybrid solution similar to yours where we `chdir('..')` since that was much more robust to other tracebacks from the python stdlib.  Thanks for the report, much appreciated.
