### ISSUE TITLE
Hidpi "auto" setting not working

### ISSUE THREAD

**Issue by wm4** [git-cola/git-cola#963]
Debian updated git-cola from v3.3 to v3.4. Suddenly, git-cola showed very tiny fonts. When I tried v3.3, the font was fine. I bisected it, and found that 1dffadb2f87d07eb86927fc0de2fccbd7b884817 broke this.

If I change the setting from "auto" to "2x", it's back to normal. (Changing back to "auto" breaks it again.)

If it matters, I'm forcing the DPI with environment variables, because otherwise EVERYTHING is broken (is it year of the Linux desktop yet?), here's the ``env|grep QT`` output:
```
QT_ACCESSIBILITY=1
QT_QPA_PLATFORMTHEME=qt5ct
QT_AUTO_SCREEN_SCALE_FACTOR=0
QT_SCALE_FACTOR=2
```

This generally seems to work fine for all other Qt and KDE applications I'm using (which aren't many, admittedly).

The Qt version is 5.11.3.

**Comment by davvid** [comment]
I had similar concerns when that feature was introduced.  I think it's good for most users, but we're stomping on things for users that want to explicitly control things via the environment.

I'm going to look into detecting `QT_AUTO_SCREEN_SCALE_FACTOR` or `QT_SCALE_FACTOR` and if they're present then the cola settings with be a no-op.  This will need to be documented and maybe added as a note to the Appearances configuration screen so that users don't get confused when their settings do nothing.

Alternatively, I could add a "Disable" value, which can be an explicit way to say, "hands-off, I know what I'm doing".  That actually seems like a better choice from a usability perspective.

It would be nice if "Auto" did the right thing, but it doesn't in your configuration (because, as noted, you have `QT_AUTO_SCREEN_SCALE_FACTOR=0` -- that is the same feature we use with `1` as our "Auto" mode) so we're going to need a better solution.

I'm liking the idea of a "Disable" mode so I'll likely add that shortly.

**Comment by davvid** [comment]
In addition to the new "Disable" mode, I also made it so that this feature disables itself in the presence of these variables.  This seems like the right thing to do because if you've set the variables then that means that you have a specific configuration that we shouldn't mess with.

In other words, the "Auto" mode should do the right thing in your situation now too.  "Disable" is there for users that want to opt-out of these settings wholesale.

**Comment by guoyunhe** [comment]
Telegram Desktop (though it is Qt Quick based) has a UI scale slider. Its default scale is the same as your desktop, for example, 150%. It looks like the normal size.

In Git Cola, I notice the manual scale factor has different effect. If I choose 1.5 scale, the UI is actually 1.5 times bigger than normal applications. So the total scale is 1.5 * 1.5 = 2.25
