### ISSUE TITLE
Automatic line break is not WYSIWYG (again)

### ISSUE THREAD

**Issue by wm4** [git-cola/git-cola#964]
Have this in the git-cola commit message editor window:
```
bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bl1 bl2-
bl3 bl4 bla 
```
(But without manual line breaks. Remove the manual line break after ``bl2-`` - it should be displaying it like this, though.)

Committing this and running git log shows this:
```    
    bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bl1
    bl2-bl3 bl4 bla
```
I would have expected that it looks exactly like git-cola showed it in its editor window.

This is with current git master and was like this for a longer time. It seems to be another corner case similar to other issues I reported before.

**Comment by davvid** [comment]
This is a case where we've tweaked the line wrapping algorithm to intentionally diverge from what Qt displays using their builtin wrapping solution.  We don't break on dashes because we want to preserve things like a unix `dashed-command-name` in commit messages and not split those into separate tokens.  Qt does split on dashes.

Fixing this tiny discrepancy would require a custom paintEvent implementation for the text widget, which is doable, but it's a lot of effort for a small gain.  I'll take a PR, but probably won't ever work on this issue myself since it's not really a concern in practice.

I don't ever really run into this discrepancy in practice because I don't manually wrap words with dashes.  This is probably the simplest way to workaround it.

Otherwise, if a command name happens to be near the end of the line, it's pretty easy to ignore that it's been wrapped because I rest assured that it won't be wrapped in the final commit message.

Ignorance is bliss.  Most users don't notice ;-)

It would be cool to write a better wrapped text paint event.  Qt's paint system would make it not too bad either for someone that's interested in hacking on something that's pretty reusable.

It sure would be nice if we could tell Qt to not wrap on dashes, though.  Qt seems to have a baked-in assumption that it should break on dashes.

**Comment by wm4** [comment]
> I don't ever really run into this discrepancy in practice because I don't manually wrap words with dashes. This is probably the simplest way to workaround it.

Not sure what you mean here. I don't manually wrap words in this example either (the line break in the github example is just to demonstrate where Qt inserts automatical line breaking).

**Comment by davvid** [comment]
I see.  I'll see if we can add a test case to at least get them closer.

**Comment by davvid** [comment]
I have the default textwidth of 72 and I get this in git log:
```
    bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bl1 bl2
    bl3 bl4 bla
```
The editor shows the same thing, with a break between bl2 and bl3.  The only time it'll do something different is if I manually add a dash `-` between 2-3, which will then make it keep them together on the next line, while Qt will split after the dash.  Otherwise, the behavior seems to be consistent here.  Please see the test case I pushed up -- I verified both your text and the text in the test case and there's 1:1 parity with Qt.

Here's a possibility -- is the widget wide enough?  If the widget is too thin, I believe Qt will wrap early, so please make sure the editor widget is wide enough.

**Comment by wm4** [comment]
Tried commit e1bd48e7cd61e6e2c7d744450df95cf909876751, doesn't seem like anything changed. It still behaves the way I described.

> Here's a possibility -- is the widget wide enough? If the widget is too thin, I believe Qt will wrap early, so please make sure the editor widget is wide enough.

Fairly sure, here's a screenshot: https://0x0.st/z9EI.png

**Comment by davvid** [comment]
I think we're in agreement here, or I didn't make myself clear -- "We don't break on dashes (hyphens) because we want to preserve things like a unix dashed-command-name in commit messages and not split those into separate tokens. Qt does split on dashes."

Your screenshot shows a dash, which is that exact scenario.  Qt does split on the dash.  In other words, the behavior you're seeing is by design.  It's intentional.  Since our wrapping algorithm is open, one idea would be to add an option to not special-case hyphens, which would then make it handle this tiny edge case.  Is it worth it?

We have to consider that this feature does the correct thing for the 99% case, so someone could argue that WYSIWYG is nice but not really worth it for the cognitive load of both users having to have the checkbox in their interface (and having to know about its presence), and for the project that has to carry around the extra behavior in the code to handle the optional behavior.  This is the typical "less is more" argument that folks use to avoid adding too much optional behavior/complexity/"bloat".

If someone implements an option it would need to include adequate documentation explaining the feature and why the user would want to enable the option.

My minimalist design sense is for a unix-centric audience.  Thus, I expect `command-names` and similar `lisp-fn-names` in commit messages, so I do myself a favor by special-casing the dash, and it's intentionally different from what Qt does.  You probably know this already, but maybe I didn't explain myself well.

It's unfortunate that Qt doesn't have a requisite feature to ignore dashes, but such is life, and life is short, so it's not really a big deal.  That's just my opinion, though.  For users that don't like the textwrap feature, we do provide the option to disable whole thing.  Then the user is free to format the message exactly how they want it to look.  Uncheck the "Auto Wrap Commit Messages" in the commit message widget's option menu and it's completely WYSIWYG.

What do you think, is it worth adding an option to split words on dashes when text-wrapping the commit message?  We could call it "WYSIWYG line wrapping" or something like that.  Alternatively, the current behavior could be called "Preserve dashes" and the option would be true by default.

For reference, this behavior was introduced in 91c6eea53e86c0304a1e65b4c4fbb88e09f44bfc so it would basically amount to wiring up a config.get(`cola.keepdashes', True)` to the `break_on_hypen` argument to the `word_wrap()` call in the `formatted_description()` method in `cola/widgets/commitmsg.py`.  You could then do `git config cola.keepdashes false` and it would then be WYSIWYG with what Qt is doing.

That's an argument for actually adding the option -- when the code was updated back then, it was done by plumbing the `break_on_hyphen` flag through and the call site doesn't specify it -- so it picks up the default keyword argument value of True.

In other words, the code already supports and has tests for an option to wrap on hyphens -- it's just not exposed to the user.

If you think it's worth having that option exposed then I wouldn't be opposed to reopening the issue since we can keep the option visible only in the commit message options menu, which reduces the pressure of wanting to keep the main preferences minimal.  Suggestions on what what to call it, and how to describe it in the documentation it are always appreciated.

The golden feature is to change the paint event so that Qt wraps text the way we want it to wrap.  I could be wrong -- maybe it isn't that hard to implement given that we already have a lot of the building blocks readily available, but we can ignore that if optional parity with Qt is sufficient.

Let me know what you think.

**Comment by wm4** [comment]
It's pretty bad when the text field doesn't represent the end result. But if you want behavior different from Qt, and Qt's behavior can't be adjusted, there's nothing that can be done. An option to change the behavior would probably be pointless and not used by many people.
