### ISSUE TITLE
Regression: Keyboard navigability of amend confirm dialog

### ISSUE THREAD

**Issue by ewjoachim** [git-cola/git-cola#965]
Version: 3.3 (utuntu 19.04)
Gnome: 3.32.1

![Screenshot from 2019-07-17 14-13-36](https://user-images.githubusercontent.com/1457576/61374711-56235a00-a89d-11e9-9366-b135c7d9f31d.png)

On the confirm dialog to amend a commit that's been pushed, we used to be able to change selection using tab. Now, the only way to select "Amend commit" is with the mouse.

If you point me to the general area where this is done, I might be able to do a PR :)

**Comment by davvid** [comment]
Thanks for the heads-up.  I ended up fixing this myself, but for the record some updates were needed to the `MessageBox` class in `cola/widgets/standard.py`.

In case it helps, we have a pre-existing hotkey you can use to make it even easier.  Instead of using "tab", you can use "y" to confirm the dialog, or "n" to reject it.  Tab works now too though.
