### ISSUE TITLE
Can't install git-cola

### ISSUE THREAD

**Issue by waterzch** [git-cola/git-cola#967]
I use Ubuntu 16.04. I want to install git-cola. So I use apt-get install git-cola. But the version 2.5-1 was installed. I want to install the lastest version.

**Comment by davvid** [comment]
The easiest way to get the latest version is to symlink it into your $HOME/bin directory.  e.g.

```
mkdir -p src bin
git clone git://github.com/git-cola/git-cola.git src/git-cola
(cd ./bin && ln -s ../src/git-cola/bin/git-cola && ln -s ../src/git-cola/bin/git-dag)
```
I believe ubuntu's .bashrc adds $HOME/bin to the front of your $PATH by default, so after doing that then running `git cola` should launch the latest version.  You might have to open a new shell to pickup the ~/bin directory in your path.

If my memory about ubuntu's .bashrc in incorrect, you can always do something like this to add the necessary bits to your .bashrc:

```
(echo 'PATH=$HOME/bin:"$PATH"'; echo export PATH) >> ~/.bashrc
```

Since you've already installed the system version then you should already have the necessary python dependencies installed.  cola is tiny in comparison to PyQt5 so there's not much harm in keeping the old version around for the purposes of holding onto its.  Hopefully they've packaged it to use PyQt5.

The default shebang lines in the `bin/` scripts use `#!/usr/bin/env python` so you can always tweak it in case your system needs python3 instead (we support both 2+3).

**Comment by davvid** [comment]
FWIW, Ubuntu 18.04 already has a new version.  There is also a [PPA](https://github.com/git-cola/git-cola/#ubuntu) with a newer version in case it helps.
