### ISSUE TITLE
No module named 'PySide', running on Linux 

### ISSUE THREAD

**Issue by cyboflash** [git-cola/git-cola#971]
Tried running git-cola on my Fedora 30 Linux machine. Got an error. It is below. This could be related to https://github.com/git-cola/git-cola/issues/787
```
$ git-cola
Traceback (most recent call last):
  File "/usr/share/git-cola/lib/qtpy/__init__.py", line 172, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/git-cola", line 53, in <module>
    from cola.main import main
  File "/usr/share/git-cola/lib/cola/main.py", line 6, in <module>
    from . import app
  File "/usr/share/git-cola/lib/cola/app.py", line 15, in <module>
    from qtpy import QtCore
  File "/usr/share/git-cola/lib/qtpy/__init__.py", line 178, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

```

**Comment by cyboflash** [comment]
I resolved the issue by install pyqt5, `pip3 install --user pyqt5`. This probably should be added as a prerequisite to the dnf package.

**Comment by davvid** [comment]
Yes, you'll want PyQt5.  You should have one available from the official fedora repositories.  I believe the package is called "PyQt5" e.g. `sudo dnf install PyQt5`

Please file a bug against the Fedora package so that the package maintainers know to update their dependencies.

**Comment by kmbgit** [comment]
Running Ubuntu 20.04 under Windows 10 WSL I still get the "PySide" problem even though PyQt5 is installed as a dependency of git-cola by `apt install`.  The problem is that libQt5Core.so.5 fails to load because it calls a kernel function that doesn't exist in the distribution I'm using.  The fix is to run `sudo strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5`.  See https://askubuntu.com/a/1163268/358938 for the discussion that led me to this fix.

I know this isn't git-cola's fault, but hopefully others will find this solution when they search for the same symptom as me.
