### ISSUE TITLE
Incorrect remote filled in on Push

### ISSUE THREAD

**Issue by WanWizard** [git-cola/git-cola#987]
Git-cola version: current master

Reproduce:

Open a repo "A", change something, push.
Open a repo "B" without closing git-cola, change something, push.

When the Push dialog opens, the "Remote" filled in is the remote used in the push from repo "A". If you're lucky, it doesn't exist in repo "B" and you get an error (branch does not exist in remote), if you are not, you've just pushed the branch to the wrong remote...

**Comment by davvid** [comment]
Yeah this behavior should be tweaked.  The use case is we might have multiple remotes selected, and we want to preserve that.  The real issue is that we store this setting for the widget wholesale, and we should instead remember it per-repo so that different repos can have different default selections.

Another idea is to ditch that behavior and let it do what it used to do, which is to select the configured remote corresponding to your current branch.  I think that might be a better solution.

Then if the user needs to push to multiple remotes they can select them, or they can do something like this:

https://stackoverflow.com/questions/14290113/git-pushing-code-to-two-remotes

I'd be fine going back to the old behavior and remove the feature that remembers the selected remotes, preferring the configured remote instead.

**Comment by WanWizard** [comment]
I can understand the feature could come in handy if you have only a few repo's, and all your remotes are called "origin". 

However, if you're using git for deployment, every repo has multiple remotes (in our case usually 4). Also, what "origin" is also dependents on the type of project. Sometimes it is our internal gitlab server, sometimes the clients github repo. Currently it can happen that you forget to explicitly select a remote, with the result that you push to the wrong remote. 

With all the different remote names, this feature is very annoying. So if you decide to keep it in, we would appreciate it if its behaviour could be controlled by config, so it can be switched off.

I am aware of a the commandline alternative, however, that would defeat the purpose of using cola, wouldn't it? ;-)

**Comment by davvid** [comment]
It's already gone back to the old (better) behavior where it selects the remote corresponding to the current branch in the current repo.  Please test master.
