### ISSUE TITLE
Unicode issue when displaying log messages

### ISSUE THREAD

**Issue by devillemereuil** [git-cola/git-cola#989]
When commit messages contain non-ascii characters and git-cola tries to display them (e.g. using View > DAG...), this results in a crash of the GUI with the following error message:

    /usr/share/git-cola/lib/cola/widgets/dag.py:1129: RuntimeWarning: tp_compare didn't return -1 or -2 for exception
      if change == QtWidgets.QGraphicsItem.ItemSelectedHasChanged:
    Traceback (most recent call last):
      File "/usr/share/git-cola/lib/cola/widgets/dag.py", line 1129, in itemChange
        if change == QtWidgets.QGraphicsItem.ItemSelectedHasChanged:
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 24: ordinal not in range(128)

This error seems different from #977 fixed by this [commit](https://github.com/git-cola/git-cola/commit/8f75bd6ac761f09ed961e41b92056ea68c4d1d88) for two reasons: 
1. the error is slightly different
2. compiling git-cola patched using [commit 8f75bd6ac761f09ed961e41b92056ea68c4d1d88](https://github.com/git-cola/git-cola/commit/8f75bd6ac761f09ed961e41b92056ea68c4d1d88) does not fix this issue.

Steps to reproduce in an empty folder:

    git init
    touch test
    git add test
    git commit -m "Test with é"

Then open git-cola in this folder and select View > DAG..., resulting in git-cola crashing with the above error message.

**Comment by davvid** [comment]
Hmm I'd expect  the error message to reference your local clone if you're running from source via `./bin/git-dag`.  I tried to repro but it seems to work fine here.  Hmm.

Are you using PyQt5?  The details from the "Version" tab in the `./bin/git-cola about` screen might shed some light on it.  This should work, but that RuntimeWarning is pretty weird.  Is it possible that the PyQt installation is in a funky state?  The error message is suggesting that you're getting strings in the `itemChange()` callback for the `change` value whereas most users should be getting ints that match the defines from QtWidgets.QGraphicsItem.

Are you using PySide perhaps?

**Comment by devillemereuil** [comment]
I'm using the version packaged for openSUSE Tumbleweed. If you understand RPM spec file, you can find [how the build is done here](https://build.opensuse.org/package/show/openSUSE%3AFactory/git-cola). So, this is not from source. The patch, I applied by adding it to the packaging on OBS building of the RPM, which you [can find here](https://build.opensuse.org/package/show/home:flyos:branches:devel:tools:scm/git-cola).

About in git-cola is showing the following:

    Git Cola version 3.4 
    Linux-5.2.10-1-default-x86_64-with-glibc2.2.5 
    Python (/usr/bin/python) 2.7.16 (default, Mar 04 2019, 07:13:50) [GCC] 
    Git 2.23.0 
    Qt 5.13.0 
    QtPy 1.7.1 
    PyQt5 5.13.0 

I'm not skilled enough in this part of python to definitely tell you whether I'm using PySide, what I can see however, searching for "pyside" in my packages, is that the package python3-pyside2 is not installed on my system. It doesn't show up either using `pip list` and `pip3 list`. Is this helpful?

**Comment by davvid** [comment]
Can you run from master and let me know if the behavior is the same there?

Once you can do that then I can start pushing up candidate changes that'll make it compatible with your environment.  Just clone the repo and run `./bin/git-cola` -- you don't need to install anything.  Let me know if you're able to get the current version to traceback.

**Comment by devillemereuil** [comment]
Yes, I can reproduce when cloning from git. Exact same error message from the test repository I created as explained in my first message.

**Comment by davvid** [comment]
I think there might be an issue with PyQt5 then (I am using PyQt5 5.11).  I really think this is worth reporting to the pyqt5 mailing list, and perhaps to the distro maintainer.

The behavior you're observing is super, super weird.  The `itemChange()` callback is never documented to take strings anywhere in its `itemChange(self, change, value)` signature.

The `change` field is a wrapped c++ enum and should never be a string, nor should the `QtWidgets.QGraphicsItem.ItemSelectedHasChanged` enum value ever be a string.

I can't find any documentation that specifies that this function should ever receive strings for the `change` value, so you can imagine why I'm a little bit cautious to patch this just yet.

I think it'd be worth reporting this to the openSUSE distro maintainers in case they've gotten other reports of apps breaking in their environment.  We could add some defensive measures to try and paper over it, but that's a leaky proposition if things are broken in some other way.

Also, let's see the error message pointing to your sandbox.  The reason is that the very next thing we want to do is add these lines to the code right before it crashes so that we can see the values (in my checkout that's at line 1129 in `cola/widgets/dag.py`):

```
        print(type(change))
        print(change)
        print('--')
        print(type(QtWidgets.QGraphicsItem.ItemSelectedHasChanged))
        print(QtWidgets.QGraphicsItem.ItemSelectedHasChanged)
```

The hack to test is whether this would even work?  A possible workaround is to change the conditional to this:
```
        selected_type = type(QtWidgets.QGraphicItem.ItemSelectedHasChanged)
        if (isinstance(change, selected_type)
                and change == QtWidgets.QGraphicsItem.ItemSelectedHasChanged):

```

But, that's super surprising because even the PyQt tutorials say to write it the way we've written it.  Here's an example that does the super simple normal boilerplate that we do:

https://github.com/baoboa/pyqt5/blob/master/examples/graphicsview/elasticnodes.py#L254

... and if those rules have changed then cola is not the only app that's broken.

:confused:

**Comment by davvid** [comment]
Also, something that you might be able to try is using python3, e.g. `python3 ./bin/git-cola` or tweaking the `#!` line to say "python3" instead of "python".

I'm hoping you're not running into some weird sip or pyqt5 build issue, but in any case, trying the python3 builds of the PyQt5 modules might be better supported in your distro.  In the very least, python3's default encoding is utf-8, which might help there.

**Comment by devillemereuil** [comment]
OK, here are the results of your tests:

- Using `python3 git-cola` indeed does "solve" the issue, i.e. no crash of git-cola. (Is this is a viable workaround for me in the meantime?)

- Here's the output of the various print you asked for:
```
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
23
--
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
14
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
21
--
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
14
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
22
--
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
14
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
17
--
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
14
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
18
--
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
14
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
19
--
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
14
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
20
--
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
14
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
11
--
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
14
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
16
--
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
14
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
23
--
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
14
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
21
--
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
14
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
22
--
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
14
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
17
--
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
14
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
18
--
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
14
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
19
--
<class 'PyQt5.QtWidgets.GraphicsItemChange'>
14
```
Not sure what to extract from this, but I expect you will know.

- Your fix doesn't seem to work (using `./git-cola`), it still results in a crash with the following error:
```
Traceback (most recent call last):
  File "/home/flyos/Bureau/git-cola/cola/widgets/dag.py", line 1129, in itemChange
    selected_type = type(QtWidgets.QGraphicItem.ItemSelectedHasChanged)
AttributeError: 'module' object has no attribute 'QGraphicItem'
```

I'll open a bug report in openSUSE, linking this one and report back the link.

**Comment by devillemereuil** [comment]
Here's the link to openSUSE's bugzilla:
https://bugzilla.opensuse.org/show_bug.cgi?id=1149872

**Comment by davvid** [comment]
typofix: `QGraphicsItem` instead of `QGraphicItem` -- I missed the `s` in `Graphics`.

**Comment by davvid** [comment]
Yes, using python3 is a viable solution.  We fully support python3, and since python2 is going to be EOL in 2020, distributions that are packaging cola might be keen to package it with python3 instead.

The output again is surprising because you are getting the correct enum values, which makes me wonder why the comparison would ever fail.  In any case, since it's working on python3 then it's possible that the python2 modules have some subtle build issue (for example, you get `RuntimeError` which is something that typically means there's a problem in the libraries or runtime that we don't control).

Thanks for filing the upstream bug report.   Python3 seems like the right solution at this time.

Let me know if the candidate tweak works for python2 since maybe we can make that work too.  If it doesn't work then please stick to python3 and we'll close this issue since the packaging will be handled in openSUSE.

**Comment by devillemereuil** [comment]
Sorry, but it still doesn't work when fixing the typo. To be sure, I changed line 1129 for:

```python
        selected_type = type(QtWidgets.QGraphicsItem.ItemSelectedHasChanged)
        if (isinstance(change, selected_type)
                and change == QtWidgets.QGraphicsItem.ItemSelectedHasChanged):
```
and running my test case, I obtain:
```
git-cola/cola/widgets/dag.py:1131: RuntimeWarning: tp_compare didn't return -1 or -2 for exception
  and change == QtWidgets.QGraphicsItem.ItemSelectedHasChanged):
Traceback (most recent call last):
  File "/home/flyos/Bureau/git-cola/cola/widgets/dag.py", line 1131, in itemChange
    and change == QtWidgets.QGraphicsItem.ItemSelectedHasChanged):
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 24: ordinal not in range(128)
```
So, basically, the exact same error.

**Comment by davvid** [comment]
Thanks for confirming.  I think that pretty much points at a broken Python2.7/PyQt5 `python-qt5` package in OpenSUSE.  I think that's something the OpenSUSE maintainers will need to fix, so we'll close this issue now.

The OpenSUSE packaging currently recommends either `python-qt5` or `python3-qt5` which is correct, so likely there's a bug that needs to be fixed in their `python-qt5` (python2.7) build, not their cola packaging.  Hopefully they've got a patch or bug report for that package specifically.

This repo is a good test case since it's easy to A/B test the various Python+Qt installations thanks to the qtpy library.
