### ISSUE TITLE
Unicode error "can't encode character u'\xf8'" when opening repo with odt-file

### ISSUE THREAD

**Issue by armandg** [git-cola/git-cola#990]
When opening a local repo that contains an odt-file (Libre Office text document), I get this traceback after running `env GIT_COLA_TRACE=1 git-cola`:

```
Traceback (most recent call last):
  File "/usr/share/git-cola/lib/cola/widgets/completion.py", line 444, in apply_matches
    item.setIcon(from_filename(match))
  File "/usr/share/git-cola/lib/cola/icons.py", line 103, in from_filename
    basename = basename_from_filename(filename)
  File "/usr/share/git-cola/lib/cola/icons.py", line 92, in basename_from_filename
    mimetype = mimetypes.guess_type(filename)[0]
  File "/usr/lib/python2.7/mimetypes.py", line 294, in guess_type
    return _db.guess_type(url, strict)
  File "/usr/lib/python2.7/mimetypes.py", line 114, in guess_type
    scheme, url = urllib.splittype(url)
  File "/usr/lib/python2.7/urllib.py", line 1087, in splittype
    match = _typeprog.match(url)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 78: ordinal not in range(128)
```

No issues with other repos I'm using.

Possible relation with #989.
Let me know if there's anything I can do to help with troubleshooting or giving more info.

**Comment by davvid** [comment]
Can you upload a repo somewhere public so that we can clone it and take a look?

**Comment by armandg** [comment]
I made it public now: https://github.com/armandg/aasenit

**Comment by davvid** [comment]
I'm able to launch cola in that repo.  I'm going to have to assume that the issue is something in your environment, or perhaps the directory name where you keep your code.  We should support utf8 path names so let's narrow this down further.

Please run `env >env.txt` and paste its contents here in a code block.

I'm curious about your `$HOME` directory -- is it in a non-ascii path?  I'm also curious to see if there's some locale or other weirdness that can explain it.  FWIW I just tested having repos in utf8 paths and it worked fine so we're going to need some more details.

If you're running an older version and the version in master doesn't have this issue then we should report this to the distro maintainers so they can upgrade.  What distro release are you using?

**Comment by davvid** [comment]
BTW are you also on openSUSE, or perhaps on Arch?  I've gotten reports from these distributions only, whereas the same code behaves just fine with unicode data on debian/ubuntu, fedora/rhel, and macOS.

Please clone the repo so that you can test the latest version in master and we can push up some candidate tweaks that'll get it to behave better in your environment.  For example, one thing we could do is to encode before calling into the mimetypes stdlib module, but we have to make sure it's not something more fundamental that needs adjustment.  I have a candidate change where we can try doing that, but it's hard to test since I'm unable to reproduce so I'll need you to test it out from the source tree.

You can run a dev version by running `./bin/git-cola` from a clone  -- you don't need to install anything since you already have the dependencies satisfied.

**Comment by davvid** [comment]
I put in some defensive code that should protect against this, but my test environment is very different so please do test from master.  I can help in case you run into any issues or have any questions.  Thanks for the report.

**Comment by armandg** [comment]
My env output is in the bottom for easier reading.

My `uname -a`: `Linux Solus 5.2.7-123.current #1 SMP PREEMPT Thu Aug 8 17:29:11 UTC 2019 x86_64 GNU/Linux`

My `git-cola --version`: `cola version 3.3`

Sure, I'll clone and test, and report back.

My env output:

```
SHELL=/bin/bash
COLORTERM=truecolor
XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg:/usr/share
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
HISTCONTROL=ignorespace
__GL_MaxFramesAllowed=1
GNOME_KEYRING_CONTROL=/home/geir/.cache/keyring-AQEY6Z
HISTSIZE=1000
LESS_TERMCAP_se=[0m
LESS_TERMCAP_so=[01;44;33m
DESKTOP_SESSION=i3
EDITOR=micro
GTK_MODULES=gail:atk-bridge
XDG_SEAT=seat0
PWD=/home/geir/Nextcloud/pc/aasenit
LOGNAME=geir
XDG_SESSION_DESKTOP=i3
QT_QPA_PLATFORMTHEME=gtk2
XDG_SESSION_TYPE=x11
XAUTHORITY=/home/geir/.Xauthority
TUIR_URLVIEWER=urlscan
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/geir
HOME=/home/geir
LANG=nb_NO.UTF-8
XDG_CURRENT_DESKTOP=i3
VTE_VERSION=5602
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/cf08fb8c_dc33_49c0_a052_d6cd7853663c
NVM_DIR=/home/geir/.nvm
TERM=xterm-256color
LESS_TERMCAP_mb=[01;31m
LESS_TERMCAP_me=[0m
LESS_TERMCAP_md=[01;31m
USER=geir
GNOME_TERMINAL_SERVICE=:1.1912
DISPLAY=:0
LESS_TERMCAP_ue=[0m
SHLVL=1
INPUTRC=/etc/inputrc
LESS_TERMCAP_us=[01;32m
XDG_VTNR=7
XDG_SESSION_ID=1
XDG_RUNTIME_DIR=/run/user/1000
PS1= \[[32m\]\w\[(B[m\] $ 
QT_AUTO_SCREEN_SCALE_FACTOR=0
XDG_DATA_DIRS=/usr/share:/var/lib/snapd/desktop/
PATH=/home/geir/.local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/snap/bin
HISTIGNORE=&:[bf]g:exit
GDMSESSION=i3
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-UfdyxisCfA,guid=bc081017c97157601ddee5e75d5ed205
TUIR_BROWSER=lynx
TUIR_EDITOR=micro
OLDPWD=/home/geir
_=/bin/env
```

**Comment by armandg** [comment]
Just tested from master v 3.4 and can confirm it works. I'll inform the distro maintainers.

**Comment by davvid** [comment]
Sweet, thanks for verifying.  If it helps, I can tag a new release to capture the stuff we have sitting in master.  It's all fairly stable and couldn't hurt from a new release.

**Comment by armandg** [comment]
That would be appreciated, cheers =)

**Comment by armandg** [comment]
Hey again, just checking in to let you know that a similar error happens when I enter the "Open Recent"-menu. The program crashes and gives this traceback:

```
Traceback (most recent call last):
  File "/home/geir/Nextcloud/pc/coding/git/git-cola/cola/widgets/main.py", line 730, in build_recent_menu
    for entry in settings.recent:
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2192' in position 5: ordinal not in range(128)
```

I just did a pull on the code and started clean with no settings-file.

**Comment by davvid** [comment]
Please open a bug with the openSUSE `python-qt5` and possibly their `git-cola` package so that they can update the packaging.  We've determined that this is due to a buggy PyQt5/Python2.7 package and there's nothing we can do on our end to paper over the broken environment.

As a user, your best bet is to tweak the `#!` first lines in the `bin/` scripts to say `python3` and all of these issues should go away.  You will need the `python3-qt5` package installed.

**Comment by davvid** [comment]
I'll be tagging a new release this weekend.  If you could try the python3 environment that'll give us more confidence.  I'll also be adding a note about OpenSUSE + Python3 in the release notes since we've lately had a lot of reports from OpenSUSE due to this issue.

**Comment by armandg** [comment]
Reporting back, the "dirty hack" you suggested gave me some errors from QT5, so I didn't investigate it further.
I have already notified the distro maintainers to update, so hopefully it will fix this.

**Comment by davvid** [comment]
I'm kinda curious.. what does this print in your environment?  It's UTF-8 here, even with python2.7:

        python -c 'import locale; print(locale.getpreferredencoding())'

If for some reason return ascii in your installation then that might give us a different debugging angle.

**Comment by armandg** [comment]
I receive the output "UTF-8" as well.
